### ISSUE TITLE
Wishlist: enable hiding menubar

### ISSUE THREAD

**Issue by tidux** [h3poteto/whalebird-desktop#1017]
This is more of an aesthetic thing, but on OSes without global-menubar, the menu seems to visually clash a bit with the dark theme.

**Comment by h3poteto** [comment]
Which is the menubar you referring to?
![Screenshot from 2019-08-30 09-03-52](https://user-images.githubusercontent.com/4631959/63984501-81d56900-cb06-11e9-8e5c-9cb5faa810e8.png)
