### ISSUE TITLE
Can't launch app downloaded through snap.

### ISSUE THREAD

**Issue by anarcobuda** [h3poteto/whalebird-desktop#1054]
## Description
When I try to open the app in the GNOME app list, it doesn't start.
If I try to open it with a terminal, typing 'whalebird', I get the following error message:
(whalebird:32839): Gtk-WARNING **: 09:20:15.882: cannot open display: :0

## How To Reproduce
On the terminal:
1. snap install whalebird
2. whalebird

## Your Environment
 - OS: GNU/Linux PureOS 9.0
 - Whalebird Version: 2.8.6

**Comment by h3poteto** [comment]
Hmm, I can install and run it on Ubuntu 18.04.

**Comment by h3poteto** [comment]
Oh...really? Now Whalebird don't work on Wayland.
refs: #934

**Comment by h3poteto** [comment]
Now Electron can not launch on Wayland, because Chromium which is used in Electron does not yet support Wayland. So I only have to wait for Chromium update: https://bugs.chromium.org/p/chromium/issues/detail?id=578890

**Comment by h3poteto** [comment]
The cause is same as https://github.com/h3poteto/whalebird-desktop/issues/934.
