### ISSUE TITLE
Can't open after closing

### ISSUE THREAD

**Issue by danger89** [h3poteto/whalebird-desktop#1055]
## Description
When I close Whalebird under Linux, it will still run on the background, listed in the notification area.

However, there is ONLY a close option, not an open option:
![image](https://user-images.githubusercontent.com/628926/66277074-8aedee80-e899-11e9-983a-b0ec2cfdc5ae.png)

It would be nice if there is an 'open' button as well. Like LBRY has:
![image](https://user-images.githubusercontent.com/628926/66277084-b7096f80-e899-11e9-9a12-1014d370d7ee.png)

## How To Reproduce
1. Start Whalebird
2. Close it

## Your Environment
 - OS: Linux Mint (Linux)
 - Whalebird Version: 2.8.6
 - Instance: n/a

**Comment by h3poteto** [comment]
![task](https://user-images.githubusercontent.com/4631959/66480382-84e65080-ead9-11e9-829b-b714f2ba818c.png)

It is my tray icon in Ubuntu 18.04.

My task icon shows mastodon's server names, because I logged in these server on Whalebird. Did you logged in any server on Whalebird?

**Comment by h3poteto** [comment]
On the other hand, I think that the open menu is required, so I will implement it.
Thank you.

**Comment by danger89** [comment]
I was still in the Login form indeed, so I closed the window (with login). But I couldn't open it anymore.

You are properbly right, the moment I log-in, I will see the server in the menu.
