### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by ahangarha** [h3poteto/whalebird-desktop#1058]
## Description
The app, forcefully show toots in LTR direction. This, not only aligns RTL text in wrong side but also if the text be mixed RTL/LTR, it doesn't render it in proper order.
![image](https://user-images.githubusercontent.com/11241315/66552107-a38a2d00-eb55-11e9-996d-18af60467003.png)

## How To Reproduce
1. Just see https://mastodon.host/@ahangarha/102934203632874455 toot.

## Your Environment
 - OS: Kubuntu 19.04
 - Whalebird Version: 2.8.6
 - Instance: independent of instance

**Comment by ahangarha** [comment]
I might be able to work on this. So, if no one else can work on it, you may assign this to me

**Comment by h3poteto** [comment]
Could you please take this issue? I will assign it to you.
