### ISSUE TITLE
Wrong Error: mastodon.social does not exist!!

### ISSUE THREAD

**Issue by ahangarha** [h3poteto/whalebird-desktop#1059]
## Description
While adding instance URL, when I enter mastodon.social, the app gives me this error: mastodon.social does not exist!

![image](https://user-images.githubusercontent.com/11241315/66552687-a6d1e880-eb56-11e9-8684-f9b65664170a.png)

I guess it is a bad error handling. I am from Iran and it seems this particular instance has access issue (no idea if it is censorship by the government or access restriction by the server in excuse of sanction). So I need to access the website using VPN or TOR.

## How To Reproduce
1. Be in Iran :D
2. Try to login to account on mastodon.social

## Your Environment
 - OS: Kubuntu 19.04
 - Whalebird Version: 2.8.6
 - Instance: mastodon.social

## Suggestion
Either the app should investigate more about if the instance exists or not, or it should tell us something like: "Fail to connect to the instance. Make sure the instance URL is correct, it is an instance of supported services (Mastodon, Pleroma) and..."

**Comment by h3poteto** [comment]
The issue about proxy exists: #982 
But, now Whalebird does not support proxy access, so your assumption may be right: 
>  I am from Iran and it seems this particular instance has access issue

**Comment by h3poteto** [comment]
> "Fail to connect to the instance. Make sure the instance URL is correct, it is an instance of supported services (Mastodon, Pleroma) and..."

Nice, I will change error message.
