### ISSUE TITLE
Stuck on loading, nothing is being fetched

### ISSUE THREAD

**Issue by LadyFuzztail** [h3poteto/whalebird-desktop#1075]
## Description
When I first installed and loaded Whalebird, the screen stayed stuck in the greyed out loading screen. New toots in my timeline appear, but nothing before the time the app first launched shows up. I can still send toots and look at my own direct messages, but nothing else seems to be functional.

I tried installing Node.js LTS, and that doesn't seem to have made a difference.

## Your Environment
 - OS: Windows 7 x64
 - Whalebird Version: 2.9.0
 - Instance: awoo.space

**Comment by h3poteto** [comment]
You can see your timeline in other servers?

**Comment by LadyFuzztail** [comment]
> You can see your timeline in other servers?

Yeah, snouts.online seems to work. So it may be an issue with how awoo.space specifically interacts with API requests, I'll bet.

**Comment by h3poteto** [comment]
> So it may be an issue with how awoo.space specifically interacts with API requests
I think so, too.

I have to create my account on awoo.space, becase I want to see logs when access the API endpoint. So, please wait, now I don't know the cause.

**Comment by noiob** [comment]
Awoospace requires you to be logged in for more API requests than a standard configuration of Mastodon, that might be the problem

**Comment by h3poteto** [comment]
Hmm..., I can login awoo.space on Whalebird, and I can see my timeline.
![Screenshot from 2019-12-09 23-34-10](https://user-images.githubusercontent.com/4631959/70444173-d06aaa00-1adc-11ea-962e-074bd73b3a1b.png)

I don't know why your timeline is not loaded, because I can't reproduce your bug.

**Comment by noiob** [comment]
If the issue was reading api/v1/instance without authorization, I patched that recently

**Comment by LadyFuzztail** [comment]
> If the issue was reading api/v1/instance without authorization, I patched that recently

I just checked, and it works now.
