### ISSUE TITLE
Support language filtering

### ISSUE THREAD

**Issue by runrunrirun** [h3poteto/whalebird-desktop#1107]
## Describe

It would be useful for Whalebird to support the language filtering settings like the Mastodon browser client.

https://files.catbox.moe/ja92l4.jpg

## Why

Large public instances can have a large number of toots in languages that are not understandable by a user and they may wish to filter them out of the tootstream.

**Comment by h3poteto** [comment]
This feature affects public timeline in Mastodon, so Whalebird will be same specification.

**Comment by h3poteto** [comment]
Now Mastodon does not provide a API endpoint for support language filtering. Now we can only customize these features: https://docs.joinmastodon.org/methods/accounts/preferences/

So, we have to wait to start supporting language filter API.
