### ISSUE TITLE
Hashtag search fails to retrieve timeline

### ISSUE THREAD

**Issue by DocKDE** [h3poteto/whalebird-desktop#1158]
## Description

When I search for specific hashtags, presumably large ones, whalebird loads for a long time and finally gives an error "Failed to retrieve timeline".

## How To Reproduce
1. Go to "Hashtags"
2. Type in "Linux"
3. Wait

## Your Environment
 - OS: Arch Linux
 - Whalebird Version: 3.0.0-1
 - Instance: mastodon.technology

**Comment by h3poteto** [comment]
Can you search the same tag in browser?

I think that Whalebird can not control the response speed, so the cause is server side.
