### ISSUE TITLE
Desktop file with AppImage

### ISSUE THREAD

**Issue by silvernode** [h3poteto/whalebird-desktop#1173]
## Describe
When the AppImage of Whalebird is executed for the first time, ask the user if they would like to integrate Whalebird by creating a desktop file. If user selects yes, create a desktop file with an icon.

## Why
Creating my own desktop file is fine but many Appimages do this for me. It would be nice for the user experience for this to be a feature of the Whalebird Appimage.

**Comment by h3poteto** [comment]
> Since electron-builder 21 desktop integration is not a part of produced AppImage file. AppImageLauncher is the recommended way to integrate AppImages.
https://www.electron.build/configuration/appimage

So, now I can't specify `desktop` key in build configuration for electron-builder.
Hmm...what should I do.
