### ISSUE TITLE
avatar gets a hyperlink pointer but isn't a hyperlink

### ISSUE THREAD

**Issue by arnoldbird** [h3poteto/whalebird-desktop#1178]
When I hover over my avatar in the left column, the cursor turns into a pointer as if it's a hyperlink I can click on to visit my profile.  Several clicks later I realize it's not a hyperlink and that's why clicking on it isn't leading to my profile.

Please either make the avatar link to my profile (or to something) or make it so there is no pointer cursor when the user hovers over it.

Thank you

**Comment by h3poteto** [comment]
This icon is not profile link.

If you register other accounts in Whalebird, you can switch your account to click these icons.
![Screenshot from 2019-12-23 23-05-58](https://user-images.githubusercontent.com/4631959/71362213-cc5c8300-25d8-11ea-8fb0-83e6ba31b8dd.png)

**Comment by arnoldbird** [comment]
"This icon is not profile link."  Yes, that's my point.  It isn't a link, so there should be no hyperlink pointer when we mouse over the icon.  You need to make a style change (this would be analagous to the "cursor" property in CSS) so that when the icon is not a link, there is no pointer.  https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by h3poteto** [comment]
This icon is not profile link, but it is link for another account, so it is no problem.
