### ISSUE TITLE
Debian package install missing SUID

### ISSUE THREAD

**Issue by realkinetix** [h3poteto/whalebird-desktop#1216]
## Description
I just downloaded & installed Whalebird from whalebird.social, which sends over https://github.com/h3poteto/whalebird-desktop/releases/download/3.0.3/Whalebird-3.0.3-linux-x64.deb

Trying to launch whalebird resulted in nothing, so running it from the command line produces:

`~$ whalebird 
[22474:0108/110054.445334:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Whalebird/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap
`
Checking the file in question shows:

`
ls -l /opt/Whalebird/chrome-sandbox 
-rwxr-xr-x 1 root root 5099032 Jan  8 04:41 /opt/Whalebird/chrome-sandbox
`

## Your Environment
 - OS: Debian Buster
 - Whalebird Version: 3.0.3
 - Instance: None yet

Doing a chmod 4755 on chrome-sandbox fixes the issue.

**Comment by h3poteto** [comment]
I think that I can't resolve it. Unfortunately there is no way to resolve it in Whalebird installer.

> Doing a chmod 4755 on chrome-sandbox fixes the issue.

It is correct.

To resolve this issue, 

- `CONFIG_USER_NS=y` enables the user namespaces feature

or 

- `sysctl kernel.unprivileged_userns_clone=1`

or

- `chmod 4755 chrome-sandbox`


refs: https://github.com/electron/electron/issues/17972

**Comment by realkinetix** [comment]
I'm not sure why you can't as the installer has to be run as root, so if the installation included the command to chmod the file after other tasks are complete (even if you were installing electron from npm), it would be done as part of the installation and work appropriately out of the box.

**Comment by hkockerbeck** [comment]
The problem seems to have appeared again with the `deb` package for Whalebird 6.2.1. `/opt/Whalebird/chrome-sandbox`  doesn't have the suid bit set.  This causes the start of Whalebird to be aborted:
```
[26214:0307/120019.422258:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/Whalebird/chrome-sandbox is owned by root and has mode 4755.
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

Changing the mode of the file to `4755` solves the problem, and Whalebird starts successfully. This problem didn't show up with the `deb` package for Whalebird 6.2.0.

**Comment by hkockerbeck** [comment]
The problem still persists with the `deb` package for Whalebird 6.2.2.

**Comment by hkockerbeck** [comment]
The problem still persists with the deb package for Whalebird 6.2.3.

**Comment by hkockerbeck** [comment]
@h3poteto  The problem still persists with the deb package for Whalebird 6.2.4.
