### ISSUE TITLE
Proxy function not work

### ISSUE THREAD

**Issue by raamking** [h3poteto/whalebird-desktop#1220]
tried every proxy option ， but didnt help . main window alway shows Loading .i think it because didnt resolve the domainname through proxy .so i changed  /etc/hosts to bind the ip to domain .then it wotks .

**Comment by h3poteto** [comment]
I can't reproduce it.
Please write:

- Your OS
- Whalebird version
- Mastodon domain name
- Proxy information

**Comment by h3poteto** [comment]
I can't reproduce and investigate without more information.
