### ISSUE TITLE
Options for memory management

### ISSUE THREAD

**Issue by BurnyBoi** [h3poteto/whalebird-desktop#1253]
## Describe
Requesting options for controlling how much RAM Whalebird uses. Once you start loading timelines, and especially start scrolling through pages of posts, RAM usage can be quite high. Maybe when doing this, Whalebird can unload posts that aren't on the screen to save memory?

## Why
I have a laptop with 3GB of RAM, and Whalebird eats up RAM after enough usage.

**Comment by h3poteto** [comment]
Certainly, Whalebird requires more memory when you scroll your timeline to go back older statuses. And If Whalebird can unload not displayed statuses, required memory will be decrease. I will consider it.

On the other hand, I can't improve any more under the normal usage; That is, when you are browsing your timeline without scrolling.

**Comment by h3poteto** [comment]
I introduce virtual scroll in Whalebird 4.3.0. It reduces memory usage. Please try it.
