### ISSUE TITLE
Text in "New Toot" form wraps on letter instead of word

### ISSUE THREAD

**Issue by morganmay** [h3poteto/whalebird-desktop#1263]
## Description
When I enter text in the New Toot form and come to the end of a line, the text breaks in the middle of the word instead of moving it down to the next line, i.e.
```
word1 wo
rd2 word
3
```
instead of
```
word1
word2
word3
```
This is only a problem while entering text, not when the post is submitted and displayed, but it makes the draft post much harder to read and edit.

## How To Reproduce
1. Click "Toot" button in upper-right corner of Whalebird window.
2. Enter more than one line of text in main textbox (where it says "What is on your mind?").
3. Lines break in the middle of words.

## Your Environment
 - OS: Arch Linux
 - Whalebird Version: 3.1.0-1
 - Instance: <https://octodon.social>

**Comment by jimmybrancaccio** [comment]
I can confirm the same behavior in v4.0.0.
