### ISSUE TITLE
Spell Checker

### ISSUE THREAD

**Issue by aarles** [h3poteto/whalebird-desktop#1280]
Hello! Is there a possibility of implementing a spell checker in Portuguese? Thanks!

**Comment by h3poteto** [comment]
I think that probably it is possible. After Electron v8.0.0, Electron supports build in spellchecker: https://github.com/electron/electron/pull/20897
Or there is a spellchecker library for Electron: https://github.com/electron-userland/electron-spellchecker

**Comment by jeroenpraat** [comment]
I second this. Not only for Portuguese of course, but for all available language, including English and my mother tongue Dutch.
