### ISSUE TITLE
Embed images in toots

### ISSUE THREAD

**Issue by itskiru** [h3poteto/whalebird-desktop#129]
Hi, 

That's will be great to embed images in toots and not only provide the link of the image !

You did a good job, continue like that !

**Comment by h3poteto** [comment]
Thank you.
I already implemented it, so please wait next release.
https://github.com/h3poteto/whalebird-desktop/pull/125

**Comment by h3poteto** [comment]
I released 0.2.0, and it includes this update. So I close this issue.
