### ISSUE TITLE
[misskey] failed error : ローカル等一部のタイムラインが無効化されているインスタンスにおいてエラーが表示される

### ISSUE THREAD

**Issue by tkmrgit** [h3poteto/whalebird-desktop#1320]
![LSRYZENCapture694](https://user-images.githubusercontent.com/28042693/77430074-f31b9700-6e1d-11ea-995a-0623b42596d8.png)
## Description
ローカル等一部のタイムラインが無効化されているインスタンスにおいてエラーが表示されます。エラー文を「このインスタンスでは一部のタイムラインが無効になっています」等に変更したりエラーではなく通知文程度に抑える(赤色の表示ではなく黄色やグレーの表示など)にすることを検討すると良いのではないでしょうか?

## How To Reproduce
1.misskey.io等の一部のタイムライン無効インスタンスにログイン
2.タイムライン上部にエラーが表示される

## Your Environment
 - OS: Windows 10 November 2019 Update
 - Whalebird Version: 4.0.0
 - Instance: misskey.io

**Comment by h3poteto** [comment]
むしろ無効化されているタイムラインは，fetch, streamingしない方向にしようと思っています．
https://github.com/h3poteto/whalebird-desktop/issues/1307
