### ISSUE TITLE
Make it possible to hide the Electron menu

### ISSUE THREAD

**Issue by jeroenpraat** [h3poteto/whalebird-desktop#1348]
## Describe
In other Electron you can hide the menu with the ALT key. This doesn't work in Whalebird.

## Why
Whalebird without Electron menu fits in better with other Gnome apps (and probably other desktop interfaces as well).

**Comment by h3poteto** [comment]
In Slack there is a menu to hide menu bar under `Window` -> `Always Show Menu Bar`. If it is disabled, menu bar does not appear, and it appear with `Alt` key.
