### ISSUE TITLE
Please add custom emojis

### ISSUE THREAD

**Issue by jeroenpraat** [h3poteto/whalebird-desktop#1350]
## Describe
Right now it's not possible to add the Mastodon servers custom emojis while composing a new toot. Please add this as well. Most mobile apps also have this feature.

## Why
Custom emojis are an important and original feature of Mastodon. Without it people are probably less eager to adopt Whalebird.

**Comment by h3poteto** [comment]
![Screenshot from 2020-04-04 01-11-02](https://user-images.githubusercontent.com/4631959/78382053-2c6bb800-7611-11ea-86fd-e1f4406fdab0.png)

I can use custom emojis. Can't you use this feature on your Mastodon server?

**Comment by jeroenpraat** [comment]
@h3poteto You are totally right! I didn't notice the asterix at the end of the row. My apologies for the false alarm.
