### ISSUE TITLE
Viewing an instance's public timeline without logging in

### ISSUE THREAD

**Issue by FayneAldan** [h3poteto/whalebird-desktop#1439]
## Describe
I want to be able to view an instance's public timelines from Whalebird without having to log into the instance.

## Why
There are some instances (such as [fosstodon.org](https://fosstodon.org)) where the posts interest me, but I don't really want to be a member of the instance, since I wouldn't really post there. I can't find any desktop clients that support this feature and [Toot! for iOS](https://apps.apple.com/us/app/toot/id1229021451) does this, which I really like.

**Comment by FayneAldan** [comment]
BTW, you can do this with Megalodon by not providing an access token. For example:
```js
const client = generator('mastodon', 'https://mastodon.social');
client.getLocalTimeline().then(res => {
	console.log(res.data);
});
```
You can access both the local and public timelines without an access token (assuming the server allows it). So, maybe once it confirms the domain, instead of just changing the Search button to say Login, you could add the instance to the server list and provide an interface similar to this:
![image](https://user-images.githubusercontent.com/1149870/82117124-6d381000-972b-11ea-8d5b-1297ab127123.png)

fwiw I replaced the user icon with a book icon I found from Google just to represent that the server was read-only. Alternatively, you could put an icon that just shows lines of text. The settings icon is still on the top-right so you can change unread notification settings.

**Comment by h3poteto** [comment]
I will consider your proposal. The logic is not complexity, but I have to consider UI for unauthorized users.

**Comment by FayneAldan** [comment]
I literally provided a mock-up of the UI but okay.

**Comment by h3poteto** [comment]
refs #618

**Comment by jet082** [comment]
I would really like this. Now that I've switched over from Twitter, this is the key feature for me in Fedilab and Toot! I'd ideally like it on desktop as well.

**Comment by h3poteto** [comment]
I have no intention of implementing this feature in Whalebird. Please see this article: https://medium.com/@h3poteto/im-developing-a-new-fediverse-client-application-for-desktop-fcd5b83a7ebb
Or please find another client.
