### ISSUE TITLE
Quotation Renote Support Bug / 引用Renote対応に問題がある part.1

### ISSUE THREAD

**Issue by tkmrgit** [h3poteto/whalebird-desktop#1451]
## Description
#1321 にて対応して頂いた引用Renote対応ですが、引用Renoteが行われた際に通知がフォロー扱いとなる問題があります。
There is a problem that notifications are treated as follow when a citation is made, which was addressed in #1321 

## Misskey
![asdf](https://user-images.githubusercontent.com/28042693/82221367-e2d5f300-995a-11ea-9dfd-d66a0de9553b.png)

## Whalebird 
![der](https://user-images.githubusercontent.com/28042693/82221443-f7b28680-995a-11ea-8442-4001363c5d20.png)
フォロー=Follow

## How To Reproduce
1.投稿する / Posted.
2.別のアカウントで引用Renoteする / Renote a quote in another account.
3.通知欄を確認する / Confirmation in the notification section

**Comment by h3poteto** [comment]
すみませんが，今後，基本的にissueは英語で書いてください．
Whalebirdは（ありがたいことに）非日本語話者にも多く利用してもらっているので，そういった方々がここにissueを見に来た際に，なんの情報も得られません．同じく開発者にも非日本語話者がいますが，このissueでは何も実装することができません．

**Comment by h3poteto** [comment]
I see: https://github.com/h3poteto/megalodon/blob/master/src/misskey/api_client.ts#L330
