### ISSUE TITLE
Can't install the app on Windows 10.

### ISSUE THREAD

**Issue by badyherz** [h3poteto/whalebird-desktop#1516]
I tried to download it, but Windoes Defender deletes it, saying its a trojaner.
Is it true? I mean it is showing me a file inside the .exe called something with trojaner.
Help?

**Comment by badyherz** [comment]
Windows Defender deletes it because of "Trojan:Win32/Fuery.C!cl".

**Comment by h3poteto** [comment]
Hmm...I will investigate it.
Of course, I haven't injected a trojan into this application. Maybe it is contained in Electron. I think that I have to upgrade Electron version to merge the fix.

**Comment by h3poteto** [comment]
Could you please tell me about your Windows?
Is it 64bit? or 32bit?
And which version of Whalebird application did you install?

**Comment by h3poteto** [comment]
![windows-defenderpng](https://user-images.githubusercontent.com/4631959/84043756-a76e9780-a9e1-11ea-99e6-d96bb487513d.png)
I downloaded x64, but Windows Defender detect security issues in ia32.

**Comment by badyherz** [comment]
Im using Windows 10 x64, Version 2004
and I tried to download Whalebird-4.1.2-windows-x64.exe
Here is the message:
![virus_win](https://user-images.githubusercontent.com/63217790/84046084-ec76d780-a9a9-11ea-9388-440a80b36e1f.PNG)

**Comment by h3poteto** [comment]
Thank you!

**Comment by justinabrahms** [comment]
Here's the error in english, if that's helpful.
<img width="389" alt="Annotation 2020-06-13 015147" src="https://user-images.githubusercontent.com/3853/84564704-7b705080-ad18-11ea-9891-3d56a004e6ff.png">

**Comment by h3poteto** [comment]
I updated Electron version in Whalebird 4.1.3. So I hope that this bug is fixed in latest version.

**Comment by justinabrahms** [comment]
Validated that I can install v4.1.3. Thanks! :)

**Comment by h3poteto** [comment]
@badyherz Could you please try to update Whalebird to the latest version?

**Comment by badyherz** [comment]
@h3poteto Sorry for the late answer, I was very busy ^^
Im tried to download it but it is super slow or just dont download at all.
I will wait, but kinda weird. 
![download_slow_wb](https://user-images.githubusercontent.com/63217790/85770303-0d198e00-b71b-11ea-84bb-89d7446da145.PNG)

**Comment by badyherz** [comment]
I tried different browsers but it is always very slow.

**Comment by badyherz** [comment]
After downloading it (took maybe 2 hours) I had no problems installing it! 
It works for me now! Thanks c:

**Comment by h3poteto** [comment]
I'm not sure about the download speed, the binary is located in AWS S3.
And if this problem is solved, I will close this issue. Thank you.
