### ISSUE TITLE
Loading panel does not go away after launch when using a proxy

### ISSUE THREAD

**Issue by m-col** [h3poteto/whalebird-desktop#1542]
## Description
The 'Loading...' panel doesn't go away after launch. Connectivity appears fine; I see the home feed behind the panel updating in sync with the web interface in a browser. It goes away fine when I don't use a proxy, but when I use a proxy it stays there.

I've tried with multiple proxies (http, socks5, socks5h) and they all work for connectivity but get this issue.

## How To Reproduce
- Launch whalebird with proxy setting enabled
or
- Launch whalebird without proxy (works), then enable proxy

## Your Environment
 - OS: Arch Linux
 - Whalebird Version: 4.1.1-1 or 4.1.2-1, same issue
 - Instance: fosstodon.org

**Comment by m-col** [comment]
Upon further investigation I found that the issue only arises when the firewall blocks non-proxy traffic, which suggests that whalebird is making connections outside of the proxy even when a proxy is specified

**Comment by h3poteto** [comment]
Which proxy server did you use? Please tell me the proxy server information if you can.

**Comment by m-col** [comment]
It happens with tor (as http, socks5, socks5h) as well as a commercial socks5 proxy (mullvad).

**Comment by h3poteto** [comment]
I can load timeline using proxy server, so I can't reproduce it. I think that your proxy server has some problems, but I'm not sure.
If you can provide more details of your proxy server, probably I can investigate more specific.

**Comment by m-col** [comment]
Even when non-proxy traffic is disallowed by the firewall?

The proxy server that is probably the easiest to test is the tor proxy server, which is running on localhost as both an http and socks5(h) proxy and connectivity works fine for other programs. What other information would be useful?

**Comment by m-col** [comment]
I monitored the network with netstat while launching whalebird, and tried it with and without blocking non-proxy (tor proxy) traffic with the firewall to see what the difference was. I found that electron was trying to make non-proxy connections (process name `electron --ty` by the looks of it). If the proxy is the only way to the internet, these cannot connect, and the 'loading' panel does not fade.

**Comment by h3poteto** [comment]
OK, I can reproduce it!

## Memo:
1. Install Tor Browser from [here](https://www.torproject.org/download/).
2. Setup proxy server to use tor proxy. Please use `localhost:9150` or `127.0.0.1:9150`.
3. Enable firewall to block non proxy request.
```console
$ sudo ufw enable
$ sudo ufw reject out to any port 80,443 proto tcp
$ curl --head www.debian.org
curl: (7) Failed to connect to www.debian.org port 80: 接続を拒否されました
$ curl --socks5 127.0.0.1:9150 --head www.debian.org
HTTP/1.1 302 Found
Date: Sun, 21 Jun 2020 13:30:54 GMT
Server: Apache
X-Content-Type-Options: nosniff
X-Frame-Options: sameorigin
Referrer-Policy: no-referrer
X-Xss-Protection: 1
Location: https://www.debian.org/
Content-Type: text/html; charset=iso-8859-1
```
4. Restart or reload Whalebird. Then the loading panel does not disappear. But streaming is living so some statuses are received.

**Comment by h3poteto** [comment]
Memo: I can't receive `/api/v1/instance` and `/api/v1/custom_emojis`.

**Comment by h3poteto** [comment]
I found the cause. In main process, axios can connect mastodon server using proxy, but in browser process, axios can not connect mastodon server using proxy. So websocket streaming is living, but loading panel does not disappear and can not fetch timelines.

**Comment by h3poteto** [comment]
https://www.electronjs.org/docs/api/session#sessetproxyconfig

**Comment by m-col** [comment]
Seems to be working great, thanks!
