### ISSUE TITLE
Orphaning of Arch Linux unofficial package

### ISSUE THREAD

**Issue by ariasuni** [h3poteto/whalebird-desktop#1571]
I’m maintaining the [package `whalebird-bin` on the AUR](https://aur.archlinux.org/packages/whalebird-bin/) for some time now, but I’ll stop updating it because I have other priorities. The package can easily be claimed and updated by another Arch Linux user.

**Comment by h3poteto** [comment]
Thank you for the updates so far.
Once I've tried to register the official AUR package, but there were already some unofficial packages. And I can't use `whalebird` as the package name, because the package already existed.

If you will allow me, I will update `whalebird-bin`.

**Comment by h3poteto** [comment]
I registered official AUR package: https://aur.archlinux.org/packages/whalebird

Thank you for the updates so far.
