### ISSUE TITLE
A problem with Alt-Shift keyboard layouts switch sequence

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [h3poteto/whalebird-desktop#1682]
## Description
When I press the traditional keyboard-layout-change keys sequence Alt Shift (simultaneously), menu handler triggers when Shift is pressed, defocusing from the input toot textarea and focusing the app menu.

## How To Reproduce
1. Add Alt Shift as a keyboard-layout-change key sequence at Ubuntu Mate
2. Select New toot, click at textarea
3. Press Alt
4. Not releasing Alt, press also Shift
5. Menu triggers instead of keyboard layout change trigger

## Your Environment
 - OS: Ubuntu Mate - bionic
 - Whalebird Version: 4.2.0
 - Instance: pleroma.site

**Comment by h3poteto** [comment]
Hmm... I can't reproduce it.
When I press Alt+Shift in New toot window, nothing changes. The focus does not change.

**Comment by nonlinear-chaos-order-etc-etal** [comment]
@h3poteto To reproduce it, you need at least two keyboard layouts in your OS and the Alt+Shift key as a trigger for keyboard layout change

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Though maybe it's Alt somewhere in my system as Menu bar trigger, and not on your system

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Strange. Checked keyboard and input bus settings, nothing relevant found...

**Comment by h3poteto** [comment]
OK, I will try it again.
