### ISSUE TITLE
New toot pane grows indefinitely; bottom buttons unreacahble

### ISSUE THREAD

**Issue by n8willis** [h3poteto/whalebird-desktop#1694]
## Description
Opening a new toot, either by toolbar button or menu, pops up a toot-composition window that is larger than the parent window, and seems to be actively growing in the vertical direction. So it's impossible to scroll down to the bottom of it and press the Toot or Cancel buttons (or any of the other option buttons), because the instant you reach the bottom, the composition window grows further down and they're inaccessible again. And I mean literally the instant; that's not hyperbole.

I first observed this on Saturday Aug 8; it may therefore have only appeared in the most recent update to the snap package.

## How To Reproduce
1. Open Whalebird
2. Start new toot (Ctrl-N, button, or menu)

## Your Environment
 - OS: Linux; Ubuntu 18.04.4 LTS
 - Whalebird Version: 4.2.1 via snap (stable channel)
 - Instance: mastodon.social

**Comment by h3poteto** [comment]
Could you please tell me your screen size or window size of Whalebird?

**Comment by n8willis** [comment]
Whalebird window 1000x618. Desktop 3840x2860.

**Comment by h3poteto** [comment]
OK, I will consider the composition window height when window or screen height is not enough.

**Comment by h3poteto** [comment]
@n8willis Does this problem resolve in Whalebird 4.2.2? Please try it.

**Comment by n8willis** [comment]
I am not seeing the problem on the machine I currently have access to
(laptop, which AFAIK is up-to-date so should be running the same snap
configuration as the original machine). However, the machine I first
reported this problem on is in a box right now because I moved recently. I
should be able to test it in a couple of days. Tentatively good news,
though. :)
