### ISSUE TITLE
Hangup when reloading the feed

### ISSUE THREAD

**Issue by nonlin-lin-chaos-order-etc-etal** [h3poteto/whalebird-desktop#1712]
## Description
When I click reload icon at Home feed, sometimes the Loading... indicator is eternal

Screenshot:

![изображение](https://user-images.githubusercontent.com/19966907/90840768-7ae5dd00-e38d-11ea-9e97-ecb37b1bd8a6.png)

## How To Reproduce

Unknown

## Your Environment
 - OS: Ubuntu bionic
 - Whalebird Version: 4.2.1
 - Instance: pleroma.site

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Also: I clicked Quit at tray icon menu, then the second tray icon appeared. I clicked Quit in the tray icon menu again,  the JS error box appeared (with error like `no property 'destroy' on null`).

After that, menuitems at both tray icons were no-op. So I had to `killall whalebird` to quit the app.

**Comment by h3poteto** [comment]
Whalebird always hangup when you reload?
