### ISSUE TITLE
Enable RGB font aliasing

### ISSUE THREAD

**Issue by mad-wnn** [h3poteto/whalebird-desktop#1755]
Hello,
I'm on Linux, running Birdwhale 4.2.1 and 4.2.2

I've noticed perceptual font render quality is lower than in my other apps, specificaly subpixel rendering is enforced to grayscale regardless my system settings that state RGB subpixel rendering should be used. That results in blurriness of a font.

Did a quick look up: per [https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do](https://www.electronjs.org/docs/faq#the-font-looks-blurry-what-is-this-and-what-can-i-do) an entry `backgroundColor: '#fff'` has been recommended to be passed to window constructor for blurriness to eventualy disappear.
Per above reference I did that change and that improved font rendering situation for my platform:

(result on the left, old behaviour on the right)
![Whalebird](https://user-images.githubusercontent.com/69050042/92027447-d8e9cb80-ed62-11ea-87a3-4144b3a33c17.png)

Could that change be incorporated into codebase?

**Comment by h3poteto** [comment]
Did you just add the code below? Does that alone improve it?

```javascript
const win = new BrowserWindow({
  backgroundColor: '#fff'
})
```

**Comment by mad-wnn** [comment]
Yes, inserted the `backgroundColor: '#fff'` line into
https://github.com/h3poteto/whalebird-desktop/blob/03798916c807fa0c5bf7ba8e10ff3aff148d4620/src/main/index.ts#L270-L273
.. for the resulting:
```javascript
  const mainOpts: BrowserWindowConstructorOptions = {
    backgroundColor: '#fff',
    titleBarStyle: 'hidden',
    x: mainWindowState.x,
    y: mainWindowState.y,
(...)
```
... did the job.
Sorry for lack of PR.
