### ISSUE TITLE
No access to external drives / network location for  files pictures images videos

### ISSUE THREAD

**Issue by hermann-san** [h3poteto/whalebird-desktop#1789]
I try to make a Mastodon troot with an image / files / pictures on a external drive (USB / SATA) / network location but I have no access to them.
Error message:  Could not read the contents of .....  
Error opening directory .....  : Permission denied

Linux Mint 19    Ubuntu
I can access files that are in my personal directory (Desktop, Download, Documents, etc)

Is there something I can do to fix the problem?  I can access those external / network locations from my nemo file browser as usual but not from Whalebird.
Thanks so much!

**Comment by h3poteto** [comment]
It is a bug, I will investigate.

**Comment by h3poteto** [comment]
I can't reproduce it.
When I add an image from USB, like `/run/media/h3poteto/D7A5-2C96/sample.png`, it is succeed to open and upload.

Where did you install Whalebird? Please tell me your install location of Whalebird.

**Comment by hermann-san** [comment]
I can't remember that I specified a location. Here are some locations where I've found references to Whalebird. Does that help?
![grafik](https://user-images.githubusercontent.com/7679654/93799247-3032db80-fc3f-11ea-87cc-6c45dc776108.png)

**Comment by h3poteto** [comment]
Hm... did you install Whalebird from snap?

**Comment by hermann-san** [comment]
I can't remember, but apparently yes.  It says so when I execute "snap list" . I'm actually not very familiar with snap.
whalebird          4.2.2                       93    latest/stable  h3poteto     -

**Comment by hermann-san** [comment]
so this is a restriction of snaps that need to be solved by the user?  
To my understanding, even though the user can change those setting it's advised not to do it

`Users should not attempt to override a strictly confined snap to make it ‘classic’. This undoes the confinement and interfaces defined by the developer. In addition applications published as strict snaps may misbehave when installed with the ‘–classic’ switch.`

**Comment by h3poteto** [comment]
Hmm......I'm not familiar with snap.
But could you please try to install Whalebird another way? For example [deb package](https://github.com/h3poteto/whalebird-desktop/releases/tag/4.2.3)

**Comment by hermann-san** [comment]
sure, I can try that when I have the time.
Thanks for your suggestion.
