### ISSUE TITLE
Feature request: Enable to boost, fav or bookmark using other account

### ISSUE THREAD

**Issue by Silmathoron** [h3poteto/whalebird-desktop#1801]
## Describe
When using multiple accounts, it would be nice to be able to boost/fav/bookmark a post using an account that is not the one being currently used.
This could be done by right-clicking on the button and having a dropdown menu propose "boost from account..."

## Why
This is implemented in Fedilab, for instance, and it makes multiple account experience absolutely amazing.
Instead of having to copy the link, move to the other account, move to search, find the post, then interact, this can now be done in a single click, without leaving the current account.

**Comment by h3poteto** [comment]
I'm not going to implement this feature on Whalebird, because this specification is too complicated.

**Comment by peterjc** [comment]
Ah, that's a shame. I'm currently using Ivory on iOS with multiple accounts, and love their implementation of this functionality, but can't run their desktop application. Sadly this means Whalebird isn't for me, but thank you.

**Comment by h3poteto** [comment]
@peterjc Please try Fedistar, it has this feature.
https://fedistar.net/

**Comment by peterjc** [comment]
I'll take a look - cross reference https://github.com/h3poteto/fedistar/issues/786 for replying from another account (something else Ivory makes very easy). Thank you.
