### ISSUE TITLE
Adding central Atlas Tamazight (Tamaziɣt) to crowding

### ISSUE THREAD

**Issue by hakimzenata** [h3poteto/whalebird-desktop#1845]
Language:central Atlas Tamazight 
Native name: Tamaziɣt
iso-code: tzm
Contry:Morocco (Ma)
Text direction: "Left to right"
Plural form: "One, other"
script: "Latin"
Thank you

**Comment by h3poteto** [comment]
I added it, so please translate on crowdin project : https://crowdin.com/project/whalebird

**Comment by hakimzenata** [comment]
Thanks
