### ISSUE TITLE
Bug: in Favorites and Mentions, the previous toot's three-points menu's body is hidden below the next toot's display

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [h3poteto/whalebird-desktop#1934]
## Description

See this issue's subject line and the next screenshot:

![image](https://user-images.githubusercontent.com/19966907/100462364-21681980-3105-11eb-85e3-a24ca2ac1f88.png)

## How To Reproduce
At my machine, the following reproduces this bug:
1. Add at least two toots to Favorites;
2. Open Favorites;
3. Click three points menu icon at the bottom of the top toot;
4. Observe the bug.

## Your Environment
 - OS: Ubuntu 18.04.5
 - Whalebird Version: 4.3.0

![image](https://user-images.githubusercontent.com/19966907/100462744-ae12d780-3105-11eb-829e-4dcebe35775e.png)

 - Instance: pleroma.site

**Comment by h3poteto** [comment]
The reason of this issue is same as https://github.com/h3poteto/whalebird-desktop/issues/1932

**Comment by nonlinear-chaos-order-etc-etal** [comment]
Same bug is at Mentions; a screenshot follows:

![image](https://user-images.githubusercontent.com/19966907/100472095-8a0bc200-3116-11eb-9b2f-fce5a45c066b.png)
