### ISSUE TITLE
Spell Checker always on

### ISSUE THREAD

**Issue by davalpi** [h3poteto/whalebird-desktop#2028]
## Description
The Spell Checker (English language ) is always active in New Toot windows, if you write using any other language then your tooth is totally underscored in red (**very annoying**) and corrections are given are for random English words (**very wrong**).
There is no obvious way to turn it off / change Spell Checker language.

## How To Reproduce
1. it appear in every New Toot window on Whalebird v 4.3.1 on Ubuntu 20.04 LTS ( both .deb & .appimage installation)
2. it does NOT appear in Whalebird v 4.3.1 on MacOS 10.13.4 (no spell check at all).
3. do not tryed on windows versions of Whalebird.
4. EDIT : I try to switch the GNOME interface language from English to Italian but the bug is still there..

## Your Environment
 - OS: Ubuntu 20.04 LTS ( both .deb & .appimage installation)
 - Whalebird Version: 4.3.1
 - Instance: mastodon.bida.im

NOTE: there is another issue (#1280) about Spell Checker (request to implement) but it does not specify OS.

**Comment by h3poteto** [comment]
Now Spell Checker is always enabled: https://github.com/h3poteto/whalebird-desktop/blob/e345370d34033397cdfb977333ff6480fbf8a07a/src/main/index.ts#L286
So I will make configurable it.
