### ISSUE TITLE
Visibility configuration doesn't apply when replying to others toots

### ISSUE THREAD

**Issue by xatier** [h3poteto/whalebird-desktop#2035]
## Description
It seems that the visibility preference settings is not configured properly when replying to toots.

## How To Reproduce
1. configure the visibility setting to something other than public. 
2. try to reply others toot
3. it seems to be the visibility of the reply will be set as the same visibility as the toot been replied.

It seems to be implemented here, the reply will follow the original toot's visibility. Users may desire all toots (including replies) should respect their own visibility setting.

https://github.com/h3poteto/whalebird-desktop/blob/master/src/renderer/store/TimelineSpace/Modals/NewToot.ts#L300

## Your Environment
 - OS: Archlinux 5.10.5-arch1-1
 - Whalebird Version: 4.3.1-1
 - Instance: pawoo.net

**Comment by xatier** [comment]
Related issue #569, the behavior was introduced in https://github.com/h3poteto/whalebird-desktop/pull/570/files .

I believe the more proper behavior would be:

Reply DMs with private, otherwise, reply with user's visibility setting.

**Comment by h3poteto** [comment]
This is not a bug, this is the intended specification. So your suggestion is a feature change.

**Comment by xatier** [comment]
@h3poteto I see. I didn't know this is intenal. Do you have more details on this "specification"? How do you think about this behavior change?

**Comment by h3poteto** [comment]
I think that current behavior is same as

> visibility setting applies to only new toots, replies follow the original toot's visibility.

isn't it?

**Comment by xatier** [comment]
@h3poteto that is correct. I believe the ambiguity here is that, "Customize default visibility of toot" setting does not have a clear scope. Now I understand it only applies to the new tweets, but not including replies.

As I mentioned earlier

> Users may desire all toots (including replies) should respect their own visibility setting.

If we would like to stay with the current behavior, that is fine. However, at the very least we should have some textual changes/documentations so that users understand the scope of this setting. I.e., we should mentioned in the UI that all replies will follow the original toot's visibility but not respecting this.

**Comment by h3poteto** [comment]
I understand.
I think that current behavior is useful. That is

- Visibility setting applies to only new toots
- This setting does not apply to replies, replies follow the original visibility of the toot

So, we should change the title/description of "visibility setting".

**Comment by xatier** [comment]
Sounds good! With proper description on the setting page, it should clear the confusion.
