### ISSUE TITLE
Windows desktop notifications doesn't work when user bell is activated

### ISSUE THREAD

**Issue by feli-suco** [h3poteto/whalebird-desktop#2088]
## Description
Desktop notification doesn't work when you follow an user and activate the bell function:

![image](https://user-images.githubusercontent.com/78355590/106467691-4c704000-649d-11eb-9724-02957baebef1.png)

Note that the notification is correctly received when the user is mentioned

## How To Reproduce
1. User A follow user B
2. User A activates the "bell button" for user B
3. User B post something
4. User A doesn't receive desktop notification

## Your Environment
 - OS: Windows 10
 - Whalebird Version: 4.3.2.0
 - Instance: "mastodon private instance"

**Comment by h3poteto** [comment]
> User A activates the "bell button" for user B

Where is the bell button?
I can't find it on Whalebird.

**Comment by feli-suco** [comment]
Hi! 
I mean this new feature added in mastodon:

https://github.com/tootsuite/mastodon/releases/tag/v3.3.0

![image](https://user-images.githubusercontent.com/78355590/106561925-d960db00-6529-11eb-8b2c-69b7b3f63aa7.png)

Can be found in the user profile you want to follow, example:

![image](https://user-images.githubusercontent.com/78355590/106562753-0eb9f880-652b-11eb-907b-6c059dbe0ac2.png)

Once you activate the bell button, you receive notifications each time the user post something.

I'm testing it in Chrome browser and the desktop notification is raised correctly, example:

![image](https://user-images.githubusercontent.com/78355590/106563606-542af580-652c-11eb-9ffa-d05b33c1530a.png)

I think this feature is not working in Whalebird

**Comment by h3poteto** [comment]
I see. 
I think that this issue is not a bug, it is a feature request.
