### ISSUE TITLE
Windows 10 - App Does not Shut-Down

### ISSUE THREAD

**Issue by Auraculum** [h3poteto/whalebird-desktop#2089]
## Description
Whenever I open the desktop client, and then shut it down, it remains still running in the background. Confirmed it via Task Bar and the Nexus Dock App, which also highlights still running programs. Both sources point to the application still running.

## How To Reproduce
1. Open the desktop App on Windows 10.
2. Shut it down.
3. It remains running.

## Your Environment
 - OS: Windows 10
 - Whalebird Version: 4.3.2
 - Instance: kiwifarms.cc

**Comment by h3poteto** [comment]
How to shut it down?

**Comment by Auraculum** [comment]
I'm sorry, English isn't my first language, so maybe I wasn't clear. I mean that, when I exit the application and/or shut it down, it still remains running in the background.

**Comment by Auraculum** [comment]
I'm sorry, English isn't my first language, so maybe I wasn't clear. I mean that, when I exit the application and/or shut it down, it still remains running in the background.

**Comment by h3poteto** [comment]
Is this same as https://github.com/h3poteto/whalebird-desktop/issues/2079 ?

**Comment by Auraculum** [comment]
Yes, but on Windows 10, instead of Ubuntu. Closing the application using Ctrl+Q does nothing - it's still running in the background.

**Comment by h3poteto** [comment]
OK, it is already fixed in master. So please wait next release.
