### ISSUE TITLE
Spell Checker language selection

### ISSUE THREAD

**Issue by davalpi** [h3poteto/whalebird-desktop#2128]
## Describe
It will be very useful to be able to select in which language the spell checker work.

#### Details 
The best solution ( the more practical ) will be to be able to change language directly in the "New Toot" window, as many people write toots ( and replay toots ) in more than one language (es. English and Italian ). 
But even to be able to select one spelling language in the settings will be fine.

## Why
Spell checker it's useful and convenient. It speed up writing correctly.

#### NOTE : 
I'm using Whalebird 4.3.3 and this version at least permit to turn off spell checker ( and it work good, but require to restart application, which in inconvenient ).
Here I'm suggesting an improvement of this functionality.

**Comment by h3poteto** [comment]
Memo: https://www.electronjs.org/docs/tutorial/spellchecker#how-to-set-the-languages-the-spellchecker-uses
