### ISSUE TITLE
Twitter, Parler and Facebook support

### ISSUE THREAD

**Issue by oyvindsaether** [h3poteto/whalebird-desktop#2224]
I personally don't care but I know it would be wise to support the mainstream social networks in order to attract a wide audience for this nice piece of free software.

Lots of people use closed proprietary social networks like Twitter, Parler and Facebook. People who use those who have an easier time gradually migrating to Fediverse sites if they could temporarily use both.

I know this is kind of out of scope for Whalebird, but it is something worth considering.

Cross-site posting would be another obvious feature to consider if Whalebird gets support for other social networks (so you could post the same post to say Mastodon and Twitter at the same time).

**Comment by h3poteto** [comment]
I'm not going to support Twitter and others right now. As you say it is out of scope for Whalebird.

However, I'm interested in cross-site posting, so I will continue to consider it.
