### ISSUE TITLE
Panic Report on MacOS 10.13.6 for Whalebird 4.4.0

### ISSUE THREAD

**Issue by davalpi** [h3poteto/whalebird-desktop#2321]
## Description
I have got a MacOS crash + blue kernel panic screen + reboot while running Whalebird 4.4.0
It's probably related with Whalebird as Panic Report say : 
"BSD process name corresponding to current thread: Whalebird"
and
"Preemption level underflow, possible cause unlocking an unlocked mutex or spinlock"

## How To Reproduce
1. The mac was running only this applications : Whalebird 4.4.0 + FireFox 87.0 (64 bit) (courrent)
2. The mac was put in stop ( suspend) state by energy saving settings
3. the mac was resumed then very briefly show the previuos window ( FireFox) 
4. MacOS kernel panic showing blue screen of death
5. MacOS reboot then show the "Panic Report" window with the report included ( it is expurged, if h3poteto need it I have keep the whole dump).

## Your Environment
 - OS: MacOS 10.13.6 (17G14042) ( High Sierra)
 - Whalebird Version:  4.4.0
 - Other apps running : FireFox 87.0 (64 bit) (courrent)
 - Instance: n.a.

### Note on High Sierra support by Apple 
MacOS 10.13.6 ( High Sierra) is officially unsupported by Apple as of December 2020.
But is the last version that "officially" run on my MacBook Pro (13-inch, Mid 2010).
I'm planning to do the unofficial upgrade to macOS Catalina ( 10.15) soon.

## My hypotheses
 - Possibly related with new support ( in v. 4.4.0 ) of Apple Silicon (M1) , so this releas is the first universal build for mac as an M1 + x86 build.
 - Possibly related with end of support of MacOS 10.13.6 ( High Sierra) on new Apple build enviroment ( probably used for the M1 + x86 universal build )

## Attach 
[Crash expurged del 332010.txt](https://github.com/h3poteto/whalebird-desktop/files/6252106/Crash.expurged.del.332010.txt)

**Comment by h3poteto** [comment]
Thank you for your detail report.
I'd like to confirm that does Whalebird 4.3.4 ( for x64 build ) not cause crash?

**Comment by davalpi** [comment]
I confirm, I have had no chashes with Whalebird 4.3.4 ( for x64 build ), ( the MacOS version / HW conf. was the same).
