### ISSUE TITLE
Whalebird opens in fixed full screen that prevent access any menu bar

### ISSUE THREAD

**Issue by nesfla** [h3poteto/whalebird-desktop#2508]
## Description
Whalebird opens in fixed full screen that prevent access any menu bar. The only alternative is Alt Tab to navigate and quit the app.

## How To Reproduce
1. 
![Captura de pantalla -2021-06-10 12-08-17](https://user-images.githubusercontent.com/11008671/121550748-625eb600-c9e5-11eb-818f-221a5cc25065.png)

2.
3.

## Your Environment
 - OS: Linux Mint 20.1 Ulyssa de 64 bits
 - Whalebird Version: 4.4.0
 - Instance: mastodon.la

**Comment by h3poteto** [comment]
What happens when you press F11 key?
