### ISSUE TITLE
Install rpm on openSUSE

### ISSUE THREAD

**Issue by bobblkabb** [h3poteto/whalebird-desktop#2542]
## Description

Can't install Whalebird-4.4.1-linux-x64.rpm on openSUSE because of missing dependencies:
```
error: Failed dependencies:
        libnotify is needed by Whalebird-4.4.1-1.x86_64
        libuuid is needed by Whalebird-4.4.1-1.x86_64
        nss is needed by Whalebird-4.4.1-1.x86_64
```

## How To Reproduce
1. shell: 'rpm -i Whalebird-4.4.1-linux-x64.rpm'
2.
3.

## Your Environment
 - Whalebird Version: 4.4.1
 - Instance: mastodon.social
 Operating System: openSUSE Tumbleweed 20210701
KDE Plasma Version: 5.22.2
KDE Frameworks Version: 5.83.0
Qt Version: 5.15.2
Kernel Version: 5.12.13-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6500T CPU @ 2.50GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 530

**Comment by h3poteto** [comment]
libnotify, libuuid and nss is required in Electron. So I can't control it. All I can do is wait for new Electron update.

**Comment by pgonin** [comment]
on openSUSE Leap 15.4 I could not get the RPM to install, but there is a flatpak available that does a good job 
https://flathub.org/apps/details/social.whalebird.WhalebirdDesktop
