### ISSUE TITLE
Support Poll Checkboxes / Multiple options in polls

### ISSUE THREAD

**Issue by aslmx** [h3poteto/whalebird-desktop#2567]
Not sure if Bug or missing feature.

## Describe
Whalebird does not seem to render checkboxes when a poll lets you chose multiple answers.

Whalebird should show checkboxes, when a poll allows to do so.

Edit: It should not only render the polls the correct way, it should of course also offer the possibility to create polls with checkboxes/multiple answers.

## Why
Some Polls offer multiple answers to be selected. If part of the poll audience can't choose as much option as would be possible, the poll is imho not reflecting the reality.

**Comment by h3poteto** [comment]
I see. This is a missing feature.
Now, Whalebird does not support multiple answers in polls.

**Comment by h3poteto** [comment]
Please check 6.0.0
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
