### ISSUE TITLE
google and github in imageViewer

### ISSUE THREAD

**Issue by albjeremias** [h3poteto/whalebird-desktop#2617]
## Description
Why is there github.com and google.com in the imageViewer? :shrug: 

https://github.com/h3poteto/whalebird-desktop/blob/master/spec/renderer/integration/store/TimelineSpace/Modals/ImageViewer.spec.ts#L95

**Comment by h3poteto** [comment]
There is no reason.
This is a test case, so example URL can be anything.

**Comment by albjeremias** [comment]
well yes.. because github and google are tracking us all over the internet so they can shows their ads. so it caused harm when you don't want this kind of companies to interfere in my circuits! |:

**Comment by h3poteto** [comment]
Then why not commit yourself?
