### ISSUE TITLE
whalebird .deb doesn't launch 

### ISSUE THREAD

**Issue by asmexcaliburwoods** [h3poteto/whalebird-desktop#2668]
## Description

whalebird tells

```
$ whalebird          
bash: /snap/bin/whalebird: No such file or directory
```

And immediately exits without showing any visible windows.

## How To Reproduce
1. Download https://github.com/h3poteto/whalebird-desktop/releases/download/4.4.2/Whalebird-4.4.2-linux-x64.deb
2. `apt remove --purge whalebird`
3. `snap remove whalebird`
4. Under root, `dpkg -i ~user/Downloads/Whalebird-4.4.2-linux-x64.deb`
5. Under ordinary user, 

```
$ whalebird          
bash: /snap/bin/whalebird: No such file or directory
$
```

## Your Environment
 - OS: ubuntu-mate 18.04.x
 - Whalebird Version: 4.4.2
 - Instances: mastodon.ml, shitposter.club

**Comment by h3poteto** [comment]
Your whalebird path is `/snap/bin/whalebird`, why?
After uninstall whalebird from snap, the path is incorrect.

**Comment by asmexcaliburwoods** [comment]
hmm ubuntu has done something with itself, now it works:

```
$ which whalebird
/usr/bin/whalebird
$ ls -al `which whalebird`
lrwxrwxrwx 1 root root 24 2021-08-18 20:01:39 +08 nanoseconds:730393818 /usr/bin/whalebird -> /opt/Whalebird/whalebird
```

closing
