### ISSUE TITLE
Mastodon instance is not updated

### ISSUE THREAD

**Issue by nasum** [h3poteto/whalebird-desktop#267]
Instance list of menu is not updated when adding Mastodon instance.

It seems to be updated when restarting the application

![image](https://user-images.githubusercontent.com/1456806/39119544-18aa814a-4727-11e8-85bc-132be60776cb.png)

**Comment by h3poteto** [comment]
> It seems to be updated when restarting the application

Yes, I knew it. But I allowed it as a specification.
Do you have any good way?
