### ISSUE TITLE
Multi-line notes not formatted in Misskey

### ISSUE THREAD

**Issue by bunnegirl** [h3poteto/whalebird-desktop#2675]
## Description
when logged into a misskey instance it does not format multi-line posts/paragraphs, even tho they appear fine when viewed from a mastodon instance.

## How To Reproduce
1. sign in to a misskey instance
2. write and post a note with multiple lines in it
3. confirm that when viewed, the note appears as one line

## Your Environment
 - OS: Linux
 - Whalebird Version: 4.4.1 (AppImage)
 - Instance: bunne.garden

**Comment by h3poteto** [comment]
@bunnegirl Could you please show me an example post?
