### ISSUE TITLE
Release 4.4.3 - is `sha256sum.txt` incomplete ?

### ISSUE THREAD

**Issue by Kr1ss-XD** [h3poteto/whalebird-desktop#2727]
Hi, thanks a lot for sharing this project !

While building the `whalebird-bin` AUR-package for the [4.4.3](https://github.com/h3poteto/whalebird-desktop/releases/tag/4.4.3) release, I noticed that [`sha256sums.txt`](https://github.com/h3poteto/whalebird-desktop/releases/download/4.4.3/sha256sum.txt), which used to contain the checksums of all of the binary packages for a tagged release, only contains the `Whalebird-4.4.3-darwin-universal.dmg` sha256 this time.

I'm thinking this was most likely unintentional ?

**Comment by h3poteto** [comment]
Oh, sorry, I mistake.
I updated it.

**Comment by Kr1ss-XD** [comment]
Thank you for the quick response then !
