### ISSUE TITLE
Compose Toot button?

### ISSUE THREAD

**Issue by SinaCutie** [h3poteto/whalebird-desktop#273]
Are there any plans to make a one-click "compose" option? It took me a while to find that I must click "Toot" and then "new toot" before I can use this.

**Comment by h3poteto** [comment]
I always use shortcut keys `Ctrl + n`. 
I was wondering whether or not to prepare a button. But, I was bothered by the position of the button.

Where do you think the button should be placed?

**Comment by SinaCutie** [comment]
I don't know. I have been trying to fit one in with the current UI.

Would it be possible to make `Toot -> New Toot` menu just be a `New Toot` top level menu item? Then it is a one-click step, and much easier to understand.

**Comment by h3poteto** [comment]
It is possible, and I can.

**Comment by h3poteto** [comment]
Top level menu is not accepted in mac.
