### ISSUE TITLE
Snap version

### ISSUE THREAD

**Issue by mhalano** [h3poteto/whalebird-desktop#276]
Could you create a Snap version? Lots of apps already have support on Snapstore.

**Comment by h3poteto** [comment]
I am leaving past versions [releases page](https://github.com/h3poteto/whalebird-desktop/releases). Is not this enough?

**Comment by mhalano** [comment]
Creating a Snap version the users will get an updated version automagically. Is a current trend Electron apps plus Snap format. (:

**Comment by nasum** [comment]
@mhalano Perhaps it is about the store of snapcraft?
https://snapcraft.io/

**Comment by mhalano** [comment]
@nasum 
Yes. Here https://snapcraft.io/store you have a list of lots of apps already available as Snaps and seems Electron-based apps are very popular as Snaps.

**Comment by nasum** [comment]
@mhalano I understand. Thanks !!
@h3poteto What should we do ?

**Comment by h3poteto** [comment]
OK, I see.
I found: https://github.com/electron/electron/blob/master/docs/tutorial/snapcraft.md
https://docs.snapcraft.io/build-snaps/electron

I will try to push this app in the next version.

**Comment by h3poteto** [comment]
I released version 1.0.0 and push this version to snapcraft.io.
https://snapcraft.io/whalebird

Thank you.
