### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by Kibranoz** [h3poteto/whalebird-desktop#2867]
## Describe

Whalebird should be available as a PWA instead of an electron based app. We could use our browsers to "download" the whalebird pwa. 

## Why

PWAs use the chromium of the browser which make your system use less RAM than electron 
PWAs takes up waaay less space (on chrome it can be something like <1mb), than electron application which each individually bundles chromium. 
PWas are supported on desktop by most chromium browser (Chrome, Edge, Brave, Vivaldi), on Mac, Windows,Linux and chromeOS (this would mean whalebird is accessible on chromeOS)

**Comment by h3poteto** [comment]
I don't have a plan to support PWA. Whalebird is using the main process of Electron, so it is not a web application.
And the official Mastodon frontend provides PWA, so I don't think Whalebird needs to support it.
