### ISSUE TITLE
4.5.0-beta.2 is marked as latest release?

### ISSUE THREAD

**Issue by suschizu** [h3poteto/whalebird-desktop#3062]
hello @h3poteto  - is version 4.5.0-beta.2 correctly marked as latest release?
thanks!

**Comment by h3poteto** [comment]
No, it is not the latest release. 
Of course, I released 4.5.0-beta.2 before I release 4.5.0, but GitHub doesn't detect it. I guess the cause is that I released them on the same day.

**Comment by suschizu** [comment]
Ok thanks for the information :)
