### ISSUE TITLE
Other instances timelines

### ISSUE THREAD

**Issue by vserbu** [h3poteto/whalebird-desktop#3079]
## Describe

I've discovered this feature in Fedilab client for Android and it is pretty awesome. You can add any  Mastodon or Pleroma instance home timeline as separate column in your client.

In Fedilab it looks like this:

![reorder_page](https://user-images.githubusercontent.com/57716396/150024476-6ce02c65-8ffb-4669-aeed-a4cd7738862b.png)

## Why

Because I think the main problem with Fediverse and Mastodon is discoverability. Everybody are confined into their own instances and (of course) you can take a look at the Federated timeline, but with this, you can peek into other instances timeline, find interesting people to interact and follow them, but without actually opening a new account on that particular instance. I know everybody can go to that instance homepage and click on "See what's happening", but it is too much work and lacks instant connection with people from other instances. Of course, instances admins can opt-out from peeking into their local timelines, but the vast instances are open. I know Eugen is usually against this, but I think it can be achived on the client side and I'm surprised I dont see something like this on any other clients .

**Comment by h3poteto** [comment]
I think this feature is the same as https://github.com/h3poteto/whalebird-desktop/issues/1439 and https://github.com/h3poteto/whalebird-desktop/issues/618

**Comment by vserbu** [comment]
I've found those feature requests afterwhile but I also decided to keep mine  request just to show that there is a need for that kind of feature. I really don't understand whay this feature is mainly avoided on any mastodon/fediverse client, I think it would a feature that could differ this client from all other clients now availeble. Thnx for answering, really :)

**Comment by h3poteto** [comment]
What is the difference between #1439 ?

**Comment by vserbu** [comment]
Well, using the Fedilab, you can actually post there, you can favorite toots and boost toots, so there is no limit.

**Comment by n8willis** [comment]
This is still a bug and these auto-close-things bots are unethical, anti-community, and wrong.
