### ISSUE TITLE
Advanced search 

### ISSUE THREAD

**Issue by vserbu** [h3poteto/whalebird-desktop#3080]
## Describe

It would be nice to find some kind of advanced search like https://search.noc.social/ . 

## Why

I know Eugen is against arbitrary string search because he thinks it is going to be used by spammers or other agencies for ads, but this kind of advanced account search would be beneficial when trying to create your own follower base, and it already exsists as a service, but it would be nice and usefull feature inside Mastodon client.

**Comment by h3poteto** [comment]
Does Social Search provide an API endpoint?
