### ISSUE TITLE
Some sections are empty

### ISSUE THREAD

**Issue by stemy2** [h3poteto/whalebird-desktop#3097]
## Description
The sections "notifications", "mentions" and "direct messages" are empty.

## How To Reproduce
Don't know, it appeared out of the blue and i can't get away with it.

## Your Environment
 - OS: ubuntu
 - Whalebird Version: 4.5
 - Instance: mastodon.social

**Comment by h3poteto** [comment]
Are those timelines still empty after you wait a few minutes?

**Comment by stemy2** [comment]
Yes.

Until now. A notification i just received is visible, but other previous notifications are still missing.

**Comment by h3poteto** [comment]
How about other timelines? For example, local, public, bookmark...etc.

**Comment by stemy2** [comment]
> How about other timelines? For example, local, public, bookmark...etc.

They work fine.

**Comment by stemy2** [comment]
Everything is back.
