### ISSUE TITLE
Client defined lists

### ISSUE THREAD

**Issue by vserbu** [h3poteto/whalebird-desktop#3100]
## Describe

I would like to see client defined lists, so I can have separate column for every list I create (something like we can see in Tweet-deck for Twitter)

## Why

List defined by profile on Mastodon have one problem and that is - you can not put any account on the list without following that account. But i usually make lists at e.g. Twitter because I want a separate timeline without "polluting" my main timeline with some accounts e.g. LIST NEWS where I can put any newspaper, tv or other similar accounts but without having them in my home timeline. Than e.g. LIST ANIME with all anime accounts that I want to read, but without having them in my home timeline. I think it could be beneficial.

**Comment by h3poteto** [comment]
Interesting, but it is difficult. Because Whalebird is a client application, it can not make timeline. Do you have any ideas on how to implement this feature?

**Comment by n8willis** [comment]
This is still a bug and these auto-close-things bots are unethical, anti-community, and wrong.
