### ISSUE TITLE
Animated GIFs are not displayed

### ISSUE THREAD

**Issue by gfrenoy** [h3poteto/whalebird-desktop#312]
When clicking on an animated GIF, the image is not displayed correctly:
![image](https://user-images.githubusercontent.com/981546/40144765-f905f0a4-595f-11e8-8163-db5d0ebad900.png)

where is should be:
![image](https://user-images.githubusercontent.com/981546/40144825-2136ae56-5960-11e8-8f1c-997d3353215f.png)

(sorry for the example with a cat but it was an easy one ;-p)

**Comment by nasum** [comment]
@gfrenoy Thank you for the report. It corresponds to this issue.

**Comment by gfrenoy** [comment]
Works now fine in v1.1.0 ; thanks a lot !

I noticed that now, some steady images are not always display.  But only some of them ; not sure why.  I'll open a new issue if I understand the root reason.
