### ISSUE TITLE
Configurable max message limit (for server)

### ISSUE THREAD

**Issue by seachdamh** [h3poteto/whalebird-desktop#3182]
## Describe
A option for every server/instance I use where I can configure max message limit. It is annoying on mastodon/pleroma instances where a lot of it have custom message limits to be closed in "default" 500 chars.

## Why
I general it would be best if instance reported own limits but as I know in case of mastodon authors aren't keen to sutch idea. 
But still fact is a lot of servers admin change it  and there is really a lot of instances with 512/600/5000/10000 message limits. It is simply annoying constantly go between web intrerface to write longer answer and program.

Default can be set on current 500 char as standard rule.

**Comment by h3poteto** [comment]
Whalebrid can read max character setting from API if the API has that information.
https://github.com/h3poteto/whalebird-desktop/pull/636
Most of Pleroma and Misskey servers provide that information, so if you use Pleroma/Misskey, that is set automatically.

**Comment by seachdamh** [comment]
But in case of mastodon modified server it don't work. In simplest way don't disable "send" button even if char counter is in minus (as it work now and simply block send message to this servers). Server on its own simply reject to long message so program don't have to block send it too I think.

**Comment by h3poteto** [comment]
> But in case of mastodon modified server it don't work

If you can change the limit in mastodon, mastodon API should return the value of the limit. Why mastodon authors don't change the API?

**Comment by seachdamh** [comment]
Mastodon author as I know is very critical vs. change this limit (on own official implementation) - simply there is no "official" way only admins of instance have to make own "hack". As I guess as a lot of admin aren't programmers they do it in simplest way and simply don't modify related/linked functions, vars. I agree it shuld be done in proper way in mastodon official port (as I don't see any sane reason to cling with arbitrary 500 chars messages outside adverts/buissness reasons related to oryginal twitter limits). 

I would be nice to be able to disable of force this limit on client or configure own max char limit to replace generic 500. I quess there is now sane reason to do in client to as long tweets are showed in proper  way. I know it isn't root of problem but for user it would work too.

**Comment by h3poteto** [comment]
OK, I see. I have no plans to do it, but I would be happy to review a PR.

**Comment by seachdamh** [comment]
Ok, I look to instances witch work ok and don't work and it seems in some point mastodon broke api:

Working instance: https://qoto.org/api/v1/instance

<html><body>


version | "3.2.1"
-- | --





max_toot_chars | 65535
-- | --



</body>
</html>

Broken instance: https://101010.pl/api/v1/instance

<html><body>


configuration |  
-- | --
statuses |  
max_characters | 2048
max_media_attachments | 4
characters_reserved_per_url | 23


</body>
</html>

There is significant difference between this two version. In first case whalebird see limit ok - 65535. In second case - it is default 500.
