### ISSUE TITLE
Add Ability to Launch the App but Keep Minimized in System Tray

### ISSUE THREAD

**Issue by a-techy-boi** [h3poteto/whalebird-desktop#3186]
## Describe

Add a "--hidden" (or similar) option to launch the application but keep it minimized in the system tray, how Element does it.

## Why

I like to launch some chat applications and keep them running in the background while I'm logged in.

Example (in my .xinitrc):
``` bash
#!/bin/sh

element-desktop --hidden & # Launches Element but keeps it minimized in the system tray
whalebird --hidden & # Same but for Whalebird
exec dwm
```

**Comment by h3poteto** [comment]
duplicated https://github.com/h3poteto/whalebird-desktop/issues/2660
