### ISSUE TITLE
Link on Masto toot links to whalebird.org (crypto mining) not whalebir.

### ISSUE THREAD

**Issue by APhillips-Sears** [h3poteto/whalebird-desktop#3211]

**Comment by APhillips-Sears** [comment]
Link on Masto toots posted with Whalebird to Masto direcs you to whalebird.org (crypto mining rigs) instead of https://github.com/h3poteto/whalebird-desktop

**Comment by h3poteto** [comment]
whalebird.org is not our domain. What do you mean? What is "Link on Masto toots posted with Whalebird " ?

**Comment by h3poteto** [comment]
I understand, you say this link, right?
![Screenshot from 2022-03-18-22-35-32](https://user-images.githubusercontent.com/4631959/159012578-a48c453c-5e64-4ce5-91a0-5ef05bee267c.png)

**Comment by APhillips-Sears** [comment]
THANK YOU~!
