### ISSUE TITLE
Can't install deb on Ubuntu 20.04

### ISSUE THREAD

**Issue by dhs-rec** [h3poteto/whalebird-desktop#3221]
## Description
When installing the downloaded Debian package I get the following error:
```
# apt-get install ./Whalebird-4.5.2-linux-x64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'whalebird' instead of './Whalebird-4.5.2-linux-x64.deb'
The following NEW packages will be installed:
   whalebird (4.5.2)
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/96.1 MB of archives.
After this operation, 503 MB of additional disk space will be used.
Get:1 ./Whalebird-4.5.2-linux-x64.deb whalebird amd64 4.5.2 [96.1 MB]
(Reading database ... 679455 files and directories currently installed.)
Preparing to unpack .../Whalebird-4.5.2-linux-x64.deb ...
Unpacking whalebird (4.5.2) ...
dpkg: error processing archive ./Whalebird-4.5.2-linux-x64.deb (--unpack):
 error creating hard link './usr/share/icons/hicolor/256x256/apps/whalebird.png': Invalid cross-device link
Errors were encountered while processing:
 ./Whalebird-4.5.2-linux-x64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I guess it's trying to create a hard link (`ln`) where it should create a symbolic link (`ln -s`)...
## How To Reproduce
1. Download Debian package
2. Install using above command

## Your Environment
 - OS: Ubuntu 20.04
 - Whalebird Version: 4.5.2

**Comment by h3poteto** [comment]
I can install it in clean ubuntu:20.04.
What files are there in `/usr/share/icons/hicolor/256x256` ?

**Comment by dhs-rec** [comment]
That's not relevant. The keyword above is `cross-device link`. The package is trying to create a hard link across filesystem borders, which is not possible. On your system the link source and target may reside on the **same** filesystem, but on mine that's obviously not the case. Therefor: Simply use a symbolic link.

**Comment by h3poteto** [comment]
This is electron-builder's issue.
https://github.com/electron-userland/electron-builder/issues/5721

**Comment by dhs-rec** [comment]
What's so nice about these bots?
