### ISSUE TITLE
Some images don't load when clicked on in timeline

### ISSUE THREAD

**Issue by PhotonQyv** [h3poteto/whalebird-desktop#323]
It might be something as simple as PNGs load and JPEGs don't.

Just checked with one of my own photos (a PNG), it loads if clicked, whereas a JPEG image does not.

cf.
[Toot with PNG attached](https://mastodon.xyz/@PhotonQyv/100062495197379655)
[Toot with JPEG attached](https://mastodon.xyz/@PhotonQyv/100062472414346881)

**Comment by h3poteto** [comment]
I see. The cause is this function:
https://github.com/h3poteto/whalebird-desktop/blob/master/src/renderer/components/TimelineSpace/Modals/Media.vue#L15

`.jpg` image  is loaded, but `.jpeg` isn't loaded.
