### ISSUE TITLE
Username Highlighting Doesn't Work on Misskey

### ISSUE THREAD

**Issue by wandering-girl** [h3poteto/whalebird-desktop#3247]
## Description

On my Mastodon account, if an user is mentioned on a post, their name is highlighted and takes me to their profile when I click it. On my Misskey account, however, the name isn't even highlighted.

Mastodon screenshot:
![2022-Apr-06-00:46__pyxis](https://user-images.githubusercontent.com/102764565/161897827-1e050e61-840d-459a-847d-04a83e94d73c.png)
Missley screenshot:
![2022-Apr-06-00:46__pyxis_000](https://user-images.githubusercontent.com/102764565/161897822-2f25f6bf-024f-4cd0-bfe9-31fa88ff1d31.png)

## How To Reproduce
1. Log into a Mastodon account
2. Log into a Misskey
3. Notice the difference

## Your Environment
 - OS: Arch Linux
 - Whalebird Version: 4.5.2
 - Mastodon Instance: tech.lgbt
 - Misskey Instance: slippy.xyz

**Comment by h3poteto** [comment]
This is not a bug. Misskey API does not contain html contents, so there is no information about the account. We need to implement a new feature to resolve this.
