### ISSUE TITLE
Apply dark mode to all elements

### ISSUE THREAD

**Issue by foss-** [h3poteto/whalebird-desktop#3263]
Dropdowns or + - settings as well as menus do not apply dark mode.

Locations that don't apply dark mode yet:

- [ ] In-app menus like keyboard shortcuts or the … menu per post
- [ ] Dropdown elements and + - settings
- [ ] Timeline settings (the slider icon next to the cogwheel on the top right)

![Screenshot 2022-04-11 at 09 51 48](https://user-images.githubusercontent.com/5708172/162691027-c28ddf3f-e370-44c1-ac68-6456270e6e15.png)

![Screenshot 2022-04-11 at 09 52 23](https://user-images.githubusercontent.com/5708172/162691008-8cf173f6-5306-4ea5-81f8-2b2903031403.png)

![Screenshot 2022-04-11 at 10 00 31](https://user-images.githubusercontent.com/5708172/162691535-f3b7b8da-818d-422a-a391-7a641b6197f6.png)

![Screenshot 2022-04-11 at 10 01 52](https://user-images.githubusercontent.com/5708172/162691817-7bb41a19-e4bd-458b-a33a-e80510337e0d.png)

**Comment by cyberpunkrocker-zero** [comment]
+1 for this feature/bug. Whalebird is one of the best Mastodon desktop apps, but using it with other than the basic 'light' theme is... well, this 'using-white-everywhere-feature' makes it either look very ugly or, occasionally makes its usage downright difficult.

I'd like to add some poins to OP's list:
- Even the 'Solarized Light'-theme uses the wrong white backrounds
- When using search, the interface occasionally turns partially white or transparent making the interface really messy.
- The scrollbar also turns white-backed in some situations
