### ISSUE TITLE
Crashes when drag and drop image over window

### ISSUE THREAD

**Issue by PicoSushi** [h3poteto/whalebird-desktop#327]
I tried to upload image by drag and drop it over window, but, the window continuously displayed the image and stopped working. (yes, I know D&D is unsupported, but it doesn't match the modern UI.)

Can this stopping fix? And, if you can, please implement uploading (tooting) image via D&D like Mastodon Web interface, like Slack, or like Twitter.

**Comment by h3poteto** [comment]
Oh, I didn't try to drag and drop. OK, I see.
