### ISSUE TITLE
Remember feed position at last read post not working with friendica via mastodon API

### ISSUE THREAD

**Issue by foss-** [h3poteto/whalebird-desktop#3271]
Follow-up to https://github.com/h3poteto/whalebird-desktop/issues/574

The implementation is done and `Load more posts` should trigger a new last read position to be remembered.

This is not working using a friendica account via mastodon API. To reproduce create a test account on https://squeet.me/ follow a few people to create some noise on the timeline. Or use an instance of https://dir.friendica.social/servers which is an overview of public servers.

**Reproduce**
Login to friendica account via whalebird.
With the account selected in whalebird under the cogwheel icon at the top right > Timeline activate `Load the timeline from the last reading position` for home.

**Currently**
In my tests the timeline is stuck on the same position, no matter how often I click "Load more post`scroll up or select a new tweet, whenever whalebird is re-opened the "latest" read post at the top remains the same.

**Expected**
Remember actual last read post and update last read post once a user clicks `Load more posts`.

Since this seems to work with mastodon accounts, probably friendica specific. Unsure how to further debug this though.

**Comment by h3poteto** [comment]
I didn't know frendica, you are talking about SNS frendica, which is different from Mastodon. 
https://friendi.ca/
Right?

**Comment by foss-** [comment]
Not sure what SNS frendica is, but yes I am referring to https://friendi.ca/. The public instance I suggested to reproduce is just a presonal preference as it is maintained by one of the key developers of friendica.

**Comment by h3poteto** [comment]
OK, I will try to create a new account.

**Comment by h3poteto** [comment]
[Memo]
When I access `/api/v1/markers` , it returns
```
{"error":"API endpoint POST api\/v1\/markers is not implemented","error_description":"The API endpoint is currently not implemented but might be in the future."}[]
```
with http status 200 OK.

**Comment by h3poteto** [comment]
As a premise, Whalebird does not support frendica now.

**Comment by h3poteto** [comment]
I can't reproduce this issue even though I use https://squeet.me .

**Comment by foss-** [comment]
Really strange. There is more odd things going on though for me. A new mention I received is being unmarked as read as well when I read it and then restart Whalebird.

To me this indicates that there is a broader problem with my account and whalebird. I'll try removing and readding it to see if that changes anything.

**Comment by foss-** [comment]
Installed 4.5.4 and while double checking the setting, noticed, that seeting to `Load the timeline from the last reading position` was disabled for `Home` and `Mentions`. That is surprised since it was active in 4.5.3 (see screenshot above).

However after re-enabling the setting it seems to appear working as expected. Closing this issue.

**Comment by foss-** [comment]
Was too quick to close: sadly this is persisting.

**Comment by h3poteto** [comment]
https://github.com/h3poteto/whalebird-desktop/issues/3327
