### ISSUE TITLE
Timeline randomly scrolling to top when clicking on image/video

### ISSUE THREAD

**Issue by mudgie** [h3poteto/whalebird-desktop#3272]
## Description
Seemingly randomly, when clicking on an image or video, the timeline is scrolled to the very top, as the image/video overlay appears in the foreground.

## How To Reproduce
Unsure how to reproduce, as it does not consistently happen - the issue will occur when clicking on an image/video, but then behave normally when scrolling down and clicking on the same media again.

## Your Environment
 - OS: Windows 10 Pro, version 21H2, build 19044.1586
 - Whalebird Version: Both 4.5.2 and 4.5.3
 - Instance: poa.st

**Comment by foss-** [comment]
Confirming with 4.5.4.

**Comment by hkockerbeck** [comment]
Not sure whether it is exactly the same bug, but I'd consider it similar enough to mention it here: Sometimes when I click on a toot that contains an image or video, the timeline is scrolled to the top as described above. I don't necessarily have to click the image or video itself, clicking the toot that contains it is enough to cause the problem.

Whalebird 5.4.5 on Gnome 3, Ubuntu 20.04 LTS

**Comment by NicoPy** [comment]
Same with V4.6.5 (Windows 10)
