### ISSUE TITLE
Misskey - incorrect notification messages when follow is accepted

### ISSUE THREAD

**Issue by GitHubGeek** [h3poteto/whalebird-desktop#3291]
## Description

In Misskey web UI, notification says, "Follow request accepted". However, Whalebird notification prints "Foo is now following you." (English UI message)

## How To Reproduce (Logged in as Misskey user)
1. Follow someone who's open follow
2. Check Whalebird's notification panel

## Your Environment
 - OS: Linux
 - Whalebird Version: 4.5.4
 - Instance: Misskey.ai

**Comment by h3poteto** [comment]
refs: https://github.com/h3poteto/whalebird-desktop/pull/4558
