### ISSUE TITLE
Have "Allways show sensitive content." option.

### ISSUE THREAD

**Issue by Techwolf** [h3poteto/whalebird-desktop#3362]
Need to have a way to show sensitive content without having to press a button on every image post in all timelines.

## Why
Tired of wearing out my mouse button on large timelines.

**Comment by h3poteto** [comment]
![Screenshot from 2022-05-21-09-22-07](https://user-images.githubusercontent.com/4631959/169626787-ed5bec79-49f2-4b6f-bc0d-95ee010eeeb4.png)

**Comment by Techwolf** [comment]
Does not work. I still get "show sensitive content" button. I do not want to ignore NSFW, I want to SHOW NSFW stuff. Note that "show sensitive content" does not necessarily always mean NSFW. This happens on two different account on different servers. Version 4.6.0.

**Comment by Techwolf** [comment]
WTF?! I enabled "Always ignore NSFW of medias" and it now shows it all without the buttons.

**Comment by h3poteto** [comment]
Sorry, the label is not good. "Always ignore NSFW of media" means that always show NSFW media. And in this case, "Always ignore contents warnings" is not related. It controls "CW", and does not affect "NSFW".

**Comment by Techwolf** [comment]
"Always ignore NSFW of medias" mean to ignore NSFW media so I never see it on my timeline.

**Comment by h3poteto** [comment]
Hmm... that behavior is not intended. On my machine, it works fine. 
If you needed, please open a bug issue and fill your information in it.
