### ISSUE TITLE
Proxy settings aren't saved (Win 10)

### ISSUE THREAD

**Issue by TearOfTheStar** [h3poteto/whalebird-desktop#3373]
Impossible to change proxy settings. Save button doesn't do anything (?), it always jumps back to default. Deleting all files excluding account data didn't help. Tried running as admin, same effect.

Worked on one of previous versions (not pre-latest, earlier one), don't remember exact version sadly.

 - OS: Windows 10 Pro x64 21H1
 - Latest Whalebird. Installed on non-system drive. Appdata was on system drive and non-system drive, same effect.

**Comment by h3poteto** [comment]
I confirmed, thanks.
