### ISSUE TITLE
Single letter domain doesnt work

### ISSUE THREAD

**Issue by c-shankar** [h3poteto/whalebird-desktop#3383]
## Description
Adding single letter domain name doesnt work. Gives the error "Please only enter the domain name
"

## How To Reproduce
1. Add c.im
2.
3.

## Your Environment
 - OS: Windows
 - Whalebird Version: 4.6.0.0
 - Instance: [c.im](https://c.im)

**Comment by dan-diaz** [comment]
![cimwhalebird](https://user-images.githubusercontent.com/753113/201550274-920565c3-849e-46b6-ae51-ecf72e53e685.png)

still present in v4.7.0

**Comment by h3poteto** [comment]
fixed https://github.com/h3poteto/whalebird-desktop/issues/3722
