### ISSUE TITLE
Version 4.6.0 lost half the Spanish translation

### ISSUE THREAD

**Issue by nesfla** [h3poteto/whalebird-desktop#3389]
The left panel and the ... options can't set in Spanish
![imagen](https://user-images.githubusercontent.com/11008671/171653086-ae085022-13a1-43ca-9136-79c6f0ec125d.png)

## How To Reproduce
1.
2.
3.

## Your Environment
 - OS: Kubuntu 22.04
 - Whalebird Version: 4.6.0
 - Instance: [e.g. mastodon.la]

**Comment by h3poteto** [comment]
I need to restart Whalebird after changing the language to reproduce this.
