### ISSUE TITLE
Words per toot limit

### ISSUE THREAD

**Issue by nesfla** [h3poteto/whalebird-desktop#3391]
## Description
Although my instance allows 5 thousand words per toot (and I can do this in the web browser), Whalebird only accepts 500. This is new as I could use the full range with previous versions
![imagen](https://user-images.githubusercontent.com/11008671/171678582-f864369f-8447-4603-8265-f7d82833c974.png)

## How To Reproduce
1.
2.
3.

## Your Environment
 - OS: Kubuntu 22.04
 - Whalebird Version: 4.6.0
 - Instance: mastodon.la

**Comment by seachdamh** [comment]
I( belive I reported here problem - stared from "feature request". It seems whalebird can parse older mastodon api (for example from 3.2.1 but not 3.5.1+

All with api: https://github.com/h3poteto/whalebird-desktop/issues/3182#issuecomment-1111249985

As I see you have "broken" (newer) api.

**Comment by h3poteto** [comment]
Yes, the version of `mastodon.la` is 3.5.1.
https://mastodon.la/api/v1/instance

**Comment by h3poteto** [comment]
And I will handle this issue in #3182
