### ISSUE TITLE
Extremely Slow on Windows 10

### ISSUE THREAD

**Issue by RotFarm** [h3poteto/whalebird-desktop#3510]
Thank you so much for your work on this! I don't know how this runs so slowly on windows 10 on my laptop, but runs like butter on Ubuntu., This is the best Mastodon client I've used and would like to see it get better,

**Comment by h3poteto** [comment]
What kind of behavior is slow? Streaming? Posting a status? Opening media? Switching timelines?

And please tell me the hardware specs of your computer. Windows 10 laptop, and Ubuntu.

**Comment by RotFarm** [comment]
It's slow on populating the timelines and scrolling through is verry sticky to the point of needing to install a different client.

Laptop: Windows 10 Dell G3 15"  2018/2019
Intel i5
NVIDIA I GTX 1050TI
16G RAM DDR4
1TB HDD


Desktop: Ubuntu 20.04
Ryzen 5 3600
NVIDIA RTX 3070
32G RAM DDR4
3TB HDD
500G SDD

I know they are leaps and bounds different, but the client shouldn't give me that different of an experience. Thank you for your help!


Shaughn Martel (They/He)
________________________________

**Comment by h3poteto** [comment]
Hmm... are you using Whalebird version 4.6.1?

**Comment by RotFarm** [comment]
Sorry I was just on vacation for a bit. I was using 4.6.0, but have updated
to4.6.2, but the problem persists.

**Comment by h3poteto** [comment]
I cannot reproduce it on my Windows.
Does that behavior happen on all servers? or does it happen when you use a particular server?

**Comment by RotFarm** [comment]
All servers or at least the 3 I'm part of.

Shaughn Martel (They/He)
________________________________

**Comment by h3poteto** [comment]
Please tell me about these servers.

**Comment by RotFarm** [comment]
Huh. Since just yesterday things have been working smoothly as it should. Could be I was taking up too much ram with the rest of the things I had open? Sometimes I'll also run teams and discord and even blender at the same time, but everything is good now? Sorry for taking up so much of your time.

**Comment by h3poteto** [comment]
> Could be I was taking up too much ram with the rest of the things I had open?

There is a possibility.
And did you update Whalebird recently? I updated Electron version in Whalebird 4.6.3, 4.6.4, and 4.6.5.
