### ISSUE TITLE
typo on flathub

### ISSUE THREAD

**Issue by cphuntington97** [h3poteto/whalebird-desktop#3546]
There's a typo on Flathub https://flathub.org/apps/details/social.whalebird.WhalebirdDesktop

The application name is displayed as "WhaleBrird"

**Comment by h3poteto** [comment]
It has already been fixed https://github.com/flathub/social.whalebird.WhalebirdDesktop/pull/2
but not yet released.

**Comment by cphuntington97** [comment]
Glad to hear it!
