### ISSUE TITLE
Cannot scroll navigation column - incomplete list of hashtags and/or lists

### ISSUE THREAD

**Issue by rfkat** [h3poteto/whalebird-desktop#3586]
## How To Reproduce
1. Add around 10+ lists, or hashtag timelines
2. Length of list of hashtags plus of lists exceeds vertical space on navigation column
3. No scrollbar on navigation column to navigate to bottom of list of lists

## Your Environment
 - OS: Linux
 - Whalebird Version: 4.6.0
 - Instance: any

**Comment by tuxwise** [comment]
This is still not fixed in v6.2.1, please reopen.
