### ISSUE TITLE
User defined max character amount

### ISSUE THREAD

**Issue by Maverynthia** [h3poteto/whalebird-desktop#360]
Mastodon instance owners can set custom character counts other than the 500. For example wtiches.town was 666 and the instance I'm on now allows for 2000. 
It would be nice to change the limit so I can use the 2000 my instance gives me. 
Either allow the user to change it in preferences, or somehow get the max characters from the instance. (If that's part of the API)

**Comment by h3poteto** [comment]
Thanks. OK, I see.
I will think how to set the limit. It is the best way that mastodon API returns the limit.
