### ISSUE TITLE
c.im is not a valid host

### ISSUE THREAD

**Issue by silbor** [h3poteto/whalebird-desktop#3722]
## Description
Adding C.IM is not recognised as a valid host.

## How To Reproduce
1. Try to add c.im domain https://c.im account

## Your Environment
 - OS: WIN10
 - Whalebird 4.6.5.0
 - Instance: c.im

![image](https://user-images.githubusercontent.com/111394166/198840069-437bc1a1-041a-47fb-a43f-76c81a1263f1.png)

**Comment by sfabel** [comment]
Can confirm, this is also happening on Ubuntu 22.04 with the Whalebird snap.

**Comment by silbor** [comment]
c.im also has DNS issues on Android, can anyone confirm?

**Comment by h3poteto** [comment]
probably it is a validator problem.
https://github.com/h3poteto/whalebird-desktop/blob/ec82523af0f32c0491a688f1060e7b02541a23c3/src/renderer/utils/validator.ts#L1

**Comment by sfabel** [comment]
What about this one:

`^(((?!\-))(xn\-\-)?[a-z0-9\-_]{0,61}[a-z0-9]{1,1}\.)*(xn\-\-)?([a-z0-9\-]{1,61}|[a-z0-9\-]{1,30})\.[a-z]{2,}$`

Seems to be a consensus answer for subdomain/domain matching on [StackOverflow](https://stackoverflow.com/questions/10306690/what-is-a-regular-expression-which-will-match-a-valid-domain-name-without-a-subd).

**Comment by silbor** [comment]
Bump, could you do me a favor and check if this resolves correctly in different browsers/os at all ? Eg I tested various android versions and I suspect c.im does not resolve there correctly either, so it may be a different / combined issue.

**Comment by sfabel** [comment]
@silbor It does for me. Also, Mastodon and Tusky apps both work with c.im.

**Comment by sfabel** [comment]
Created a PR: https://github.com/h3poteto/whalebird-desktop/pull/3775
