### ISSUE TITLE
Support search for accounts on other instances

### ISSUE THREAD

**Issue by maikgreubel** [h3poteto/whalebird-desktop#3724]
## Describe
I expect the search to work the same as in browser version, where it is possible to search for accounts to follow by entering there full handle also on different instances.

## Why
It is annyoing to me to use another client because of a missing feature.

**Comment by M4rc-Andre** [comment]
> ## Why
> It is annyoing to me to use another client because of a missing feature.

Yeah that bugs me too. You always have to log in via web browser and use the search there.
