### ISSUE TITLE
Pressing "r" opens new toot when searching sometimes

### ISSUE THREAD

**Issue by ChiefGyk3D** [h3poteto/whalebird-desktop#3746]
## Description
I am using Pop!_OS Linux, and sometimes when typing in a field I will press "r" to as part of the word say when searching hashtags, or usernames, or such, and will pop up the new toot menu. Sometimes i have to type in Sublime then paste it into Mastodon to get around it. But it doesn't seem to always happen. 

## Your Environment
 - OS: Pop!_OS 22.04
 - Whalebird Version: 4.6.5
 - Instance: social.chiefgyk3d.com

**Comment by h3poteto** [comment]
Ah, OK. I understand.
