### ISSUE TITLE
Wrong Domain in App Tag

### ISSUE THREAD

**Issue by tigexplorer** [h3poteto/whalebird-desktop#3767]
## Description

The "App Tag" with the name of the app "Whalebird", that's added to a toot, has the wrong url: https://whalebird.org
The url should be: https://whalebird.social
So, users are lead to an confusing site.
## How To Reproduce
1. Create a new toot
2. Show the toot in an App, that displays the App Tag
3. Klick the App Tag "Whalebird" on bottom of the toot

## Your Environment
 - OS: [e.g. MacOS]
 - Whalebird Version: [e.g. 1.0.0]
 - Instance: [e.g. mastodon.social]

**Comment by h3poteto** [comment]
Please try re-authenticate. The URL has been already changed: https://github.com/h3poteto/whalebird-desktop/blob/baba84a3854767a18ae9572a0ec369966b4954f0/src/main/auth.ts#L7

**Comment by h3poteto** [comment]
This will be resolved 5.0.0.
