### ISSUE TITLE
Tray/menubar icon

### ISSUE THREAD

**Issue by MatejLach** [h3poteto/whalebird-desktop#377]
Hi, 
Thanks a lot for Whalebird, it's been very useful. 

I'd like to ask what do you think about adding the possibility of having a 'close to tray' option, similar to Slack, which instead of closing Whalebird entirely when its main window is closed, would minimize it into a system tray icon, (menubar on the Mac). 

This has the benefit of you still being able to receive notifications, while being more space efficient than just having Whalebird minimized and allowing additional functionality, such as quickly switching between Mastodon accounts by right-clicking on the tray icon, or showing a notification badge on the icon itself and overall taking much less space in the taskbar than a minimized Whalebird window would, while also eliminating the possibility of accidentally alt-tabbing into it, if you don't want to.

Something to consider. 
Thanks and your time to work on Whalebird is much appreciated!

**Comment by h3poteto** [comment]
I understand your opinion, and I think it is useful.
But there are many points to consider: e.g. streaming background process, switch account, and Apple's guideline. And, If I implement 'close to tray', it will become useful only MacOS.
 So, I think that I can not develop it with priority.

**Comment by MatejLach** [comment]
@h3poteto I did not know about the AppStore restriction, it makes sense to me then not to include a tray icon for now then, thanks for the explanation.
