### ISSUE TITLE
Javascript error could not be dismissed

### ISSUE THREAD

**Issue by jon-ault** [h3poteto/whalebird-desktop#3770]
Whalebird put up a Javascript error message this evening that was so long it ran off the bottom of the screen (Mac OS 13, Whalebird 4.7.0). I couldn't resize or move it up to get at the bottom, no button to dismiss it was available, and I couldn't exit the app without dismissing the dialog first. I wound up having to force-quit the app.

Suggest either making the error message window resizable (so it can be made shorter), or moving the controls to the top of the window so they are always accessible.

![Screenshot 2022-11-08 at 7 20 16 PM](https://user-images.githubusercontent.com/117789280/200715785-90df8b70-55da-434b-ba05-b4c181cf842c.png)

**Comment by h3poteto** [comment]
Please write according to the format of bug template.
