### ISSUE TITLE
Change compose window for new toot to a none modal one

### ISSUE THREAD

**Issue by tigexplorer** [h3poteto/whalebird-desktop#3771]
## Describe

If one hit "New toot" the compose window is in modal mode. 
It would be nice to have this window as a none modal one.
## Why

There is no way, to switch in the main whalebird window, for example, to copy something from a toot or bio, check something in a thread etc.

**Comment by h3poteto** [comment]
I think it is an issue that should be considered. 
Which position is the best do you think? Top? Bottom? Left?

**Comment by tigexplorer** [comment]
> I think it is an issue that should be considered. Which position is the best do you think? Top? Bottom? Left?

In my opinion, bottom!
