### ISSUE TITLE
"Failed to load accounts" error after closing profile settings screen

### ISSUE THREAD

**Issue by chiizujin** [h3poteto/whalebird-desktop#3772]
## Description
This issue happens when the profile settings screen is accessed by clicking "Settings" on the pop-up menu on the down arrow at the top left of the window next to the account name. It does not happen when accessing it by clicking the cog at the top right of the screen.

After closing the profile settings screen the main feed screen goes blank, the account name disappears and a "Failed to load accounts" error is displayed.

To fix this broken state go to the application preferences screen (CTRL + ,) then close the screen. The feed reloads and goes back to normal. Clicking the reload icon near the top right while in this state results in the same error message and doesn't reload.

![whalebird](https://user-images.githubusercontent.com/1300745/200775743-c839f666-0d90-4a3c-916c-e54bffd83cce.png)

## How To Reproduce
1. Click on the down arrow at the top left of the window next to the account name.
2. Click "Settings" on the pop-up menu.
3. Click the X at the top right to close the settings screen.

## Your Environment
 - OS: Linux Mint 20.3
 - Whalebird Version: 4.7.0
 - Instance: masto.ai

**Comment by jon-ault** [comment]
It does the same thing to me running on Mac OS 13.
