### ISSUE TITLE
Timeline refresh loose current focus position

### ISSUE THREAD

**Issue by franck-paul** [h3poteto/whalebird-desktop#3773]
## Description

It should be nice to have an option to not move into a timeline (whatever is this one) even if refresh get some new items!

## How To Reproduce

1. Display a timeline (home for example)
2. Leave it for some minutes and come back after
3. The previous position in the timeline is lost and its difficult to retrieve it

## Your Environment
 - OS: MacOS
 - Whalebird Version: 4.7.0

**Comment by h3poteto** [comment]
This is not a bug.

**Comment by franck-paul** [comment]
> This is not a bug.

May be, but this behavior make the application difficult to use :-)
