### ISSUE TITLE
"lists" of hashtags

### ISSUE THREAD

**Issue by wpalmer** [h3poteto/whalebird-desktop#3779]
## Describe
I would like to be able to save a "list" including hashtags. This could be implemented by allowing "saved hashtags" to include multiple hashtags in a single save (perhaps comma-separated?)

## Why
I would like to be able to browse multiple related hashtags simultaneously, eg: a List called "aiart" which includes hashtags #aiart, #dalle, #midjourney, and #stablediffusion

**Comment by h3poteto** [comment]
I need to investigate whether Mastodon API allows these queries.
