### ISSUE TITLE
Clicking on a user handle opens profile in browser instead of the app

### ISSUE THREAD

**Issue by acidghost** [h3poteto/whalebird-desktop#3781]
## Description
Clicking on an handle in a toot opens the profile in the browser instead of the app. This seems to happen only if the handle in in the middle of the toot; if the handle is at the start (e.g. in a reply toot) it's opened correctly within the app.

## How To Reproduce
1. view a toot that mentions another user in the middle of the toot (e.g. https://infosec.exchange/@dreadpir8robots/109323662966579550)
2. click on the mention (e.g. `@jerry`)

## Your Environment
 - OS: MacOS 13.0.1
 - Whalebird Version: 4.7.0
 - Instance: https://infosec.exchange

**Comment by h3poteto** [comment]
Hmm... I don't know why. And I can't reproduce this.
In my server, I can open the user profile on Whalebird when I click a username.

**Comment by Gulagithub** [comment]
I have the same issue on Win10, 
Whalebird 4.6.5.0

If i click on a userhandle @userxyz within a toot it redirects me to the standard browser instead of staying inside Whalebird client.

**Comment by potto007** [comment]
Same thing happens for me on Whalebird 4.7.0 running MacOS 13.0.1 on Mastodon version 3.8.3 and 4.0.2 (tried on both https://hachyderm.io and https://mastodon.social).
