### ISSUE TITLE
Show multiple accounts in same (collapsible) panel

### ISSUE THREAD

**Issue by lisardggY** [h3poteto/whalebird-desktop#3783]
## Describe
Instead of having a two-tier panel for multiple accounts (first choose account, then choose panes/feeds), there should be an option to have all accounts in the same pane, and to select which options are shown for each account. For instance, I would like to have the Home, Notifications and Local feeds for one account, and only the Home and Notifications for another, in the same panel.

Existing behavior:
![image](https://user-images.githubusercontent.com/555329/201512084-472e3886-b4bb-47a8-b710-a9e371ec58b6.png)

Mockup of requested behavior:
![image](https://user-images.githubusercontent.com/555329/201512347-32edae78-b3c7-480c-8327-f1816596b982.png)

## Why
Switching between accounts should be as simple as switching between feeds for a single account, otherwise accounts that aren't in the foreground are easy to forget.

**Comment by h3poteto** [comment]
I have no intention of implementing this feature in Whalebird.
Because this breaks the simple state that can be operated by shortcut keys and introduces big complexity.
