### ISSUE TITLE
Can't log into instance

### ISSUE THREAD

**Issue by cedewey** [h3poteto/whalebird-desktop#3785]
I just installed Whalebird and after I paste in the authorization code and click "Submit" the application hangs indefinitely, never succeeding in logging me into my instance.

**Comment by h3poteto** [comment]
Please write according to the format of bug template.

**Comment by jakjakob** [comment]
I have to the problem. c.im is standard marked red. Does it maybe has a min. character limit that blocks it?

**Comment by jakjakob** [comment]
macOs Ventura, App Store
