### ISSUE TITLE
Doesn't let me log in to my instance on MacOs

### ISSUE THREAD

**Issue by jakjakob** [h3poteto/whalebird-desktop#3786]
Description
Just wanted to try Whalebird, but as I entered my instance, c.im it won't let me continue (see screenshots)
<img width="1470" alt="Bildschirm­foto 2022-11-14 um 00 02 41" src="https://user-images.githubusercontent.com/118139800/201549432-783e2b7f-adde-4096-b17b-9c8f976fb75e.png">
<img width="1470" alt="Bildschirm­foto 2022-11-14 um 00 03 00" src="https://user-images.githubusercontent.com/118139800/201549428-2e2109c0-3d67-4ac0-9bdd-5cc012e249bd.png">
To reproduce
1. Open the app
2. enter c.im as domain name

My Environment
 - OS: MacOS Ventura 13.0.1
 - Whalebird Version: 4.7.0 (App Store)
 - Instance: c.im

**Comment by h3poteto** [comment]
duplicated https://github.com/h3poteto/whalebird-desktop/issues/3722
