### ISSUE TITLE
Can't log into pxelfeed instance

### ISSUE THREAD

**Issue by ZeroDot1** [h3poteto/whalebird-desktop#3790]
I can't log in because I can't get an autentification code.

https://pixelfed.de/oauth/authorize?

CC @dansup

![Bildschirmfoto vom 2022-11-15 21-28-16](https://user-images.githubusercontent.com/28985171/202019241-cd23b711-6713-476a-a07d-d6bad028dd85.png)

**Comment by h3poteto** [comment]
Pixelfed is not supported yet.
https://github.com/h3poteto/whalebird-desktop/issues/1156
