### ISSUE TITLE
start initially closed

### ISSUE THREAD

**Issue by muellerto** [h3poteto/whalebird-desktop#3794]
## Describe
When Whalebird is to be started automatically after a user login start it initially closed. It will probably NEVER happen that the first action the user wants to do is to send a toot.

## Why
It's annoying that I must close this window every day at least one time. All (!) other tray applications do start initially closed.

**Comment by h3poteto** [comment]
Duplicated: https://github.com/h3poteto/whalebird-desktop/issues/2660
Check existing issues before you create an issue.

**Comment by muellerto** [comment]
Yes, but why do I still have this issue more than a year later?

**Comment by h3poteto** [comment]
Because no one takes this issue.
