### ISSUE TITLE
About dialog not modal

### ISSUE THREAD

**Issue by muellerto** [h3poteto/whalebird-desktop#3795]
## Description
The About dialog is not modal and can be opened in multiple instances. When you have "focus follows mouse" (also called X-mouse) behavior such a window can easily get into background.

## How To Reproduce
Just try it.

## Your Environment
 - OS: Windows 11
 - Whalebird Version: 4.6.2.0
 - Instance: mastodon.online (doesn't matter at all)

**Comment by h3poteto** [comment]
I can't understand what is wrong

**Comment by muellerto** [comment]
I call this a problem to have multiple About dialogs in background for nothing.

**Comment by h3poteto** [comment]
Is it a problem that we can open multiple about dialogs?

**Comment by muellerto** [comment]
No, not at all, ridiculous useless crap is not a problem, it's all a question of definition.

(It's just ten minutes of work or so. You must just change one single function call, that's all, then it would be as in every other application. - I tried to help you with your application. I'm the user. You don't need to take this serious. Let people ask about this About mystery and then discuss with them. That's what they expect from issue handling.)

**Comment by h3poteto** [comment]
> It's just ten minutes of work or so. You must just change one single function call, that's al

If you think so, do it yourself. This is OSS, I look forward to your PR.

**Comment by muellerto** [comment]
Of course! The user fixes any unknown software he just stumbled over himself, that's a really great approach. Why do software projects have issue management and all that? If that's not needed at all?

I have a life. Especially I have a 10-hour-job. And I have own software projects. - I don't have the time for that.

I will uninstall it now. Not because it's so bad but because your unlikely issue handling and this ridiculous discussion nobody needs. I just tried to give you some hints in what aspect you can improve your software - you, not me.

P.S.: Want to know the first impression I had of your Whalebird? - Somehow loveless. And this is what also this discussion demonstrates.

**Comment by h3poteto** [comment]
thanks for the useless advice
