### ISSUE TITLE
Answer with the same status

### ISSUE THREAD

**Issue by Grazouillis** [h3poteto/whalebird-desktop#380]
Hello H3Potato,

Thanks for Whalebird, it is very promising !
I was hesitating before suggestion or troubleshooting here, because this lack is very annoying to me
When we answer to a toot`*`, the status is "public" by default, even if the first one is a private message...
Is it possible to improve you app for a better privacy, please ? :)

Have a good day ;)

`*` (I'm using Linux/Xubuntu 18.04)

**Comment by h3poteto** [comment]
Thank you for using.

OK, I see. 
I think that it it better to inherit the privacy level from source toot. I will investigate who to implement it.
