### ISSUE TITLE
Multiple columns for different timelines.

### ISSUE THREAD

**Issue by Ailean** [h3poteto/whalebird-desktop#3801]
## Describe
I would like to have the possibility to have multiple timelines in columns next to each other. For example [home][DM][local timeline][hashtag]. Like you can in the Mastodon browser instances (and for instance Tweetdeck in a browser).

## Why
It gives me a chance to follow more things at the same time. Especially the local timeline where interesting things/people might be posting which would give me a chance to follow them.

**Comment by h3poteto** [comment]
I have no intention of implementing this feature in Whalebird. Please see this article: https://medium.com/@h3poteto/im-developing-a-new-fediverse-client-application-for-desktop-fcd5b83a7ebb
Or please find another client.
