### ISSUE TITLE
Break textarea when using backquotes

### ISSUE THREAD

**Issue by akito19** [h3poteto/whalebird-desktop#382]
## Description
Toot's textarea is broken when using backquotes.

![use_backquotes](https://user-images.githubusercontent.com/8242734/41198778-96175298-6cc0-11e8-90dc-27ab450e11ae.gif)

## How To Reproduce
1. Use backquote on toot modal.

## Your Environment
 - OS: macOS 10.13.4, Ubuntu 18.04 LTS
 - Whalebird Version: 1.3.0
 - Instance: mstdn.jp

**Comment by h3poteto** [comment]
This is due to the font which is used in this application.

**Comment by h3poteto** [comment]
https://github.com/googlei18n/noto-fonts/issues/736
