### ISSUE TITLE
Misskey - Notifications username gets messed up for server-local emoji reactions

### ISSUE THREAD

**Issue by runrunrirun** [h3poteto/whalebird-desktop#3822]
People leaving emoji reactions on smug.moe Misskey server causes rendering issues with the username in the Notifications panel.
I believe these are server-local emoji.

https://files.catbox.moe/gsf2ym.png

**Comment by h3poteto** [comment]
refs: https://github.com/h3poteto/whalebird-desktop/pull/4558
