### ISSUE TITLE
Option to disable sounds

### ISSUE THREAD

**Issue by vmbrasseur** [h3poteto/whalebird-desktop#3823]
## Describe

When I send a toot the app emits a sound.

## Why

Sound notifications are very disruptive for me. I disable them on all apps, but there is no option to disable them on Whalebird (as far as I can see).

**Comment by h3poteto** [comment]
![Screenshot from 2022-11-23-10-10-38](https://user-images.githubusercontent.com/4631959/203451515-d7c1daae-5367-4ac2-9525-2630d2244739.png)
Already implemented. Please open Preferences -> General.
