### ISSUE TITLE
v4.7.1 SNAFU systray icon

### ISSUE THREAD

**Issue by FiSHYsolutions** [h3poteto/whalebird-desktop#3824]
just updated from whalebird v4.7.0 to v4.7.1 (both snap) in xubuntu 22.04.1 LTS (xfce v4.16).
now systray icon broken:

![Bildschirmfoto_2022-11-23_00-37-45](https://user-images.githubusercontent.com/222112/203442869-622c963c-4bc8-472e-9b27-561f0ffe7e91.png)

expectation: software before refresh bad, software after update good
situation: systray icon before refresh good, systrayicon after refresh bad
question: why?

**Comment by h3poteto** [comment]
I will take this issue in #3831
