### ISSUE TITLE
Loading toots endlessly

### ISSUE THREAD

**Issue by nesfla** [h3poteto/whalebird-desktop#3827]
Hi.  I update to 4.7.1 version and now I can't read toots as they are loading endlessly and the screen is permanently skipping. I have tried to change config but didn't find how to stop or change the way the app is loading toots

**Comment by runrunrirun** [comment]
This seems to be new, previous versions did not update the scroll position if you were not at the top of the timeline. Current behavior seems to be that the scroll position is recalculated based on new incoming toots every time you touch the scroll thumb - the effect is that the timeline keeps "jumping back" every time new toots come in as you scroll. On a busy server,  the Public timeline can become almost impossible to scroll.

Need an option to not update a timeline automatically and/or don't alter the scroll position for incoming toots.
