### ISSUE TITLE
Taskbar icon missing

### ISSUE THREAD

**Issue by skribe** [h3poteto/whalebird-desktop#3831]
## Description

The whalebird icon in the taskbar is either missing or has been changed to resemble a missing icon.  It's certainly different from the "deformed rabbit" icon used in the previous version =).

## How To Reproduce
1. Upgrade to latest version from previous
2. Look down at taskbar
3. Notice the deformed rabbit icon has turned into a circle with a line through it
4. Say 'Wow!  That's different'
5. Write bug report on github

## Your Environment
 - OS: Linux
 - Whalebird Version: 4.7.1
 - Instance: all
![Whalebird-icon-missing](https://user-images.githubusercontent.com/5283207/203781016-7048acbb-b2ec-41cd-8df9-a60bc61f53cf.jpg)

**Comment by h3poteto** [comment]
How to install Whalebird? Snap? or `.deb` package?

**Comment by skribe** [comment]
Snap

**Comment by h3poteto** [comment]
Is this same as https://github.com/h3poteto/whalebird-desktop/issues/3824 ?

**Comment by skribe** [comment]
It looks the same

**Comment by h3poteto** [comment]
I think it occurs only when using snap.

**Comment by skribe** [comment]
Ok, thanks.

**Comment by h3poteto** [comment]
Probably, this one: https://github.com/h3poteto/whalebird-desktop/pull/3760

**Comment by skribe** [comment]
Ok, thanks.
