### ISSUE TITLE
Login to libranet.de (Friendica) does not work

### ISSUE THREAD

**Issue by alexbarton** [h3poteto/whalebird-desktop#3837]
## Description
Logging in to "libranet.de" (running Friendica, which should provide a Mastodon compatible API) does not work: the assistant starts, asks for the "server domain name", is OK with "libranet.de", redirects to the acknowledgement page of libranet.de (in Safari), but then does not accept the token provided there: after entering it, Whalebird just shows "Failed to authorize".

![Whalebird Libranet de login error](https://user-images.githubusercontent.com/174961/204166375-d0a06ae6-0f24-4ba9-ab23-7339f8a52d36.png)

## How To Reproduce
1. Open Whalebird with no account configured
2. Enter "libranet.de" as server
3. Enter the token provided from the server

## Your Environment
 - OS: macOS
 - Whalebird Version: 4.7.1
 - Instance: libranet.de

Should/could this work already? Related to #3327?

**Comment by h3poteto** [comment]
Friendica is not officially supported yet.

**Comment by alexbarton** [comment]
I see, thanks for the update and your work @h3poteto!

**Comment by h3poteto** [comment]
I will take this issue in #3327
