### ISSUE TITLE
Follow individual hashtags and users in separate sections/lists

### ISSUE THREAD

**Issue by KoenDG** [h3poteto/whalebird-desktop#3853]
## Describe
I'm looking for the ability to more clearly filter, and create custom lists of things to follow. Like a singular hashtag or account..

## Why
Right now it appears one can only see the timelines and basically everyone you're following. If you'd want to follow a specific tag or user it currently requires doing individual searches every time. Having individual tabs/sections/lists/... for this makes everything very useful.

Basically, I'm describing what Tweetdeck allows. While they work with columns, you can define as many columns as you like and each one is basically a search query, that returns its results, allowing you to do things like: `#fanart #videogame after:2022-11-01 before:2022-11-30`. Or follow content creators or just individual accounts in general.

Stuff like that.

This seems slightly related to https://github.com/h3poteto/whalebird-desktop/issues/3797 but I'm not sure that covers all of it.

**Comment by h3poteto** [comment]
Part of #3797

**Comment by h3poteto** [comment]
refs #4754
