### ISSUE TITLE
How do I slow or stop Whalebird's feed in Mastodon

### ISSUE THREAD

**Issue by marcsterg** [h3poteto/whalebird-desktop#3855]
How do I slow or stop Whalebird's feed in Mastodon so I can read individual posts.

There is no way to read or respond to posts because they pass by so quickly!

**Comment by RobATX** [comment]
Same. Need to not move the reading position in the feed while background refreshes are occurring. It's impossible to use my Home feed with things changing ever few seconds.

**Comment by canadaduane** [comment]
I think I'm having a similar problem--but it's the slow-loading of images that causes "jumping" to occur. I can't read the posts when some post far above the scroll line just got its image and moved every subsequent post down.

**Comment by h3poteto** [comment]
duplicated
https://github.com/h3poteto/whalebird-desktop/issues/3854
