### ISSUE TITLE
Why am I seeing little mastodon icons by each account?

### ISSUE THREAD

**Issue by masukomi** [h3poteto/whalebird-desktop#3865]
see screenshot below.

Am I right in assuming that if one of these accounts was Misskey or Pleroma, the icon would change? 

How does being reminded of  / told the server software that each account is running help me as a user? 

I feel like there's a value here that I'm not understanding. That being said, it feels like visual clutter for no purpose. 

<img width="38" alt="CleanShot 2022-12-06 at 14 08 18@2x" src="https://user-images.githubusercontent.com/2829/206000362-cbe1f9eb-aa67-4791-9345-8777d2236229.png">

**Comment by h3poteto** [comment]
These are server icons.
> if one of these accounts was Misskey or Pleroma, the icon would change?

Yes, that's right.

Some users are using the same icon for multiple servers. In this case, it is hard to recognize which server you want to use. So server icons are displayed.

**Comment by masukomi** [comment]
> Some users are using the same icon for multiple servers. In this case, it is hard to recognize which server you want to use. So server icons are displayed.

er. check my screenshot. I do that. Two of them have the same avatar icon AND the mastodon icon. All 4 of them have the same mastodon icon actually. I get what you're going for now, and it sounds like a good idea, but i don't think it actually plays out as well as hoped in practice.
