### ISSUE TITLE
Q: Is there a way to freeze or pause the timelines?

### ISSUE THREAD

**Issue by JoeCotellese** [h3poteto/whalebird-desktop#3867]
I'm reading the public timeline on my Mac. It's fairly high velocity and I can't read the content fast enough, the feed continues to push new content on the top.

Is there a way to freeze this or at least not have it auto-scroll?

**Comment by RotFarm** [comment]
Not yet. I think that feature of a slow mode, or pause for it is hopefully coming. I made a mention of it a while ago.

**Comment by ShaneCurcuru** [comment]
Mark me as another requester for supporting Slow Mode in the whalebird UI, this is the #1 usability issue I have with it currently; otherwise super-nice client!

**Comment by DerekFen** [comment]
I can't understand how anybody can use it when everything you are trying to read just keeps popping down the screen.
