### ISSUE TITLE
[1.3.3.] Doesn't find existing user accounts on remote instances.

### ISSUE THREAD

**Issue by MacLemon** [h3poteto/whalebird-desktop#388]
## Description
I've tried to follow a newly created user account on a remote instance but search doesn't find the account. Checking directly on the remote instance the account is existing and active. Bot instances do federate properly, no blockings are in place.
Other accounts on the remote instance are found without problems. I am successfully getting messages from other accounts on the remote instance.

## How To Reproduce
1. Create a new account on one instance.
2. Use Search in Whalebird to find the new account
3. There is no step three

## Your Environment
 - OS: macOS 10.12.6
 - Whalebird Version: 1.3.3
 - Instance: [chaos.social](https://chaos.social), trying to follow an account from [bsd.network](https://bsd.network)

**Comment by h3poteto** [comment]
Can you find the remote account from chaos.social using web browser?
In order to search remote account, these two instances need to be connected. If these instances are not connected, you can not find the account in web browser.

As the another reason, it may take time to be reflected.

**Comment by MacLemon** [comment]
Yes, other accounts on the remote instance are followed and get found and have been working for months. So these instances definitely are talking to each other perfectly fine.

It may be a caching issue or update-frequency issue. I'm not familiar enough with the API to know how often or when instances trigger updates or if searches are executed live.

**Comment by amyspark** [comment]
I've found issues when searching from a Mastodon instance to Pleroma/Hubzilla, especially when not using the @username@instance.tld syntax.

**Comment by foss-** [comment]
Persisting in 1.5.0 on macOS 11.6.2 when searching for e.g. `@phessler@bsd.network` no search result is displayed.
