### ISSUE TITLE
Error: ENOSPC: System limit for number of file watchers reached

### ISSUE THREAD

**Issue by noliveira95** [h3poteto/whalebird-desktop#3895]
## Description
After cloning the repo and starting the test server, an error is thrown when opening the localhost. I tried rebooting my system just in case and the problem still occurs.

`Error: ENOSPC: System limit for number of file watchers reached, watch '/home/nick/Projects/Whalebird/whalebird-desktop/node_modules/babel-polyfill/node_modules/core-js/library/es7/map.js'`

## How To Reproduce
1. Clone the repository to local system
2. Install packages with "yarn install"
3. Run "yarn run dev" and open the localhost

## Your Environment
 - OS: Ubuntu 22.04.1 (Linux)
 - Whalebird Version: 4.7.2
 - Instance: N/A

**Comment by h3poteto** [comment]
Please show me 
```
$ cat /proc/sys/fs/inotify/max_user_watches
```

**Comment by noliveira95** [comment]
> Please show me
> 
> ```
> $ cat /proc/sys/fs/inotify/max_user_watches
> ```

That returned:
```
$ cat /proc/sys/fs/inotify/max_user_watches
65536
```

**Comment by h3poteto** [comment]
Please increase it.
Refs: https://bobbyhadz.com/blog/system-limit-for-number-of-file-watchers-reached
