### ISSUE TITLE
Search for accounts don't work

### ISSUE THREAD

**Issue by tigexplorer** [h3poteto/whalebird-desktop#3913]
## Description

On several machines/ installations of WhaleBird, I've no luck with searching for accounts for a while. Not with a part of nor with the full handle.
## How To Reproduce
1. Open the search form
2. Type in or past a handle or a part of them
3. Type ENTER
4. Nothing happens

## Your Environment
 - OS: ubuntu 20.04
 - Whalebird Version: 4.6.5
 - Instance: several instances

**Comment by h3poteto** [comment]
I can't reproduce it.
![Screenshot from 2022-12-17-10-45-52](https://user-images.githubusercontent.com/4631959/208217522-cbcb4449-c911-4db3-b0ae-f161505c579d.png)

**Comment by larsga** [comment]
I had the same bug (Macos, Whalebird 4.6.2). I upgraded to 4.7.2, and now it works just fine.

**Comment by tigexplorer** [comment]
> I had the same bug (Macos, Whalebird 4.6.2). I upgraded to 4.7.2, and now it works just fine.

Thanx, this is also solving the problem here
