### ISSUE TITLE
Notification sound volume

### ISSUE THREAD

**Issue by Mrkol** [h3poteto/whalebird-desktop#3914]
## Describe
I want a volume slider for notifications.

## Why
They are bloody loud, and whalebird does not show up on windows' sound mixer (for electron reasons, I guess?)

**Comment by dowodenum** [comment]
I'll chime in that being able to change the notification sound would solve this problem (users could adjust the volume of the sound on their own w/ audacity etc) - and unique per-account notification sounds would be really nice too!

Currently, changing sound/volume can be done by editing resource files at `\Whalebird\resources\build\sounds`, but per-account is still not possible, unfortunately.

**Comment by Mrkol** [comment]
Having to go into an audio editor for changing the volume of notifications is not an acceptable user experience. The issues of fancy customization and basic usability (not popping your eardrums after every toot) should be considered separately, IMHO.
