### ISSUE TITLE
Can't enter port

### ISSUE THREAD

**Issue by FGRPM432** [h3poteto/whalebird-desktop#3919]
## Description
I want to enter the domain name to enter the instance, because the listening port of my instance is 56397, so the content I entered is:  
 mydomain.com:56397 , when I press search, Whalebird prompts me: only the domain name can be entered.

## How To Reproduce
1.login instance

## Your Environment
 - Windows
 - 4.2.3.0
 - Misskey

**Comment by h3poteto** [comment]
Please publish your server with 443 port.  Most are not made with the assumption that you will specify a port.
And I'm not going to do this.

**Comment by FGRPM432** [comment]
I can't,
Because my ISP blocked my 443 port on my network, that's why I'm giving feedback

**Comment by h3poteto** [comment]
I don't know. Please use a better ISP.
