### ISSUE TITLE
mac download leads to 404

### ISSUE THREAD

**Issue by core-code** [h3poteto/whalebird-desktop#3931]
<img width="472" alt="Screenshot 2022-12-19 at 15 12 19" src="https://user-images.githubusercontent.com/1261954/208445031-4fb91016-9d23-4da1-a7c8-76de3fbcce8a.png">
=>
<img width="465" alt="Screenshot 2022-12-19 at 15 12 21" src="https://user-images.githubusercontent.com/1261954/208445055-2a24a82c-714b-46f7-b04a-49949f9a1660.png">

**Comment by h3poteto** [comment]
fixed!

**Comment by core-code** [comment]
thanks :)
