### ISSUE TITLE
duplicated image in the toot

### ISSUE THREAD

**Issue by Asturgeek** [h3poteto/whalebird-desktop#3965]
when loading an image for toot, duplicated loading

Whalebird 4.7.0 and earlier
Linux x64 Appimage

![whale](https://user-images.githubusercontent.com/94010695/210111102-1299d69a-71f1-4f9f-8cb9-16363b5e6a29.png)

**Comment by h3poteto** [comment]
Can't reproduce it, please use the latest version.
