### ISSUE TITLE
[Website] Add WinGet package manager instructions.

### ISSUE THREAD

**Issue by homotechsual** [h3poteto/whalebird-desktop#3970]
The WinGet package manager is included in supported Windows 10 and 11 builds it would be handy to have this on the installation / download page:

```ps
winget install -e h3poteto.whalebird-desktop
```

**Comment by h3poteto** [comment]
I wrote a note about winget: https://github.com/h3poteto/whalebird-desktop#windows
I don't recommend winget and `.exe` files because of code signing. So I think we shouldn't write winget on the website.
What do you think?
