### ISSUE TITLE
Allow configuring non-account local feeds

### ISSUE THREAD

**Issue by mars0i** [h3poteto/whalebird-desktop#3971]
## Describe
Whalebird seems very nice.  It would be great if I could add local feeds from instances on which I don't have accounts.  This seems like an easy thing to add, and I think a lot of people would like it.

## Why
I want to keep my number of accounts low (one or two), but I like to browse local feeds on particular instances and then boost, comment, or follow toots and people there from my main account.

**Comment by h3poteto** [comment]
Duplicated: https://github.com/h3poteto/whalebird-desktop/issues/1439
And please see this comment: https://github.com/h3poteto/whalebird-desktop/issues/1439#issuecomment-1383179235

**Comment by mars0i** [comment]
Thanks!  Sorry I didn't find the earlier issue--the searches I tried didn't find it.  I

Fedistar looks good.  I'll see if I can install the current dmg version on MacOS.  I won't be able to co tribute code--no time, and I'm not familiar with Rust or the other tools you're uaing.
