### ISSUE TITLE
[4.7.4] Unreadable error message random pop-up.

### ISSUE THREAD

**Issue by chenshaoju** [h3poteto/whalebird-desktop#3981]
Sorry for my english.
## Description
When the computer wakes up from few hours sleep, Have a certain chance this message pop-up:
![Screenshot_20230102_173559](https://user-images.githubusercontent.com/515763/210214988-ad3dd7ce-4b6f-4336-86fa-50f151b2ff05.png)

## How To Reproduce
1. Open Whalebird
2. Put the computer in sleep mode few hours.
3. Wake up the computer.

## Your Environment
 - OS: Manjaro Linux (Linux kernel 6.1.1-1)
 - Whalebird Version: 4.7.4, Installed from snap.
 - Instance: acg.mn

Logs:
[main.log](https://github.com/h3poteto/whalebird-desktop/files/10330849/main.log)

If need any information, please feel free to ask, thank you.

**Comment by h3poteto** [comment]
In Manjaro Linux, sleep means "suspend"? or "hybrid-sleep"?  There are some options in sleep: https://wiki.archlinux.org/title/Power_management
And is the internet disconnected during sleep?

**Comment by chenshaoju** [comment]
Is "Sleep", not "Hibernate" or "Hybrid Sleep"

And yes, the Internet is disconnected.
