### ISSUE TITLE
Whalebird desktop windows fails to connect to snabeln.no

### ISSUE THREAD

**Issue by Kilill** [h3poteto/whalebird-desktop#3994]
## Description
Trying to "search" for domain _snabeln.no_ results in: 
`Failed to connect snabeln.no, make sure the server URL`

## How To Reproduce
1. install latest windows version of whalebird-desktop
2. try to open _snabeln.no_

## Your Environment
 - OS: Windows 10
 - Whalebird: 4.7.4.0
 - Instance: snablen.no

**Comment by h3poteto** [comment]
Is this domain correct? I can't connect it from the browser.
```
$ curl https://snabeln.no
curl: (6) Could not resolve host: snabeln.no
```

**Comment by Kilill** [comment]
ah, ouch, sorry. I'm and idiot and blind as well it seems, not sure how many times i managed to type that incorrectly :-P
the correct url is ofc snabelen.no and ofc it works...
