### ISSUE TITLE
Option to turn off link previews

### ISSUE THREAD

**Issue by Wolf301** [h3poteto/whalebird-desktop#4004]
## Describe
Link previews should be optional, controlled by a user setting. Currently any toot that includes a hyperlink automatically includes a preview of what is at that link. 

## Why
1) On the tiny screen of my laptop they occupy unreasonable amounts of real estate. 
2) It runs up data charges on my 4G stick when I am away from home/WiFi. 
3) It has the potential to download something I really do not want sitting on my machine, in cache or in logs which would not be there if the link preview were not generated.  I can block the user responsible, but it's too late if the content has been fetched and a preview generated.

**Comment by h3poteto** [comment]
I'm not interested, but PR is always welcome.

**Comment by Wolf301** [comment]
Apologies, I got dragged into hospital. Not a problem, if you're not interested, it's your show!
