### ISSUE TITLE
Option to disable taskbar icon

### ISSUE THREAD

**Issue by UnderEu** [h3poteto/whalebird-desktop#4019]
## Describe
Implement an option where users can enable/disable taskbar icon at their will

## Why
1. Freedom for users to customize their experience
2. In some circunstances, the taskbar can become flooded and users can select what icons appear and what doesn't.

I use Ubuntu MATE 22.04 but that should extend to every other OS

**Comment by h3poteto** [comment]
I'm not interested, but PR is always welcome.

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
