### ISSUE TITLE
Enable validation on account search

### ISSUE THREAD

**Issue by akito19** [h3poteto/whalebird-desktop#402]
When login Mastodon with Whalebird, we enter instance domain name in the following form. 

<img width="516" alt="screen shot 2018-06-17 at 23 28 30" src="https://user-images.githubusercontent.com/8242734/41508862-4279fa66-7286-11e8-956c-4c1feea103f9.png">

However, it can search accounts even if we fill in the form with a non-instance name. For example, when I fill in the form with `akito19@mstdn.jp` or `@akito19@mstdn.jp`, succeed in searching my account and go next steps. In spite of continuing log in process, I will fail to authorize. This is because Whalebird realizes that my `domain` is `akito19@mstdn.jp` not `mstdn.jp`, fails to call Mastodon API.

Thus, I'd like to equip search form with validation or extract only instance domain name in `LoginForm`.
WDYT?

**Comment by h3poteto** [comment]
I thin it is nice.
Whalebird check the instance at:
https://github.com/h3poteto/whalebird-desktop/blob/master/src/renderer/store/Login.js#L78

I was surprised that you can search the instance using username.
