### ISSUE TITLE
Crash with Uncaught Exception: Error: SQLITE_CANTOPEN: unable to open database file

### ISSUE THREAD

**Issue by cajhne** [h3poteto/whalebird-desktop#4032]
## Description
Tried both 5.0 .deb and appimage, both produce this same error and refuse to run when launched. (Ubuntu Linux 22.04)

## How To Reproduce
1. Launch 5.0 alpha 3 from either installed .deb or appimage
2. Crashes immediately without showing any UI.

Full Error: 

A JavaScript error occurred in the main process
Uncaught Exception:
Error: SQLITE_CANTOPEN: unable to open database file

## Your Environment
 - OS: Ubuntu 22.04
 - Whalebird Version: 5.0.0 Alpha 3

**Comment by h3poteto** [comment]
Thank you for trying the alpha version. Could you please show me your `~/.config/Whalebird` directory?
```
$ ls -lha ~/.config/Whalebird
```

**Comment by cajhne** [comment]
Sure:

total 16K
drwx------  4 crogers crogers 4.0K Jan 20 00:47 .
drwx------ 82 crogers crogers 4.0K Jan 21 04:35 ..
drwx------  2 crogers crogers 4.0K Jan 19 22:03 Crashpad
drwx------  2 crogers crogers 4.0K Jan 19 22:03 logs

**Comment by h3poteto** [comment]
Ah, I got it.
I can reproduce it:
```
$ whalebird
A JavaScript error occurred in the main process
Uncaught Exception:
Error: SQLITE_CANTOPEN: unable to open database file
```
