### ISSUE TITLE
No font size setting available

### ISSUE THREAD

**Issue by chrisgrieser** [h3poteto/whalebird-desktop#4035]
## Description
From what I can tell by searching the issues (e.g. #237), there should be a font size setting somewhere. However, in the whalebird settings, there is no such font size setting to be found anywhere for me.

## Your Environment
 - OS: macOS 13.0.1 (M1)
 - Whalebird Version: 4.7.4
 - Instance: pkm.social

**Comment by h3poteto** [comment]
![Screenshot from 2023-01-22-01-51-34](https://user-images.githubusercontent.com/4631959/213877746-c9ce9b09-b1db-4bc7-b784-03bf86f6d8cb.png)
Preferences -> Appearance?

**Comment by chrisgrieser** [comment]
those do not appear for me: 
<img width="1206" alt="Pasted image 2023-01-21 19 37 08" src="https://user-images.githubusercontent.com/73286100/213882092-d4a89a9a-6d37-4b00-9f98-9e32d64d6c11.png">

**Comment by chrisgrieser** [comment]
ah, now I see. the cog shows settings, while with the menu, you open preferences, where the font preferences are to be found.

To be frank, it is terribly confusing that there is a preference menu and a settings menu, and that the only visible cog symbol does not lead to all of them…
