### ISSUE TITLE
No scroll to Feeds list

### ISSUE THREAD

**Issue by RotFarm** [h3poteto/whalebird-desktop#4036]
## Description

The second list from the left where your Feeds are listed doesn't have a scroll bar to accommodate pinning hashtags and creating LIsts. 

![List no scroll](https://user-images.githubusercontent.com/10239722/213883276-2714ebb3-0d46-4632-872e-a769224b634e.jpg)

## How To Reproduce
1. Go to search
2. search hashtags
3.pin hashtags until your "List" feed option stops being visible

## Your Environment
 - OS: Windows 10
 - Whalebird Version: 4.7.4]
 - Instance: rotfarm@eldritch.cafe

**Comment by h3poteto** [comment]
duplicated: https://github.com/h3poteto/whalebird-desktop/issues/3586
