### ISSUE TITLE
New Toot Notification Blocks Thread Buttons

### ISSUE THREAD

**Issue by lehitoskin** [h3poteto/whalebird-desktop#4051]
## Description
I expanded a post to read the thread and tooted a response and now some of the buttons are blocked from being clicked by new toot notification thing that appears in the top right corner of the window.

<img width="193" alt="Screenshot 2023-01-26 at 12 18 47 PM" src="https://user-images.githubusercontent.com/2506703/214942791-1f933145-fb08-4eae-ab23-51097cbe55dd.png">

## How To Reproduce
1. Expand toot
2. Scroll the main window down a little
3. Respond to toot or wait for a new toot to come in
4. Notification thing pops up, blocking thread buttons

## Your Environment
 - OS: macOS 13.1 Ventura
 - Whalebird Version: 4.7.4
 - Instance: mstdn.social

**Comment by seachdamh** [comment]
On Linux (Debian 11 x64) and Windows 11 the problem also occurs.

**Comment by h3poteto** [comment]
It's removed in 5.0.0.
