### ISSUE TITLE
Expanded card media view

### ISSUE THREAD

**Issue by trashhalo** [h3poteto/whalebird-desktop#414]
## Describe

Expand media and present in a organic grid. Something like https://www.pinterest.com/

## Why
Why do you want this feature?

I follow artists on mastodon. Would love to consume their content without having to click into every post. Ive never found a mastodon client that lets me view my timeline like this.

**Comment by h3poteto** [comment]
I saw pinterest, but I can't imagine the organic grid.
Do you have any concrete picture etc?

**Comment by trashhalo** [comment]
I was thinking about something like this. https://masonry.desandro.com/ You take the media from people toots and you use this libraries to draw it into a grid. Here is a site using something like this. http://www.imagoid.com/r/DessertPorn

**Comment by h3poteto** [comment]
How do you think that toot without attachment should be displayed?

Are you looking for a timeline which contains only images?

**Comment by trashhalo** [comment]
Id be okay with hiding those toots in that view. Yes only images.

**Comment by h3poteto** [comment]
OK, I see, but I don't intend to implement such timeline. Since many people are using this application, I am not implementing features that only benefit some people.

**Comment by trashhalo** [comment]
No biggie :) Ill just fork your repo and build it myself
