### ISSUE TITLE
[5.0.0-rc] Keyboard shortcuts interfering with compose message box

### ISSUE THREAD

**Issue by AshTR** [h3poteto/whalebird-desktop#4161]
## Description
Tried the most recent RCs with the compose message box below the timeline and keyboard shortcuts seem to have priority over typing in the compose message box.
 
## How To Reproduce
1. Open Whalebird
2. Start writing new post.
3. Push Shift+J or Shift+K and posts are selected in the timeline instead of typing in the appropriate capitalized character.
 
## Your Environment
* OS: Windows 10 22H2 19045.2673
* Whalebird Version: 5.0.0-rc3
* Instance: Meow.Social

**Comment by oliware** [comment]
I can confirm same behaviour on kubuntu 22.04

**Comment by AshTR** [comment]
Just saw this made it into the full release. What was the point of a release candidate if there wasn't even testing of basic functionality or reading this issue tracker?

**Comment by h3poteto** [comment]
This issue report was too late. It wasn't important enough to roll back after all the store reviews went through.
