### ISSUE TITLE
v5.0.0 macOS x64 JavaScript error on launch

### ISSUE THREAD

**Issue by lehitoskin** [h3poteto/whalebird-desktop#4173]
## Description
I downloaded and installed Whalebird-5.0.0-darwin-x64.dmg but when I run it, I get this JavaScript error and a window never opens.
<img width="632" alt="Screenshot 2023-03-06 at 9 07 11 AM" src="https://user-images.githubusercontent.com/2506703/223181400-cc8bfd32-4269-4ea2-9932-3ed5e4728399.png">

## How To Reproduce
1. Download Whalebird-5.0.0-darwin-x64.dmg
2. Install Whalebird.app
3. Open application
4. Error window appears

## Your Environment
 - OS: macOS Ventura 13.2
 - Whalebird Version: 5.0.0

**Comment by h3poteto** [comment]
How about AppStore version? Do you have the same error?

**Comment by lehitoskin** [comment]
It comes up with this error window a few times and then the original error appears.
<img width="372" alt="Screenshot 2023-03-06 at 7 52 58 PM" src="https://user-images.githubusercontent.com/2506703/223316597-c733ca7d-6bb3-4fd8-a050-d08c2b067c05.png">

**Comment by h3poteto** [comment]
Hmm, both of them are working on my Mac. I'm not sure what the difference is.

**Comment by runrunrirun** [comment]
I have the same error, Monterey 12.6.3 Intel. I downloaded the x64 only binary.

**Comment by lehitoskin** [comment]
Cloning the repo and running from source with `yarn run dev` works. HMMMM

**Comment by h3poteto** [comment]
Probably, the cause is code signing (not related to application codes).
@runrunrirun  Did you try MacAppStore version?

**Comment by runrunrirun** [comment]
Same behavior as @lehitoskin with MAS version as well.

**Comment by toabi** [comment]
Found the same here, I think the key cause is this part: `not valid for use in process: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?))` - maybe you accidentally signed it with some wrong profile? And it works for you because that profile is trusted on your mac.

**Comment by lehitoskin** [comment]
@h3poteto Just point me to the DMG and I'll test it.

**Comment by h3poteto** [comment]
@lehitoskin @runrunrirun Please try https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.1-beta.7

**Comment by runrunrirun** [comment]
> @lehitoskin @runrunrirun Please try https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.1-beta.7

Looks good here on Monterey Intel 👍

**Comment by lehitoskin** [comment]
@h3poteto That works! Woohoo! 🥳

**Comment by h3poteto** [comment]
Thanks! I will sort out the fix and merge it. After that, I will release 5.0.1, please wait a little more.
