### ISSUE TITLE
j and k shortcuts navigate posts even when composing a post

### ISSUE THREAD

**Issue by kkellerlbl** [h3poteto/whalebird-desktop#4182]
## Description

When trying to compose a post (either new or a reply), the j and k keys select the next or previous post instead of entering the character in the compose box.  Other keyboard shortcuts seem to work as expected in the compose box.  Copy and pasting these characters works fine; only keyboard entry produces the navigation issue.

## How To Reproduce
1. Enter the compose box
2. Try to type "j" or "k"
3. Move back and forth between posts instead of seeing the correct characters in the compose box

## Your Environment
 - OS: Ubuntu 20.04
 - Whalebird Version: [e.g. 5.0.0]
 - Instance: [curling.social]

**Comment by h3poteto** [comment]
duplicated: https://github.com/h3poteto/whalebird-desktop/issues/4161
