### ISSUE TITLE
Shortcut J activates in composition field

### ISSUE THREAD

**Issue by PN3UMA** [h3poteto/whalebird-desktop#4193]
## Description
I cannot type the letter 'j' in the composition field because it activates the assigned shortcut 'Select the next post.'

## How To Reproduce
1. Click into 'What's on your mind?' field.
2. Type the letter 'j.'
3. Instead of typing 'j,' it activates the assigned shortcut "Select the next post."

## Your Environment
 - OS: [e.g. Debian 11]
 - Whalebird Version: [5.0.0 (flatpak says 4.7.4?)]
 - Instance: [e.g. fosstodon.org]

**Comment by h3poteto** [comment]
Duplicated: https://github.com/h3poteto/whalebird-desktop/issues/4161

And it is already fixed, please use 5.0.1.

**Comment by PN3UMA** [comment]
> 

Thank you for the prompt reply. How do I get 5.0.1? Flathub is only pulling down 4.7.4, On whalebird.social, I only see 5.0.0 and the links to the appimage & deb are throwing 404s.

**Comment by PN3UMA** [comment]
> > 
> 
> Thank you for the prompt reply. How do I get 5.0.1? Flathub is only pulling down 4.7.4, On whalebird.social, I only see 5.0.0 and the links to the appimage & deb are throwing 404s.

I found 5.0.1 here under Assets and downloaded the appimage and issue is resolved. Thanks! 

How do we get whalebird.social and flathub to show updated 5.0.1 instead of 5.0.0 and 4.7.4 respectively?

**Comment by h3poteto** [comment]
Sorry, I forgot to update whalebird.social.
I already updated the download page. Flatpak version has another issue, so it is not released yet.
https://github.com/flathub/social.whalebird.WhalebirdDesktop/pull/12
