### ISSUE TITLE
Whalebird 5.0.0 fails to start

### ISSUE THREAD

**Issue by ztomer** [h3poteto/whalebird-desktop#4195]
## Description

Whalebird fails to start after updating to version 5.
* Removing and installing from the latest DMG (v5.0.1), fails as well with the same error.

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1908552/224331879-11264869-da71-4dff-b61a-580056521ead.png">

## How To Reproduce
1. Install/ update Whalebird with a version >= 5.0.0
2. Launch Whalebird
3. Failure to launch

## Your Environment
 - OS: MacOs Ventura v13.2.1, M1 Mac
 - Whalebird Version: 5.0.0, 5.0.1, installed from Homebrew for 5.0.0, and DMG for 5.0.1
 - Instance: Didn't get to this step

**Comment by h3poteto** [comment]
Probably this issue happens only arm64 OS.
@gumbolastima Are you also using an amr64 OS?

**Comment by h3poteto** [comment]
@ztomer @gumbolastima 
Could you please try this image? https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.2-beta.1
It is a test release. I would be happy if you could try both arm64 and universal binary.

**Comment by ztomer** [comment]
Tried 5.0.2-beta.1, arm64, it fails with the following error:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1908552/224480491-bff0ef35-788d-44cc-ba5b-e8050b511e47.png">

**Comment by h3poteto** [comment]
@ztomer How about https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.2-beta.2

**Comment by ztomer** [comment]
Negative
<img width="632" alt="image" src="https://user-images.githubusercontent.com/1908552/224499630-246bc3e7-f3f1-4279-b1dc-c0f0a79128c0.png">

**Comment by Wildvirus** [comment]
Same here. Mac Mini M1 and Macbook M1 Pro. Both Beta2-versions crashed with the same error

**Comment by h3poteto** [comment]
@ztomer @gumbolastima @Wildvirus Could you please try beta.3?
https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.2-beta.3

**Comment by h3poteto** [comment]
Ah, OK. I will create an official release v5.0.2.

**Comment by Wildvirus** [comment]
I can also commit Beta3 was ok, both versions for Mac.

**Comment by Wildvirus** [comment]
Great Job, downloaded new release 5.02 some minutes ago and it works perfect!. Thanks.

**Comment by h3poteto** [comment]
5.0.2 is released.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.2
