### ISSUE TITLE
MacOS 5.0.2 on x86_64 breaks with error about Sqlite3 on ARM

### ISSUE THREAD

**Issue by sdenaro** [h3poteto/whalebird-desktop#4220]
## Description
Whalebird installed via brew cask fails to start on x86 MacBook Pro. Looks like Mac ARM module is being used and x86 version can not be found. 

![image](https://user-images.githubusercontent.com/270809/226141447-ab49c9a5-032b-4eab-935f-31d3e9c16135.png)

## How To Reproduce
1. Install Whalebird via `brew install --cask whalebird` on x86 Mac.
2. Launch 

## Your Environment
 - OS:  MacOS 13.2.1 (22D68) on 2.3 GHz 8-Core Intel Core i9
 - Whalebird Version: 5.0.2
 - Instance: https://indieweb.social/

**Comment by h3poteto** [comment]
How about AppStore version?

**Comment by sdenaro** [comment]
AppStore version works. It's only the install from brew that fails.  I normally install things from homebrew if possible and only the the AppStore for paid apps.

**Comment by h3poteto** [comment]
Hmm, can you please try to download dmg from https://github.com/h3poteto/whalebird-desktop/releases/tag/v5.0.2 ?
Please try x64 and universal dmg.

**Comment by sdenaro** [comment]
Looks like the dmg file has the same issue, which makes sense as this is what the brew command downloads and installs. 

![image](https://user-images.githubusercontent.com/270809/226222481-e10eab95-d7e7-433b-9691-af35815f5d66.png)

**Comment by h3poteto** [comment]
Please try x64 dmg.

**Comment by brevilo** [comment]
This seems to be a path issue. `app-x64.asar` is just a file, while `app-x64.asar.unpacked` is the unpacked directory. So the latter should be used instead, I think.

**Comment by h3poteto** [comment]
@brevilo No, the path is correct. In x64, `app-x64.asar.unpacked/node_modules/better-sqlite3` should be used. In arm64, `app-arm64.asar.unpacked/node_modules/better-sqlite3` should be used. 
The problem is `app-x64.asar.unpacked/node_modules/better-sqlite3` is not built for x64, it seems like arm64.

**Comment by brevilo** [comment]
I agree, but the screenshot (and on my live system) none of those are used, but apparently just the `pp-arm64.asar` file.

**Comment by h3poteto** [comment]
> but in the screenshot above (and on my live system) none of those are used, but apparently just the app-<PLATTFORM>.asar file.

??? What do you mean?

`app-x64.asar/node_modules/better-sqlite3/lib/database.js` calls `app-x64.asar/node_modules/bindings/bindings.js`, and it calls `app-x64.asar.unpacked/node_modules/better-sqlite3/build/Release/better_sqlite3.node`. It is a normal situation with native dependency.

**Comment by brevilo** [comment]
As I said:
> Unless I misinterpret the last path stated there. If so, ignore me.

The stated paths were just misleading. There's no path issue then. Ignore that part of my reply.

**Comment by h3poteto** [comment]
OK. it's working.
