### ISSUE TITLE
Max caracters limit

### ISSUE THREAD

**Issue by marseye** [h3poteto/whalebird-desktop#423]
Hi,
It would be nice to have the toot max caracters range to conform to the instance's allowed one.

For example : my instance "mastodon.host" allows up to 1000 caracters. 
I tried a toot up to -499 caracters, since Whalebirds seems to check the 500 caracters limit itself (though it can count from 500 to  0, then down to -ZZZ). But it won't even try  to submit the toot, just informing which caracter range the toot must stay within. 

Thanks

**Comment by h3poteto** [comment]
Duplicated.
https://github.com/h3poteto/whalebird-desktop/issues/360
