### ISSUE TITLE
Re-enable universal dmg build

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#4243]
## Describe
I stopped building universal dmg for an issue. Refer to https://github.com/h3poteto/whalebird-desktop/issues/4220

## Why
Of course, it is better to prepare universal dmg. So, if you can resolve that issue, please recover the universal dmg build.

**Comment by core-code** [comment]
plus one for bringing back a real universal download

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
