### ISSUE TITLE
Favorites, bookmark, boost buttons do not work in 5.0.2

### ISSUE THREAD

**Issue by geojoek** [h3poteto/whalebird-desktop#4247]
## Description

In 5.0.2, on Mac, clicking on the favorite, bookmark, and boost icons appear to do nothing / there is no longer any visual or audio cue that any of these actions succeeded.  When visiting the instance via the web browser it appears that Favorite, Bookmark, and boost for aa given toot did work, but the Whalebird app does not indicate it while taking those actions, or if the toot has been favorited, bookmarked, or boosted.

## How To Reproduce
1. Install 5.0.2 using either Homebrew or Mac App Store
2. Open program
3. Click on any of the aforementioned icons.

## Your Environment
 - OS: MacOS
 - Whalebird Version: 5.0.2
 - Instance: mastodon.hams.social

**Comment by Dret42** [comment]
I confirm the problem. Same for me after updating to 5.02
