### ISSUE TITLE
Display issues on Mac - giant spaces being left above toots

### ISSUE THREAD

**Issue by Coldkennels** [h3poteto/whalebird-desktop#4288]
## Description
When scrolling down through the feed, certain toots will "jump" - they first appear at the bottom of the viewport correctly, but when scrolling to see the entire post, they disappear downwards, creating a massive (and seemingly variable) amount of space above the toots' content, as shown below:

[image](https://user-images.githubusercontent.com/130574576/231478772-f0160a29-afa5-40a8-bb79-53ad06549bb1.png)

## How To Reproduce
Simply scroll through the feed. There's seemingly no pattern or way to predict which toots will display this way.

## Your Environment
 - OS: Mac OS 10.14.6
 - Whalebird Version: 5.0.2
 - Instance: mastodon.social (instances of posts affected vary)

**Comment by compuguy** [comment]
I'm seeing the same exact issue with Whalebird on Windows as well. I don't think its a platform specific issue....

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
