### ISSUE TITLE
Option to pause streaming/automatic scrolling of toots

### ISSUE THREAD

**Issue by gitet** [h3poteto/whalebird-desktop#4322]
## Describe
An option (right click context menu, dedicated button, one or the other or both) to pause the automatic scrolling / stream of toots would be very useful - especially in the `Federated timeline` and `Local timeline` views.

## Why
It is impossible to "go back" in the federated timeline because Whalebird will not stop scrolling. I find this very annoying and it is one of the reasons why I still haven't switched over to using Whalebird on a daily basis (The `fedistar` mastodon client has this feature)

**Comment by h3poteto** [comment]
duplicated https://github.com/h3poteto/whalebird-desktop/issues/3854
