### ISSUE TITLE
Boost icon still appears at the bottom of toots even if it's private

### ISSUE THREAD

**Issue by hellocam** [h3poteto/whalebird-desktop#433]
Hi! Anyway, you can take a look at the screenshot below.  The toot is private, but instead of a lock icon, the boost icon is still in its place. I took this one from the Home timeline, but it also happens when I select View Toot Detail.

<img width="168" alt="screen shot 2018-07-11 at 12 20 08 am" src="https://user-images.githubusercontent.com/6691280/42550575-8e346d84-84a0-11e8-83b3-9f41c9ca7c63.png">

**Comment by h3poteto** [comment]
OK, I see. I will change it.
