### ISSUE TITLE
Local Timeline only loads most recent ~15 posts after upgrading from 4.7.x to 5.0.3.0

### ISSUE THREAD

**Issue by bhcompy** [h3poteto/whalebird-desktop#4345]
## Description

On 4.7.x, I could scroll back infinitely using Local Timeline.  After upgrading to 5.0.3.0, it no longer loads any more posts when scrolling down through Local Timeline.  I cannot find any settings that appear to control this behavior, so I do not think it is a new option.  Home seems to function as I would expect for scrolling backwards.    

## How To Reproduce
1. Open application (logged into hachyderm.io)
2. Go to Local Timeline
3. Scroll down.  After about 15 posts or so, no more new ones load.  This is different behavior than 4.7.x.

## Your Environment
 - OS: Windows
 - Whalebird Version: 5.0.3.0
 - Instance: hachyderm.io

**Comment by h3poteto** [comment]
Thank you for reporting. I got it.
