### ISSUE TITLE
UI issue?

### ISSUE THREAD

**Issue by puffinux** [h3poteto/whalebird-desktop#444]
Hi,

There are two little white marks above the "Home" button when the menu is open fully (so text shows). This is not a problem but looks like it needs sorting out.

Thanks.

**Comment by h3poteto** [comment]
Have you any picture? I can't confirm it on my Whalebird.

**Comment by puffinux** [comment]
![whalebird ui issue](https://user-images.githubusercontent.com/41450706/43020807-3874b726-8c59-11e8-8f0a-068cde555c04.PNG)

**Machine:**
- Fujitsu Lifebook S571
- Windows 10

**According to [Whalebird -> About Whalebird] info:**
- Whalebird 1.5.1
- Electron 1.8.6
- Chrome 59.0.3071.115
- Node 8.2.1
- V8 5.9.211.38

Settings in [Whalebird -> Preferences] do not affect the issue.

**Comment by h3poteto** [comment]
OK, I see. I think that it is appear when the window is too small. Normally, there is an account name displayed there, like this:
<img width="194" alt="2018-07-21 12 44 22" src="https://user-images.githubusercontent.com/4631959/43031792-efe3e28a-8ce3-11e8-8cd3-a37881505382.png">

It seems that it is overlooked by the problem of space. 
I will try to fix. Thank you for your reporting.
