### ISSUE TITLE
Cant connect to selfhosted akkoma instance

### ISSUE THREAD

**Issue by skwerlman** [h3poteto/whalebird-desktop#4488]
## Description

When connecting to my akkoma instance, i get this message:

> Failed to connect to fedi.tetrarch.co, make sure the server URL is valid or correct.

I can connect with my browser, and get data from the api with curl.

## How To Reproduce
1. Open whalebird
2. Enter fedi.tetrarch.co as the domain name (i have no accounts set up at all atm)
3. Click search

## Your Environment
 - OS: Arch Linux
 - Whalebird Version:
   - 5.0.5 (using whalebird-bin from the AUR)
   - 5.0.7 (using whalebird from the AUR)
   - cda8225b (using whalebird-desktop-git from AUR)
 - Instance: fedi.tetrarch.co

**Comment by h3poteto** [comment]
Because Akkoma is not supported. Whalebird support only Mastodon, Pleroma, and Misskey.

**Comment by skwerlman** [comment]
Ah, I understand. I figured itd fall under pleroma support since its forked from that, but i guess they have diverged enough by now to cause problems. Roughly what work would need to be done to add akkoma support?

**Comment by h3poteto** [comment]
Does Akkoma provide the same API interface as Pleroma? If so, it is easy, just change it to treat it as Pleroma.

**Comment by r14c** [comment]
akkoma is compatible with pleroma, they have some small differences but none of the mastodon or pleroma apps that i've used have shown any issues.

**Comment by h3poteto** [comment]
Please try the latest Whalebird
