### ISSUE TITLE
Pls make the timeline not move messages down all the time when scrolled

### ISSUE THREAD

**Issue by mitvitaminen** [h3poteto/whalebird-desktop#4498]
## Describe
I like when I scrolled down the timeline that the messages in view not start jumping downward out of screen even, I mean come on I am reading em it is annoying if I have to manually keep the same message in view. This happens in federated timeline.

## Why
Because the way it is is just annoying, good work otherwise though much appreciated

kind regards Chris

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
