### ISSUE TITLE
The visibility of original message is not reflected when replying

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#4517]
## How To Reproduce
1. Open DM
2. Reply to a message
3. Visibility is public

## Your Environment
 - OS: Manjaro
 - Whalebird Version: 5.0.5
 - Instance: all

**Comment by tigexplorer** [comment]
Same here...

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
