### ISSUE TITLE
Is There A Way To Turn Off the "Send / Toot" Box?

### ISSUE THREAD

**Issue by freecicero** [h3poteto/whalebird-desktop#4522]
## Describe
It seemed to me in versions of Whalebird prior to 5 that there was no "toot" box at the bottom of the screen.  I liked that very much because it gave me the most area to view toots, which is all i do.  I never send toots, just read them.

## Why

Is there a way you could make display of that box optional so that the most screen real estate can be devoted to toots?  I use your slack-like interface, which is great, as a reading panel, and I don't want to be forced to see a "send" box that I never use.  That's why I much prefer the older screen layout.

Thank you!

**Comment by h3poteto** [comment]
There is no way, and I'm not going to make it. Even in Slack, the post-panel is always displayed.
