### ISSUE TITLE
Keep content static when a feed has been scrolled

### ISSUE THREAD

**Issue by WovenTales** [h3poteto/whalebird-desktop#4552]
## Describe
When the user scrolls down on a feed, wherever they've stopped should remain consistent even as new posts are made at the front of the feed -- their presence should be indicated with a minimal banner or icon until the user scrolls back to the top of the feed.

## Why
There's a few instances I'm on which federate a lot of content, and their federated timelines are essentially unusable at times because even as I'm scrolling down to see what was posted a few minutes ago, the new content being posted *now* continues to bump the content I've already read back into my viewport.  If I've scrolled, I expect the feed to remain where I leave it.  *Telling* me there's something new to read is perfectly fine, but it shouldn't affect the position of what I'm currently reading.

**Comment by marvz72** [comment]
i second this issue.  I like whalebird but is unusable when trying to view federated content.

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
