### ISSUE TITLE
Allow toggling quit-on-close in place of tray-on-close

### ISSUE THREAD

**Issue by WovenTales** [h3poteto/whalebird-desktop#4553]
## Describe
When an option has been toggled in the preferences, closing the window quits Whalebird entirely, including the daemon left in the system tray.  (I'm using the Linux .deb, if that matters.)

## Why
Whalebird uses a lot of resources, and one of the devices I check it on is a low-powered laptop.  I get the benefits of minimize-to-tray on a lot of systems, but if I forget to actually *quit* rather than simply *close*, Whalebird winds up eating my precious few resources and nearly doubling my CPU temp.  I never want that behaviour on that system, but I recognize that it's helpful for others to be notified even when they aren't actively checking it; the best behaviour, then, would be to allow people to set for themselves whether they want closing to quit or to minimize.

**Comment by h3poteto** [comment]
Please check 6.0.0
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
