### ISSUE TITLE
Remove account

### ISSUE THREAD

**Issue by monochromec** [h3poteto/whalebird-desktop#4644]
## Describe
Add a context menu item (in addition to the image functionality) to an account picture to the remove account.

## Why
The procedure is as explained in https://github.com/h3poteto/whalebird-desktop/issues/3351 is cumbersome and counter-intuitive. Why do I have to resort to an issue search to find this workflow?!?

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
