### ISSUE TITLE
preferences dialog not responding (completely)

### ISSUE THREAD

**Issue by omendezmorales** [h3poteto/whalebird-desktop#4654]
## Description
Hi,
I've changed some preferences in the corresponding dialog, however I notice the UI takes considerable time to react (more than a couple of seconds), and eventually apply my changes. 
I would say in general the UI is reacting slow.

## How To Reproduce
1. OPen the preferences dialog
2. Do some appearance changes. I changed for instance theme and font
3. Close the preferences dialog and wait until the changes are applied

## Your Environment
 - OS:  Ubuntu 23.04 x86_64 
Kernel: 6.2.0-36-generic 
Resolution: 1920x1080, 1080x1920 
DE: Xfce 
WM: Xfwm4 
WM Theme: Greybird 
CPU: Intel Celeron J4125 (4) @ 2.700GHz 
GPU: Intel GeminiLake [UHD Graphics 600] 
Memory: 6079MiB / 7752MiB 
 - Whalebird Version: [e.g. 1.0.0]
 - Instance: fosstodon.org

**Comment by h3poteto** [comment]
Please check 6.0.0
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
