### ISSUE TITLE
Using powershell to get binary version shows a typo

### ISSUE THREAD

**Issue by zouhair** [h3poteto/whalebird-desktop#4658]
Windows 10

$ powershell -Command '[System.Diagnostics.FileVersionInfo]::GetVersionInfo("C:\Program Files\Whalebird\Whalebird.exe").FileVersion.ToString()'
6.0.0-alhpa.2

Should be 6.0.0-alpha.2

**Comment by h3poteto** [comment]
Ah, that's right.

**Comment by h3poteto** [comment]
Please wait 6.0.0-alpha.3

**Comment by zouhair** [comment]
Sure, thanks for all the work

**Comment by h3poteto** [comment]
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0-alpha.3
