### ISSUE TITLE
Missing systray icon

### ISSUE THREAD

**Issue by FiSHYsolutions** [h3poteto/whalebird-desktop#4659]
we don't have a systray icon anymore after upgrading the snap from v5.0.7 to v5.1.0 in xubuntu 22.04.3 lts

i reverted the snap from v5.1.0 back to v5.0.7 an got the systray-icon back. a buggy one (as described in https://github.com/h3poteto/whalebird-desktop/issues/4225#issuecomment-1488963890) but at least it's an icon.

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
