### ISSUE TITLE
Can't store/pin hashtags 

### ISSUE THREAD

**Issue by phochste** [h3poteto/whalebird-desktop#4754]
In the menu 'Hashtags' I can only search for a hashtag but can't save/pin a tag. Each time I need to do a new search. I'm using Whalebird on 5.1.1 on OSX Sonoma 14.2.1.

I've tried to de-install Whalebird and remove all of `~Library/Application Support/Whalebird` but still I can only search and not save hashtags queries.

**Comment by nileshtrivedi** [comment]
I think this is somewhat similar to #4503 ??

**Comment by nileshtrivedi** [comment]
I would actually love to have all followed tags in the sidebar. This seems much more like Slack in spirit: 
<img width="603" alt="image" src="https://github.com/user-attachments/assets/898ef4a3-e7f3-4da6-8ea2-c86af6a4a3e7">

@h3poteto What do you think?

**Comment by h3poteto** [comment]
Hmm, I think it's okay to have.

**Comment by nileshtrivedi** [comment]
I might take a stab at implementing this.
Hashtag listing and timeline is already implemented in the Search page. But need to be able to fetch the hashtags the logged-in account is following.

**Comment by nileshtrivedi** [comment]
@h3poteto Please see the PR #5028. It would be fantastic to have a Slack-like client for Mastodon.
