### ISSUE TITLE
Save Image Crash

### ISSUE THREAD

**Issue by TorinEmard** [h3poteto/whalebird-desktop#478]
## Description
Wondering if anyone else is getting a crash while trying to "save image" in Whalebird.
<img width="212" alt="screen shot 2018-08-08 at 3 46 45 pm" src="https://user-images.githubusercontent.com/1911874/43868466-9c72b2aa-9b22-11e8-8b81-cca21a2f93e0.png">

## How To Reproduce
1. Right-click on an image in a post 
2. Select "Save Image"

## Your Environment
 - OS: MacOS Mojave 10.14 (beta)
 - Whalebird Version: 1.5.6
 - Instance: mastodon.social

The problem report in MacOS says:
```
Application Specific Information:
Crashing on exception: -[_NSImageViewSimpleImageView setDoubleValue:]: unrecognized selector sent to instance 0x6000028603c0
```

**Comment by h3poteto** [comment]
May be the cause is electron. I'm waiting for newer electron release.

**Comment by amyspark** [comment]
https://github.com/electron/electron/issues/14008

**Comment by TorinEmard** [comment]
I checked again and this doesn't happen in Whalebird 2.6.0.

**Comment by h3poteto** [comment]
OK, thank you!
