### ISSUE TITLE
Instance custom emoji

### ISSUE THREAD

**Issue by Canorus** [h3poteto/whalebird-desktop#480]
## Describe

Rendering image of custom emoji instead of shortcode like `:blobfacepeek:`

(This may have been requested or already in your mind but since I can't find anyone did request, so I'm doing it now.)

## Why
Why do you want this feature?

(I think) this is what makes Mastodon different from Twitter, among many other things.

**Comment by h3poteto** [comment]
Refer: https://github.com/tootsuite/mastodon/blob/782224c99151665470b138add583d50df17b4380/app/javascript/mastodon/features/emoji/emoji.js

**Comment by Canorus** [comment]
I seem to have failed to fully explain my intention, my apologies.

On my WhaleBird, toots including emojis are displayed as `:blobthinking:` rather than ![:blobthinking](https://storage.googleapis.com/twingyeo-kr-media/custom_emojis/images/000/001/372/original/31941ee3a785a047.png), as a text not image. Latter, in my opinion, is what was intended.

**Comment by h3poteto** [comment]
OK, I see. I will implement it.
