### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by UnderEu** [h3poteto/whalebird-desktop#4806]
Just downloaded v6.0.0 and, when I type the instance domain, it loops back to the start.

![ezgif-4-79e78fc194](https://github.com/h3poteto/whalebird-desktop/assets/16519758/a1077367-cc6a-4ea6-8eb5-6fccccffcd64)

OS: Ubuntu MATE 22.04
Tried using AppImage and DEB versions from the Releases tab, same result.

**Comment by h3poteto** [comment]
Did you click sign in after you type the domain?
