### ISSUE TITLE
Friendica login not possible

### ISSUE THREAD

**Issue by foss-** [h3poteto/whalebird-desktop#4815]
Whalebird 5.1.0

Now that support for friendica has been added in 5.1.0 (thank you ❤️) wanted to re-try whalebird client. But ran into an error message.

1. enter pirati.ca or squeet.em domain name to add account
2. click `Search`

Error is shown: `Failed to connect to pirati.ca, make sure the server URL is valid or correct.`

Also reproducible with squeet.me so wondering if there is a general problem adding friendica accounts.

**Comment by h3poteto** [comment]
Have you tried 6.0.0?

**Comment by foss-** [comment]
Hah, I missed that, since I only checked MAS. Kudos to the release. Retried with 6.0.0.

1. enter pirati.ca or squeet.me domain
2. click `Sign in`

There is an interesting misbehavior when entering the domain and pressing `Enter` where nothing happens, the login dialog reloads and is blank.

When clicking the Sign In button the browser loads and shows the auth code to then paste into Whalebird, which adds the account as expected.

So you may want to look into pressing enter after entering domain, but that is a different issue than what is being discussed here.

Thanks for keeping Whalebird under active maintenance ❤️
