### ISSUE TITLE
failed to get authorize URL

### ISSUE THREAD

**Issue by naoyaikeda** [h3poteto/whalebird-desktop#4854]
## Description
Login form doesn't show up after putting in the domain, fails with "failed to get authorize URL"

## How To Reproduce
1. enter vivaldi.net on the login
2. press the button twice

## My Environment
* OS: Windows 11
* Whalebird Version 5.1.0.0 (Latest in Microsoft Store)
* Instance: vivaldi.net

**Comment by h3poteto** [comment]
vivaldi.net does not open an API endpoint to register apps. It returns 404
```
POST https://vivaldi.net/api/v1/apps 404 (Not Found)
```
so, we can't use it from Apps.
