### ISSUE TITLE
can't properly reply to posts

### ISSUE THREAD

**Issue by unDocUMeantIt** [h3poteto/whalebird-desktop#4870]
the flatpak version seems to be a bit dated and the snap version didn't work for me, so i installed 6.0.2 from the debian package today on ubuntu 22.04. it seems i can't reply to posts any longer, which worked fine with 5.1.1 (flatpak). my replies are sent, but as standalone posts tagging the original posts author. they are not attached to the post. guess this is not a mastodon feature ;)

**Comment by h3poteto** [comment]
Thanks, it has been fixed: https://github.com/h3poteto/whalebird-desktop/pull/4863
