### ISSUE TITLE
(almost) no settings and l10n available in 6.0.2

### ISSUE THREAD

**Issue by unDocUMeantIt** [h3poteto/whalebird-desktop#4872]
using the debian package of whalebird 6.0.2 on ubuntu 22.04, there are almost no settings available. this is all options i get: 

![screenshot_2024-03-07_11-01-33](https://github.com/h3poteto/whalebird-desktop/assets/1068974/2dc25522-180b-40f1-a9b5-abb9e0302555)

the list of languages (english, chinese? and portuguese) is complete.

perhaps it would be time well spent to set up a [project at build.opensuse.org](https://openbuildservice.org/help/manuals/obs-user-guide/art.obs.bg) that automatically builds whalebird from the git sources for multiple distributions? looks like it can also build [flatpak apps](https://openbuildservice.org/2021/02/18/introducing-flatpak-builds/).

**Comment by h3poteto** [comment]
I removed unnecessary settings, and other languages are not translated: https://crowdin.com/project/whalebird-desktop

**Comment by unDocUMeantIt** [comment]
how come 5.1.1 was available in multiple languages (i count about 20)?

**Comment by h3poteto** [comment]
I've rewritten all functions with React, so we can't reuse the old translation files.
