### ISSUE TITLE
Latest update wiped out accounts and removed dark mode

### ISSUE THREAD

**Issue by datawench** [h3poteto/whalebird-desktop#4913]
I used homebrew to install whalebird on my mac some time ago. Yesterday I had occasion to do a full brew upgrade. When I next launched whalebird, all accounts were lost (I can re-authorize them) and the dark mode I'd set is now not even available.

Not sure what happened here.

**Comment by h3poteto** [comment]
https://pleroma.io/notice/AeAttsDIAh7qGIkGVE

**Comment by datawench** [comment]
Ah. I see. Thanks for the info.
Looking forward to features being restored, and whatever comes next.
