### ISSUE TITLE
Re-enable the right-button "Copy Link" menu

### ISSUE THREAD

**Issue by Dret42** [h3poteto/whalebird-desktop#4917]
I would like to suggest to reintroduce this feature for a better user-experience when you want to open a link not in the predefined app.

Thanks!

**Comment by h3poteto** [comment]
I forgot that feature......, does the previous version have a context menu?

**Comment by Dret42** [comment]
Yes, in version 5.x I used it constantly and I immediately noticed the difference! :)

**Comment by Dret42** [comment]
I found that also the "Copy Image" right-click function is not more present... :(

**Comment by Dret42** [comment]
Hi, and **thanks a lot for the implementation of the context menu**.

I would like to report **a little bug** and **a possible improvement**:

**1) The little bug**. Clicikng on a attached portrait image (with vertical orientation) the original image is displayed in a pop-up. But the image is cutted at the bottom (see arrow in image below) because in not resized to the max-screen height.

![Screenshot 2024-08-10 17 40 41](https://github.com/user-attachments/assets/5cb4e9f3-7f08-4ec0-9bcc-4db8ab059688)


**2) The improvement:** Would be great to add the possibility in context menu for options like: "Save image as..." and "Copy Image" as it stands in 5.11 version (see image below).

![Screenshot 2024-08-10 18 03 18](https://github.com/user-attachments/assets/79e13139-3ad2-4af7-ae44-f303e0dc02a5)

Thanks advance!
Bye
