### ISSUE TITLE
Can't connect to self-hosted GoToSocial instance

### ISSUE THREAD

**Issue by kvibber** [h3poteto/whalebird-desktop#4963]
GoToSocial implements most of the Mastodon client API, and I'm able to connect to it with other Mastodon clients like Elk, Semaphore, Tusky, etc. But when I try to connect to my GTS server with Whalebird, I get the error: "Failed to connect to ___________, make sure the server URL is valid or correct."

Linux, Fedora 40
Whalebird 5.1.1 installed via flatpak

Server logs show Whalebird successfully hitting /.well-known/nodeinfo and /nodeinfo/2.0

**Comment by h3poteto** [comment]
Please use the latest Whalebird.
Whalebird started supporting Gotosocial from 6.1.1.
