### ISSUE TITLE
[Question] Where are account(s) stored?

### ISSUE THREAD

**Issue by adevoss** [h3poteto/whalebird-desktop#5012]
Had to reinstall the OS (Linux).
Most of my settings of my applications are stored in my home directory.

When Whalebird starts there are no accounts.
Can I restore my accounts from a backup?

Among the files of the backup I can't find anything with "whalebird" in the name (except the application itself).

**Comment by h3poteto** [comment]
You've already reinstalled your OS?
It's difficult......

Accounts are stored in indexedDB on Electron browser. So, you can't find it in your backup files.

**Comment by h3poteto** [comment]
Usually, IndexedDB is stored at `~/.config/Whalebird/IndexedDB`. If you restore it, perhaps accounts will be restored.

**Comment by adevoss** [comment]
In the backup there is a db in ~/.config/Whalebird/db/*.db
Now it is changed to the location you posted.
So that's why the accounts were not restored.

See what happens on the next restore with the next major OS release.
Thanks.
