### ISSUE TITLE
Reset scroll position when viewing a new user profile

### ISSUE THREAD

**Issue by brkattk** [h3poteto/whalebird-desktop#504]
## Description
If the user profile sidebar panel is open and has been scrolled, then you click on a new user to view their profile, the scroll position of the sidebar panel should be reset to the top.

## How To Reproduce
1. From timeline, click user avatar to open profile panel
2. Scroll profile panel
3. Back in timeline, click a new user avatar

## Your Environment
 - OS: macOS 10.13.6
 - Whalebird Version: 2.0.0
 - Instance: mastodon.technology

**Comment by amyspark** [comment]
I think I fixed this in #745. Can you try and see if it works for you @brkattk ?
