### ISSUE TITLE
Whalebird limits you to 500 character post even if your instance allows more

### ISSUE THREAD

**Issue by tv21** [h3poteto/whalebird-desktop#5044]
Seems like Whalebird has a 500 character limit on posts, but the instance I use (hear-me.social) allows 12000 character posts.  Please allow the instance limit rather than the default limit.

**Comment by h3poteto** [comment]
![Screenshot from 2024-09-07-16-14-12](https://github.com/user-attachments/assets/f0f208a0-ae7e-4f2c-b189-855389e3e604)

It has already been allowed.
