### ISSUE TITLE
Toot Visibility option not working

### ISSUE THREAD

**Issue by Canorus** [h3poteto/whalebird-desktop#505]
## Description

I requested an option to set default toot visibility in preferences panel on issue [\#461](https://github.com/h3poteto/whalebird-desktop/issues/461) and thank you very much for that, but it doesn't seem working on App Store version.

## How To Reproduce
1. Set visibility to other than public(unlisted or private)
2. Call a new toot compose modal and find out it's still public toot

## Your Environment
 - OS: macOS 10.13.6
 - Whalebird Version: 2.0.0 App Store version
 - Instance: All(https://twingyeo.kr, https://cmx.im)

**Comment by h3poteto** [comment]
Oh! I see. May be the change was degrade some other changes.
I will fix it as sonn as possible.
