### ISSUE TITLE
On the latest version, on Desktop Windows, please use Arial not the Roboto font

### ISSUE THREAD

**Issue by amsm** [h3poteto/whalebird-desktop#5056]
Hi.
In my case, using the latest version, the posts became less readable, presented with thinner and grayer letters. I suppose this is because (of a switch to?) the Roboto font.
The current publications' presentation is much less readable than it was, to my eyes.
Using the developer tools, I can force font-family:Arial , but it is not convenient at all.

So, please consider at least giving the user the Arial font option.

Thank you for this great software!

**Comment by h3poteto** [comment]
Which version are you talking about? 6.1.4? or 6.1.5?

**Comment by amsm** [comment]
Thank you for replying!
6.1.4
installed from
Whalebird-6.1.4-win-x64.exe

**Comment by h3poteto** [comment]
Did 6.1.3 work with Arial font?

**Comment by amsm** [comment]
I am not totally sure if it was v6.1.3, but it was a MS Store signed version, recent enough - and it did not have font problems. I suppose it defaulted to Arial, and it worked fined.
v6.1.4, in my system, defaults to the Robot font which is rendering thin and gray, not crisp and black. If I force Arial from the developer tools, the reading experience improves greatly.

**Comment by h3poteto** [comment]
I've checked 6.1.3 and 6.1.2, but both are Roboto font. I don't know when Arial font has been changed.

**Comment by amsm** [comment]
Any chance of bringing it back, at least optionally? Thank you!

**Comment by h3poteto** [comment]
First, I'm going to change the default font settings. After that, I'm going to implement a function to change fonts.

**Comment by h3poteto** [comment]
https://github.com/h3poteto/whalebird-desktop/issues/5060

**Comment by amsm** [comment]
Thank you!
