### ISSUE TITLE
Not possible to answer to multiple persons and the visibility level isn't kept

### ISSUE THREAD

**Issue by Astaoth** [h3poteto/whalebird-desktop#5070]
Hi,

When I answer to a toot, the previous toot writter is automatically mentionned at the beginning, unless it's me. This is the normal behaviour and it's good.

However, when we are multiple persons in the discussion, with multiple @ in the previous toot, they aren't automatically added. I have to writte the missing @ (which are everyones outside of the previous toot writter) myself.
In addition, despite the https://github.com/h3poteto/whalebird-desktop/issues/380 issue, I've seen the visibility level isn't kept.

It's especially annoying because I'm often in private discussions with multiple people. I can't answer to them in a fluid manner because I have to re-add all of them, and to change the visibility level each time.

Would it be possible, when answering to a toot which mentions multiple people, to prefill the answer by mentionning all of them, and to change the visibility level to the same than the previous toot ?

I use Whalebird 5.1.1 installed from flatpak.

**Comment by h3poteto** [comment]
5.1.1 has already been deprecated, and flatpak has no longer been updated. Please use the latest Whalebird.

**Comment by Astaoth** [comment]
Ah, sorry, I should have checked this before making this issue. There is ineed none of this issues with the latest version, thank you for pointing this to me.

I use whalebird in an env where I can't install system packages, but I've seen you provide an appimage too, I'll switch to this one. Is there any reason for not keeping the flatpak package ?

**Comment by h3poteto** [comment]
No one maintains flatpak package.
https://github.com/h3poteto/whalebird-desktop/issues/4641

**Comment by Astaoth** [comment]
Oh, I see. Thanks for your anwsers, I guess I can close this and no longer annoye you :)
