### ISSUE TITLE
Failed to authorize my 2nd account

### ISSUE THREAD

**Issue by PicoSushi** [h3poteto/whalebird-desktop#518]
## Description
I tried to add my second account on Whalebird. Opening auth URL and getting code succeeded, but after pasted authorization code and clicked Submit button, Whalebird returned "Failed to authorize"
 error.
## How To Reproduce
1. Add some 1st account. This works successfully.
2. Click "+" button on most left bar. 
3. Enter mastodon instance domain name, click "Search", and click "Login".
4. Authorization URL opens in browser. Click allow in browser and authorization code appears.
5. Enter authorization code in Whalebird.
6. "**Failed to authorize**" appears.

## Your Environment
 - OS: Windows 10
 - Whalebird Version: 2.0.0(latest)
 - Instance: mastodon.cloud

**Comment by PicoSushi** [comment]
Additional information: after failing that authorization, every toots displayed as duplicated.

But, after restarting Whalebird, it fixed.

**Comment by h3poteto** [comment]
This cause is mastodon, and the fix is already merged.
https://github.com/tootsuite/mastodon/pull/8231

Please tell the administrator of mastodon.cloud to update mastodon source code.
