### ISSUE TITLE
Custom emoji compatibility

### ISSUE THREAD

**Issue by Boundarybreaker** [h3poteto/whalebird-desktop#525]
## Describe
Currently, WhaleBird (at least Darwin 2.0.1) doesn't parse Mastodon's custom emoji. It would be pretty cool if it was able to sometime.

## Why
Custom emoji are one of the most fun features exclusive to Mastodon, and seeing a lot of :wordsincolons: everywhere really detracts from the use of the system.

**Comment by h3poteto** [comment]
I merged it today.
https://github.com/h3poteto/whalebird-desktop/pull/516
