### ISSUE TITLE
Get packages into Linux repositories

### ISSUE THREAD

**Issue by vinzv** [h3poteto/whalebird-desktop#526]
This is low priority task: To avoid having to check for new versions on the website it would be cool to get DEB/RPMs into Linux distribution's repositories. openSUSE's build service automates this process quite well.
So, if you could provide the .src.rpm I would volunteer on putting it to there.

**Comment by h3poteto** [comment]
I'm using electron-builder to build this application.
And electron-builder accepts AppImage, snap, deb, rpm, freebsd, pacman, p5p, apk, 7z, zip, tar.xz, tar.lz, tar.gz, tar.bz2, and dir as archive.
https://www.electron.build/configuration/linux

So may be I can't build .src.rpm.
