### ISSUE TITLE
Unable to paste images into compose dialog

### ISSUE THREAD

**Issue by pawjob** [h3poteto/whalebird-desktop#530]
## Description
I am unable to append an image from my clipboard to a new Toot. This functionality is present in a desktop browser.

## How To Reproduce
1. Press "New Toot" button
2. Paste image using Ctrl+V or Right Click + Paste into "New Toot" dialog

## Your Environment
 - OS: Windows 7
 - Whalebird Version: 2.1.0
 - Instance: mastodon.social

**Comment by Canorus** [comment]
+1 for Feature Request

**Comment by h3poteto** [comment]
This feature is merged today.
https://github.com/h3poteto/whalebird-desktop/pull/532
