### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by GambaJo** [h3poteto/whalebird-desktop#536]
## Describe
Would be great, if the app could also minimize to tray.

## Why
So my boss can't see, what I'm doing ;)

**Comment by h3poteto** [comment]
What is your OS?

**Comment by GambaJo** [comment]
Widows 10 and Linux Mint Mate. But I use Linux private, so this feature is more important for Windows.

**Comment by h3poteto** [comment]
I have never used Windows10, so I don't know this function.
I can't implement this because I can't confirm it on my computer.

If you send a pull request, I will merge.

**Comment by PicoSushi** [comment]
As I think, whalebird-desktop is using electron so that's possible as Slack client does.

other ref:
https://stackoverflow.com/questions/37828758/electron-js-how-to-minimize-close-window-to-system-tray-and-restore-window-back

**Comment by GambaJo** [comment]
@h3poteto Sorry, I don't know electron, but it looks interesting.

**Comment by marxistvegan** [comment]
I am on Solus Project OS and I dont see an option for system tray. Is it possible to set as an option (great work on this by the way!)
