### ISSUE TITLE
Keyboard shortcut

### ISSUE THREAD

**Issue by Canorus** [h3poteto/whalebird-desktop#543]
## Describe

A customizable keyboard shortcut would provide great user experience. There's basic keyboard shortcut for composing new toot and changing instances, but these, imao, are far from enough.

- [ ] cmd + r ( ctrl + r ) for boosting
- [ ] cmd + t ( ctrl + t ) for mention(to toot)
- [ ] cmd + e ( ctrl + e) for favourite
- [ ] cmd + shift + r ( ctrl + shift + r) for refreshing etc.

If you just provide items on menu bar, macOS users can customize their own shortcuts within their preferences app.

## Why

Keyboard shortcut has been crucial part of user experience on desktop/laptop devices. My only concern is, if it will also work well on other OS like Win10 or linux.

**Comment by h3poteto** [comment]
Now Cmd+R is used in reload timeline, so would you like to change to another key?

**Comment by Canorus** [comment]
Those are just examples I can come up. You may set any other key combination and I(as well as others) can get used to it, but it would be **very** appreciated if those combinations are customizable.
