### ISSUE TITLE
Emoji in usernames not rendered

### ISSUE THREAD

**Issue by runrunrirun** [h3poteto/whalebird-desktop#548]
## Description
New emoji support seems to be working well, thx... but just noticed that emoji in username/handle still don't render.

## How To Reproduce
1. See attached
<img width="383" alt="screen shot 2018-08-20 at 12 25 56" src="https://user-images.githubusercontent.com/1388365/44356503-285b4880-a475-11e8-9ce7-2ac9069e7278.png">

## Your Environment
- Whalebird Version 2.1.0 (41)

**Comment by h3poteto** [comment]
I knew it, but it is not easy.
