### ISSUE TITLE
Incorrect Settings Tab Stays Highlighter

### ISSUE THREAD

**Issue by codeacula** [h3poteto/whalebird-desktop#551]
## Description
When changing settings, the wrong settings tab stays highlighted after leaving settings and returning.

## How To Reproduce
1. Ctrl+,
2. Click Account
3. Click "X" to close
4. Ctrl+, again

Account is blue but we're not on that tab

## Your Environment
 - OS: Windows
 - Whalebird Version: 2.1.1
 - Instance: mastodon.gamedev.place

**Comment by h3poteto** [comment]
Oh, it is a bug...
