### ISSUE TITLE
Uncaught Exception: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by PicoSushi** [h3poteto/whalebird-desktop#553]
## Description
When using WhaleBird with unreliable network, a window as "A JavaScript error occurred in the main process" appeared.

![2018-08-22 01_11_45-error](https://user-images.githubusercontent.com/37548801/44414284-5ee5b000-a5a8-11e8-97ac-f7b2b18c851f.png)

## How To Reproduce
1. Open WhaleBird with bad network.
2. That error occurred.

## Your Environment
 - OS: Windows 10
 - Whalebird Version: 2.0.0
 - Instance: any

**Comment by h3poteto** [comment]
I didn't consider this pattern.

**Comment by amyspark** [comment]
@h3poteto, this needs an extra handler on the `electronProcess`. Do you want me to add it?

**Comment by h3poteto** [comment]
I don't know what kind of changes you are going to make. And I don't know the cause. So I can't judge.
Do you know the cause in the first place?

**Comment by amyspark** [comment]
@h3poteto I can get tons of these by forcibly using Websockets for timeline streaming (by commenting streaming_manager.js) and then hibernating the computer. An unreliable Internet connection works too.
```
┏ Electron -------------------

  [16:33:16.956] [info] streaming stopped

┗ ----------------------------

┏ Electron -------------------

  [16:33:16.960] [info] streaming stopped

┗ ----------------------------

┏ Electron -------------------

  { Error: read ECONNRESET
      at TLSWrap.onread (net.js:657:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }
  { Error: read ECONNRESET
      at TLSWrap.onread (net.js:657:25) errno: 'ECONNRESET', code: 'ECONNRESET', syscall: 'read' }

┗ ----------------------------

┏ Electron -------------------

  Closed connection with 1006
  Closed connection with 1006

┗ ----------------------------

┏ Electron -------------------

  Reconnecting

┗ ----------------------------

┏ Electron -------------------

  Reconnecting

┗ ----------------------------
```

This is the suggested diff:

```diff
diff --git a/src/main/index.js b/src/main/index.js
index 3e734c3..8d7ab91 100644
--- a/src/main/index.js
+++ b/src/main/index.js
@@ -253,6 +253,10 @@ app.on('activate', () => {
   }
 })

+process.on('uncaughtException', (e) => {
+  console.error(e)
+})
+
 let auth = new Authentication(accountManager)

 ipcMain.on('get-auth-url', (event, domain) => {
```

**Comment by h3poteto** [comment]
It will catche other exceptions. Is the rescue range too wide?
I want to catche only this error.

**Comment by amyspark** [comment]
This sort of connection error bubbles from here:

https://github.com/h3poteto/megalodon/blob/0a4a65048abc8573dc54f2d089d283e16c7e3869/src/web_socket.ts#L128

Somehow the callback that Whalebird adds to the streaming doesn't catch it. I'm trying to reproduce it again under a debugger to get the full console log.
