### ISSUE TITLE
DM replies are public.

### ISSUE THREAD

**Issue by kevquirk** [h3poteto/whalebird-desktop#569]
## Description
If someone sends me a direct message on Mastodon, and I reply via Whalebird, the reply defaults to a public Toot. This has obvious privacy implications.

## How To Reproduce
1. Get someone to send you a DM.
2. Reply to it and check the privacy setting.

## Your Environment
 - OS: Ubuntu 18.04.1
 - Whalebird Version: 2.1.1
 - Instance: fosstodon.org

**Comment by h3poteto** [comment]
The fix is merged now!
https://github.com/h3poteto/whalebird-desktop/pull/570
