### ISSUE TITLE
New shortcuts affect New Toot entry, so 'h' and 'j' cannot be used in toot text

### ISSUE THREAD

**Issue by PhotonQyv** [h3poteto/whalebird-desktop#573]
## Description
The shortcuts for help (h) and select next toot (j) are active in the New Toot dialog, so typing them opens the help dialog in the case of 'h', or does nothing in the case of 'j', meaning that you have to toot without the use of these two letters, or use their capitalised versions.

## How To Reproduce
1. Open New Toot dialog
2. Start typing... 'The quick brown fox jumped over the lazy dog
3. Result, help dialog will pop up on pressing 'h', twice, and no 'j' will show up so you end up with 'Te quick brown fox umped over te lazy dog'.

## Your Environment
 - Linux (Bionic Kubuntu)
 - Whalebird Version: 2.1.2
 - Instance: mastodon.xyz

**Comment by PhotonQyv** [comment]
@h3poteto Yep, merged your commit f3a16235ff08c96495c88f872b4a68ad53ca00f7 where you bump the version to 2.1.2 into my version.

Just checking that I actually installed it...
Just re-building...
Just re-installed...

No, still happening!

Sorry (:*

**Comment by PhotonQyv** [comment]
@h3poteto Apologies, the bug still happens.

I've also checked that I really did merge all the changes from your master by attempting another PR, with the result:

"There isn’t anything to compare.
PhotonQyv:master is up to date with all commits from h3poteto:master."

[The only difference from yours to mine is that I use Bookerly font while yours uses Lato].

Sorry my last comment was a little unclear. I sometimes forget that not everyone's first language is the same as mine (;*

**Comment by h3poteto** [comment]
Now, I cloned `PhotonQyv:master`, install, and run it.
I can input `j` and `h` keys on NewToot modal.
Sorry, I can not reproduce...

OS: Ubuntu18.04
Branch: PhotonQyv:master 
Revision:  612b8c0e90f4032d654a133bb7b4a8be02880e0c

**Comment by PhotonQyv** [comment]
@h3poteto Ok, time for me to clean up my end and try again (:* Funny, I was going to clone yours and try that (:*

**Comment by PhotonQyv** [comment]
@h3poteto Ok, removed my build directory and re-cloned from my repo, app now works correctly. Wonder what got messed up in my original local copy?

Anyway, I'll now close the issue. Apologies for the false positive.

**Comment by h3poteto** [comment]
OK, that's good.
I was relieved.
