### ISSUE TITLE
Notifications: Control over the in-app notifications shown

### ISSUE THREAD

**Issue by arunsathiya** [h3poteto/whalebird-desktop#581]
I am referring to the notifications app inside the app in this context, and push notifications on Mac, if any.

## Suggestion 

It would be a good idea to have an option on the app's settings, to hide notifications about new followers and new likes on the toots.

A few users would prefer to see notifications only for replies, and having more granular control over what kind of notifications are seen helps.

## Additional reason why

When notifications about new followers and new likes on toots are shown, they are not grouped together. This causes a wastage of screen space which is why disabling these notifications entirely is a better idea, IMO.

****

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by h3poteto** [comment]
OK, I agree. I want to set in preferences.
