### ISSUE TITLE
In-app notifications: Group similar notifications together

### ISSUE THREAD

**Issue by arunsathiya** [h3poteto/whalebird-desktop#582]
It would be a good idea to group in-app notifications together, on the `Notification` tab of the app.

I have arrived at this idea from this issue #581. The idea is that notifications about new followers, new likes on toots can be grouped together periodically to show in this format:

`A, B and C favorited your toot.` and `A, B and C followed you.`

This feels better over seeing an endless chain of new follower and new like notifications on the `Notification` tab of the app.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by h3poteto** [comment]
I understand, but it is not easy...
