### ISSUE TITLE
Use favicon of instance as global header icon for distinction

### ISSUE THREAD

**Issue by munierujp** [h3poteto/whalebird-desktop#597]
## Describe
Use favicon of instance as global header icon for distinction.

## Why
If user is using same icon for multiple instance, user can't distinguish instance on global header 😭 

![2018-09-09 22 15 14](https://user-images.githubusercontent.com/20086673/45264859-2b4ac700-b47e-11e8-8f22-32acf27a9539.png)

**Comment by h3poteto** [comment]
I understand what you mean.

On one hand, some users use multiple accounts in same instance. So if I use favicon as icon, they can not distinguish their accounts.
And some instances don't customize favicon, they are using the default icon.
I can not judge which is better.

**Comment by munierujp** [comment]
>On one hand, some users use multiple accounts in same instance. So if I use favicon as icon, they can not distinguish their accounts.
And some instances don't customize favicon, they are using the default icon.

That's right.

And,  I noticed that I can see the instance name when mouse over on avatar.

![2018-09-09 23 03 28](https://user-images.githubusercontent.com/20086673/45265385-0a39a480-b485-11e8-9e9d-b45ff7d4f9a0.png)

I think that it's a good way to distinguish multiple instances.

Thank you.
