### ISSUE TITLE
View Multiple Specific Remote Mastodon Instances

### ISSUE THREAD

**Issue by MichaelTunnell** [h3poteto/whalebird-desktop#618]
## Describe
The ability to display the public timeline of an instance that you are not a part of. My accounts are on Mastodon.social but there are many instances that are for specific niche topics which would be cool to be able to view the public timeline for. Unfortunately, Mastodon does not have the ability to do this at the moment so if a client were able to do it I think it would be a massive selling point for that client.

For example, Mastalab has that ability on Android but nothing exists for it on the desktop and the way Mastalab does it is a bit clunky because of it being a mobile app. I think if Whalebird were to implement this function it would elevate it considerably for being the go to client.

## Why
I want it because Mastodon doesnt offer it and it would make it a lot easier to participate in remote instance conversations and just using Mastodon overall in general.

**Comment by h3poteto** [comment]
I have no intention of implementing this feature in Whalebird. Please see this article: https://medium.com/@h3poteto/im-developing-a-new-fediverse-client-application-for-desktop-fcd5b83a7ebb
Or please find another client.
