### ISSUE TITLE
Unable to Connect to Mastadon.social

### ISSUE THREAD

**Issue by trek-e** [h3poteto/whalebird-desktop#634]
## Description
After entering instance domain name, system doesn't do anything

## How To Reproduce
1.Download Whalebird from Appstore (Mojave and High Sierra Tried)
2.start app
3.enter mastodon.social for instance domain name

nothing happens.  no errors, no movement forward, nothing.

## Your Environment
 - OS: MacOS (High Sierra and Mojave tested)
 - Whalebird Version: 2.3.0 downloaded from App Store
 - Instance: mastodon.social

**Comment by h3poteto** [comment]
This behavior is occur only mastodon.social? You can login to other instances?

**Comment by trek-e** [comment]
Oh hey, sorry hadn't thought to try others.  Tried a couple others and those progressed.  Appears it's an issue with mastodon.social where I have my account.   Is there a log I can share?
