### ISSUE TITLE
Support profile metadata

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#644]
## Describe
Whalebird is currently missing the metadata fields for Mastodon profiles.

## Why
I've been using Mastodon for a short while and I can't get to see the metadata for the users I follow.

**Comment by h3poteto** [comment]
Are you saying that you can not see your profile?

**Comment by amyspark** [comment]
I can see my profile and everyone's, what is not being shown is the four metadata fields associated with the selected profile:

![mastodon](https://user-images.githubusercontent.com/13498015/46639016-1e32fd80-cb3a-11e8-9859-86edcc1a741a.jpg)

![whalebird's profile UI](https://user-images.githubusercontent.com/13498015/46639017-1ecb9400-cb3a-11e8-92ef-cf43e5b37e11.jpg)

(I've marked the profile metadata in Mastodon's UI with a box)

**Comment by h3poteto** [comment]
Oh, I see, thank you for reporting.

**Comment by sl154672** [comment]
#644
