### ISSUE TITLE
"gifs" served as MP4 are still inserted in <img> elements

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#666]
## Description
For the sake of looped playback and bandwidth efficiency, recently GIFs are converted to and served as MP4 videos. These, although successfully retrieved by Whalebird, are shown as 0x0 `<img>` elements instead of `<video>`.

## How To Reproduce
1. Load this toot in Whalebird: https://mastodon.social/@tahajin/100901260792957585
2. Try opening the embedded animation.

## Your Environment
 - OS: [e.g. MacOS] MacOS Sierra 10.12.6
 - Whalebird Version: [e.g. 1.0.0] 2.4.2
 - Instance: [e.g. mastodon.social] mastodon.social

**Comment by amyspark** [comment]
@h3poteto I've downloaded Whalebird's source, can I take this up?

**Comment by h3poteto** [comment]
Yes, thank you. I'm waiting for you contribution.
