### ISSUE TITLE
Retrieve and apply instance's custom emoji

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#667]
## Describe

It would be great if Whalebird retrieved and applied the current instance's custom emojis.

## Why

ref #564, each instance can define custom emoji for their users. Currently, emojis not in the `emojilib` library are still rendered as `:short_code:`.

**Comment by h3poteto** [comment]
Instance custom emoji is already implemented: https://github.com/h3poteto/whalebird-desktop/issues/480

Can you see custom emojis?
I can enter the custom emoji:
![screenshot from 2018-10-29 21-45-48](https://user-images.githubusercontent.com/4631959/47650618-207dfa00-dbc4-11e8-8263-fa24de802621.png)

and it is rendered.
![screenshot from 2018-10-29 21-47-18](https://user-images.githubusercontent.com/4631959/47650650-3ee3f580-dbc4-11e8-8bdb-93b58318bdb0.png)

**Comment by amyspark** [comment]
Duplicate of #548, upon further review.
