### ISSUE TITLE
Let toot visibility follow web settings.

### ISSUE THREAD

**Issue by Canorus** [h3poteto/whalebird-desktop#673]
## Describe

Can you make default toot visibility setting in sync with that on web version?

## Why

Currently WhaleBird's default toot visibility is set in App settings, which makes all toots sent from WhaleBird have one same value as default. However, once visibility setting follows web version, it would make better experience. Maybe *unlisted* from this account, *publish* from that account and so on.

Retrieving default visibility option maybe can be done on loading timeline?

This is just improve suggestion. Thanks.

**Comment by h3poteto** [comment]
Now I can not find the API to get visibility settings.
https://docs.joinmastodon.org/

>  once visibility setting follows web version

Really?
I don't remember making such implementation.

**Comment by h3poteto** [comment]
Oh, I see, thank you.
I found it too: https://docs.joinmastodon.org/api/entities/#source

Maybe I can implement this feature.
