### ISSUE TITLE
Feature to disable the local timeline notification bubble

### ISSUE THREAD

**Issue by skynebula** [h3poteto/whalebird-desktop#677]
## Describe
It could be great if we could disable (in the app settings) the little notification for new toots in the local timeline.
<img width="153" alt="screenshot 2018-10-25 14 48 14" src="https://user-images.githubusercontent.com/669147/47501281-686bec80-d865-11e8-93b0-d1ae065f2d09.png">

## Why
This kind of notification is useful on small instances, but if we are on mastodon.social for example (or any other big instance), it's useless, as new toots arrive in real time each and every second, in many different language, about various topics...
This little bubble cannot stop attracting attention. For nothing.

Thank you!

**Comment by skynebula** [comment]
Hey @h3poteto, I don't see any change in the new update. No setting despite the "allow customize unread notification of timelines" in the changelog :(

**Comment by h3poteto** [comment]
![screenshot from 2018-11-11 20-50-11](https://user-images.githubusercontent.com/4631959/48312534-6d65c580-e5f3-11e8-903b-62a17d037846.png)
![screenshot from 2018-11-11 20-50-20](https://user-images.githubusercontent.com/4631959/48312535-7060b600-e5f3-11e8-9272-78e5b00aa814.png)

**Comment by skynebula** [comment]
Okkkkkkk!
I just went to the global settings of the app (where all that should be gathered IMHO... :)
Thanks!
