### ISSUE TITLE
CWs are not respected when replying

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#695]
## Description
Content Words are not carried over when replying.

## How To Reproduce
1. Find a CW'd toot.
2. Reply to it, either with <kbd>r</kbd> or the Reply button.
3. Check the posted reply. The original toot's CW are not applied.

## Your Environment
 - OS: [e.g. MacOS] MacOS
 - Whalebird Version: [e.g. 1.0.0] 2.4.4 dev
 - Instance: [e.g. mastodon.social] Mastodon.social

**Comment by h3poteto** [comment]
Should the CW carry over when replying?
Actually, I don't know. I can't confirm it in mastodon web.

**Comment by amyspark** [comment]
At least Glitch Edition e.g. https://dev.glitch.social does.

**Comment by nursemchurt** [comment]
I'm on an instance using the "normal" version of Mastodon and can confirm that CWs should carry over.

**Comment by h3poteto** [comment]
I'm sorry, I could confirm it.
![screenshot from 2018-11-13 00-48-32](https://user-images.githubusercontent.com/4631959/48358329-df1a3e00-e6dd-11e8-986a-05836e06ffa2.png)
