### ISSUE TITLE
Some emojis are rendered incorrect

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#708]
## Description

<img width="621" alt="2018-11-15 0 57 53" src="https://user-images.githubusercontent.com/4631959/48494622-9eebc480-e871-11e8-8054-607ade1a11bf.png">

## How To Reproduce
1. Open New Toot modal
2. Open Character Viewer of macOS
3. Select the woman face-palming and click to inset

## Your Environment
 - OS: MacOS
 - Whalebird Version: 2.5.0

**Comment by amyspark** [comment]
I think this is because the modal uses the system font for composite emojis instead of embedding the shortcode.

**Comment by amyspark** [comment]
Oops, I was wrong. It actually uses Noto Sans for rendering the emojis by default. This font doesn't seem to work with compound emojis.
@h3poteto , you may want to edit the `--specified-fonts` stack to override Noto Sans with:
-   'Apple Color Emoji',
-  'Segoe UI Emoji',
 - 'Segoe UI Symbol',

(taken from the Bootstrap stack)

**Comment by h3poteto** [comment]
OK, I will try it. Thank you.

**Comment by amyspark** [comment]
Upon further digging, I removed the extra `--specified-fonts` variable in App.vue and dealt only with fonts.js.

I edited Whalebird's font stack with Bootstrap's as a fallback:
```js
export default [
  'Noto Sans',
  'Noto Sans CJK JP',
  'Takaoゴシック',
  'Hiragino Kaku Gothic ProN',
  'ヒラギノ角ゴ ProN W3',
  // 'Meiryo',
  // 'メイリオ',
  // 'Osaka',
  // 'MS PGothic',
  '-apple-system',
  'BlinkMacSystemFont',
  'Segoe UI',
  'Roboto',
  'Helvetica Neue',
  'Arial',
  'sans-serif',
  'Apple Color Emoji',
  'Segoe UI Emoji',
  'Segoe UI Symbol'
]
```
Any of the four fonts commented out breaks composite emoji when enabled.
