### ISSUE TITLE
Processes are not terminated in Windows.

### ISSUE THREAD

**Issue by kazh98** [h3poteto/whalebird-desktop#727]
## Description
After the Whalebird application is closed, its processes are left as "Background processes" and not terminated.

![default](https://user-images.githubusercontent.com/904792/48671159-81677500-eb67-11e8-9936-6c8c0642d1c6.PNG)
This picture shows the Whalebird processes appearing in the "Background processes" section of Task Manager after I iterated starting and closing the Whalebird application, which has three Mastodon accounts, three times.

## How To Reproduce
1. Start the Whalebird application.
2. Terminate it.
3. See the "Background processes" section in the "Processes" tab of Task Manager.

## Your Environment
 - OS: Windows 10 Pro [Version 1803]
 - Whalebird Version: 2.5.0 (when I saw this behavior at first.), 2.5.1 (when I saw this behavior most recently.)
 - Instance: social.arnip.org and mstdn.maud.io

----
Thank you for your considering my report on your great work "Whalebird."

**Comment by h3poteto** [comment]
How do you terminate it?
I think it is the feature of #596

**Comment by kazh98** [comment]
Thank you for your comment.
#596 resolves my problem completely.
I only closed the main window, without selecting the "Quit" item of the task tray.
I'm sorry that I didn't notice this feature.

In recent versions of Windows, I usually use minimization instead of the task tray because taskbar items became smaller and iconized.
So, I forgot the existence of the task tray.
However, I think this feature is dramatically useful for shortening the time for starting the application.

Thank you for your kindly answering.
