### ISSUE TITLE
Better resizability

### ISSUE THREAD

**Issue by cybercatgurrl** [h3poteto/whalebird-desktop#758]
## Describe

I'd like to keep Whalebird window width very small but Whalebird does not be seem to be designed with this in mind. 
## Why

A lot of established Twitter clients are very good at this and it would allow Whalebird to not take up very much real-estate just like Tweetbot or Twitterrific. Everything stops working once I shrink it down to a small width.

**Comment by h3poteto** [comment]
What specific features do you want? I don't know what problems do you have when you change the window size.

**Comment by amyspark** [comment]
Timeline width causes toots to break down if the width is too small (usually when opening the sidebar).

**Comment by alxlg** [comment]
Maybe making the sidebar width resizable and hiding main view when sidebar is open and there isn't enough space would solve the problem...?
![immagine](https://user-images.githubusercontent.com/26327475/49385691-498f2e80-f71e-11e8-9e84-648cf779b7e8.png)

**Comment by h3poteto** [comment]
refs: https://github.com/h3poteto/whalebird-desktop/issues/1046
