### ISSUE TITLE
Backtick renders as combining-accent

### ISSUE THREAD

**Issue by BrianEnigma** [h3poteto/whalebird-desktop#767]
## Description
When typing or displaying a backtick character, it gets combined with the following character as an accent.

## How To Reproduce, Typing
1. Click on “new toot” toolbar button.
2. Compose a toot like: Use `git add` to add files to git.
3. The app displays g with a backtick-accent and t (the first letter of “to”) with a backtick accent.
4. For what it's worth, the text itself still seems intact and fine. You can cut/paste over to a text editor and get the correct text. Only the display of the text is broken.

## How To Reproduce, Displaying
1. Use you Mastodon instances website to toot: Use `git add` to add files to git.
2. View the tweet in the Whalebird timeline and see the above-mentioned render problem.

## Your Environment
 - OS: MacOS High Sierra (10.13.6)
 - Whalebird Version: 2.5.2 (60)
 - Instance/Problematic Toot: https://xoxo.zone/@BrianEnigma/101179389694974239

**Comment by BrianEnigma** [comment]
<img width="314" alt="screen shot 2018-12-03 at 4 08 56 pm" src="https://user-images.githubusercontent.com/925799/49409506-cf5aac00-f715-11e8-8a35-29056e744792.png">

**Comment by h3poteto** [comment]
Please use latest version, it is already fixed.
![2018-12-04 10 31 57](https://user-images.githubusercontent.com/4631959/49412804-1d70bd80-f7b1-11e8-9a17-c1ed5ca1065d.png)
