### ISSUE TITLE
Cloud not post image

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#789]
## Description
<img width="479" alt="2018-12-14 16 08 06" src="https://user-images.githubusercontent.com/4631959/49988569-97c3ed80-ffba-11e8-9f94-c32b5ea395e3.png">

The preview is not displayed.

## How To Reproduce
1.
2.
3.

## Your Environment
 - OS: MacOS
 - Whalebird Version: 2.6.1
 - Instance: pleroma.io

**Comment by amyspark** [comment]
Does your Pleroma instance use a media proxy?

**Comment by h3poteto** [comment]
It is a pleroma's problem. I solved it, thank you.
