### ISSUE TITLE
Improve loading indicator

### ISSUE THREAD

**Issue by CR0CKER** [h3poteto/whalebird-desktop#792]
## Describe
Instead of covering the entire app with a shadow and showing a loading indicator in the middle, which prevents the user from doing anything else with the interface, I suggest we remove the shading and display the loading indicator in the navigation bar at the top of the app. 

## Why
Keeping the UI accessible while loading content would allow users to continue scrolling or otherwise interacting with the app while additional content is loaded.

**Comment by h3poteto** [comment]
Now I can not accord this. 
Because when the loading indicator is displayed, the app treat some data and it must not be interrupted. And it can not tolerate data inconsistency.

**Comment by CR0CKER** [comment]
Are you sure, @h3poteto? When using the standard Mastodin web interface, it never does this. Is there a fundamental difference between the standard web UI and Whalebird? Considering that Electron is just a browser, I don’t see why the Whalebird UI must completely block any interaction while loading, if the standard Mastodon web UI is able to solve this differently.

**Comment by h3poteto** [comment]
Whalebird UI is different from Web UI, and I don't aim for the same UI as the Web.
For example, Whalebird can switch multiple accounts.
The loading indicator is necessary to keep the state when user switches accounts.

**Comment by CR0CKER** [comment]
Hmm, I see. Could we make the loading indicator more subtle? Even if we don't allow the user any interaction with the UI while loading, we may not have to block the whole UI. I think the Riot.im desktop client has the same issue that you describe, and they also show a loading indicator, but it's still possible to scroll while the additional data is loaded. Maybe we cannot allow the user to modify any content while loading the additional information, but we could allow to scroll and read? Right now, using the app feels like I am spending a lot of time looking at black UI blackouts :)

**Comment by h3poteto** [comment]
> Even if we don't allow the user any interaction with the UI while loading, we may not have to block the whole UI.

I think that it is not possible under current data structure. If you think it possible, please create pull request.
