### ISSUE TITLE
Keep app running while app window is closed on macOS

### ISSUE THREAD

**Issue by CR0CKER** [h3poteto/whalebird-desktop#794]
## Describe
The app should continue running in the background while the window is closed on macOS. Currently the app closes, and needs to reload whenever the app icon is closed and the window reopens.

## Why
It is standard behavior on macOS that apps keep running and preserve the window state and content while the window is closed. I saw there was actually a feature request #319 that suggested to quit the app when closing the window, but this is non-standard behavior on macOS.

**Comment by h3poteto** [comment]
It is already implemented.
https://github.com/h3poteto/whalebird-desktop/pull/446

**Comment by CR0CKER** [comment]
I think there is a misunderstanding about this issue. The current version on macOS does indeed keep running when the main window is closed, but whenever the window is reopened, the window content has been lost, the user stares at the launch popup, and then has to wait until all content has loaded again. Expected behavior (and a lot more convenient) would be that the window opens exactly with the same content as when it was closed, immediately. That is not happening in the latest version.

**Comment by h3poteto** [comment]
The close button is not minimize. So there is no need to reproduce the previous state when the app is reopened. Please use minimize.
For example, google chrome: if you close (not quit) google chrome, and reopen, google chrome does not reopen previous tabs.

**Comment by CR0CKER** [comment]
You're correct about Chrome, but it seems to me that most macOS apps reinstate the content of the main window. Apple Mail, Tweetbot, Calendar, Messages, Bear, Reeder, and Electron apps like Riot and Signal all retain the main window content when closing and reopening it. I think it's just a lot more convenient, too. I hope I can convince you to reconsider this app behavior :)

**Comment by CarlosEvo** [comment]
I second this. I think the issue pertains to the design philosophy/convention of macOS apps. It is perhaps more reasonable to offer an option in preference to allow this behavior, as it is consistent with user habits.
