### ISSUE TITLE
Fallback render for Pleroma attachments

### ISSUE THREAD

**Issue by amyspark** [h3poteto/whalebird-desktop#796]
## Description
Pleroma doesn't send preview images for attachments, so if the attachment isn't an image (or the media proxy fails), the "No Image" placeholder is shown. This is also the case when media attachments are not media objects.

A possible fix would be to redo the fallback and, instead of showing a placeholder, render a list of attachments like Mastodon does:

<img width="312"  src="https://user-images.githubusercontent.com/13498015/50153989-d1407580-02a6-11e9-8bed-08dadcbd0a45.png">

## How To Reproduce
1. Try viewing the following toots: https://catgirl.science/notice/2854856, https://queer.hacktivis.me/objects/0a36b8ed-e8be-4141-91c3-5701b9e6a284, 

## Your Environment
 - OS: [e.g. MacOS] MacOS
 - Whalebird Version: [e.g. 1.0.0] 2.6.1-dev
 - Instance: [e.g. mastodon.social] pleroma.site

**Comment by h3poteto** [comment]
> A possible fix would be to redo the fallback and, instead of showing a placeholder, render a list of attachments like Mastodon does:

I think that it is nice.
