### ISSUE TITLE
No scrolling after new direct message is sent 

### ISSUE THREAD

**Issue by CR0CKER** [h3poteto/whalebird-desktop#797]
## Description
When responding to a Direct Message in the notification view, the new message appears on top of the message list in the main window, but scrolling up to see it is not possible. Clicking on the round blue "up" button works fine, but scrolling won't work.

## How To Reproduce
1. Respond to the latest Direct Message that's on top of the Notification view
2. Try to scroll
3. See that you cannot scroll

## Your Environment
 - OS: macOS
 - Whalebird Version: 2.6.1

**Comment by h3poteto** [comment]
Because when you respond the message, you select a toot. Whalebird does not scroll when user select a toot.

**Comment by CR0CKER** [comment]
Maybe it should? From a user perspective, I found this behavior counter-intuitive. It may be worthwhile to reconsider it if it feels like a bug from the user perspective.

**Comment by CR0CKER** [comment]
Thanks for your quick responses! Maybe I didn't explain it clearly enough. If I select a toot, I can still scroll, and the round blue button allows me to jump to the top -- that's great and works fine. But when I respond to the latest Direct Message, and I am scrolled to the top of the Direct Message list, I cannot scroll upwards to see my new Direct Message. It would be good if we either automatically scroll up to the top and show the latest Direct Message, or at least make sure that the user can scroll upwards. 

Once I briefly scroll down, I can also scroll up again. But immediately after sending the Direct Message, I cannot scroll up. This feels like a bug. I can click the blue round button to jump to the top, but I cannot scroll. See my screenshot below.

<img width="458" alt="whalebird 2018-12-19 11-06-50" src="https://user-images.githubusercontent.com/6056387/50196637-d8d34d80-037e-11e9-91fb-f0497f799130.png">

**Comment by h3poteto** [comment]
I think that this behavior occurs not only in DirectMessages but in all timelines.
And have you click the reply button when you respond to the message?

**Comment by CR0CKER** [comment]
I've tried to reproduce this issue and I think what's happening is simply that the UI freezes for a few seconds quite frequently. Even when I switch back to the app, the app often doesn't react to any scrolling for a few seconds. The animations, like the slider when opening a profile, also stutter quite a bit are not smooth. Seems to be a performance issue. But I don't see this happen with any other Electron apps I am using -- not sure what may be causing this in Whalebird.

**Comment by h3poteto** [comment]
Is this a performance issue?

**Comment by CR0CKER** [comment]
I'm not sure. But I have a pretty recent MacBook Pro and don't observe any UI stutters in any other Electron apps.
