### ISSUE TITLE
Put active cursor in compose window when replying to posts

### ISSUE THREAD

**Issue by CR0CKER** [h3poteto/whalebird-desktop#801]
## Describe
When clicking on the reply icon of a post, a lightbox compose window opens but as a user I need ti click into the text field before I can start typing. As a user I would like to cursor to be active already I can start typing right away.

## Why
Because that's what I think most users expect and it's also how the compose window for new posts already works.

**Comment by h3poteto** [comment]
I can't reproduce it.
In my machine, it is autofocused.
![peek 2018-12-21 22-17](https://user-images.githubusercontent.com/4631959/50344441-57421200-056e-11e9-823d-1b71275c8e26.gif)

**Comment by CR0CKER** [comment]
It seems to work sometimes, but more often not. See my screencast -- first time the cursor doesn't appear, second time it does. I haven't been able to discover a pattern.

![screencast](https://user-images.githubusercontent.com/6056387/50373970-89f91280-0621-11e9-9262-775250bbbb5f.gif)
