### ISSUE TITLE
Duplicate toots on slow Internet connections if "Toot" button is pressed more than once

### ISSUE THREAD

**Issue by CR0CKER** [h3poteto/whalebird-desktop#802]
## Description
Toots are posted twice if Internet connection is slow and user clicks "Toot" button again when composing a new post.

## How To Reproduce
1. Open compose window
2. Write a post and click "Toot" button
3. Click "Toot" button again before window disappears

## Your Environment
 - OS: macOS
 - Whalebird Version: 2.6.1

**Comment by h3poteto** [comment]
Is it different from #798 ?

**Comment by CR0CKER** [comment]
No, this issue here is about toots appearing twice in the timeline even though they have only been posted on the network once. #798 is about too *actually* being posted twice.
