### ISSUE TITLE
[Feature Request]: Add support for Misskey instances

### ISSUE THREAD

**Issue by marek-lach** [h3poteto/whalebird-desktop#816]
## Describe
It would be great if Whalebird could work with Misskey instances as well, besides Mastodon and Pleroma.
Misskey is a full microblogging member of the Fediverse, although a little less known than the other two.
Check out the project here: https://github.com/syuilo/Misskey

You would have to explore its APIs a bit of course, but generally its important to know that in Misskey, the individual posts on a timeline are called notes so a POST method for notes is an important call for viewing and interacting with the Misskey timeline, while POST api/users is an important call to interact with Misskey users. There may be other necessary calls to implement, of course.

Thank you,

## Why

I like Misskey a lot due to its robust modular design and implementing support would help it with much deserved exposure. I also think that implementing support for a third decentralised microblogging software is just a natural evolution for Whalebird to take. Furthermore, Misskey's flagship instance already has 3.6k users and growing, while other instances also have considerable user-bases.

**Comment by marek-lach** [comment]
Misskey supports Mastodon's API to a degree, but it also has its own API documentation here: https://藍.moe/api-doc

**Comment by syuilo** [comment]
FYI this document is newer :)
https://misskey.io/api-doc
