### ISSUE TITLE
tray icon on ubuntu

### ISSUE THREAD

**Issue by LiamDawe** [h3poteto/whalebird-desktop#822]
## Describe
Is it possibly to get a tray icon we can minimize to on Ubuntu?

## Why
Don't have to load it up constantly. Close to tray, keep notifications coming in etc.

**Comment by h3poteto** [comment]
Probably it is possible. Now slack can close to tray in Ubuntu.
But should I implement it? Is it general behavior in Ubuntu?

**Comment by LiamDawe** [comment]
Telegram and Discord certainly have no issues doing it.
