### ISSUE TITLE
Unclosed TCP connections

### ISSUE THREAD

**Issue by dermalikmann** [h3poteto/whalebird-desktop#830]
## Description
When you enable websocket Whalebird opens a new TCP connection every few seconds but doesn't close them. This leads to a lot of open connections which slowly but surely fills the servers RAM. Furthermore this effect seams to stack every time when you disable and reenable WS which leads to a DoS like behavior when executed a few times.

## How To Reproduce
1. Open whalebird
2. Enable WS
3. Disable WS
4. Reenable
5. continue, watch server log gets flooded and server RAM filled.

## Your Environment
 - OS: Win10
 - Whalebird Version: 2.6.2
 - Instance: machteburch.social

![6682b4b046f51a86](https://user-images.githubusercontent.com/3097625/51987157-1d83f580-24a2-11e9-92e8-4d04af72b476.png)

**Comment by M4lik** [comment]
BTW: Usually we are around 100 simultaneous open TCP connections. The max peak there was around 13 000 simultaneous connections
