### ISSUE TITLE
Cannot log out of accounts

### ISSUE THREAD

**Issue by feld** [h3poteto/whalebird-desktop#840]
You can log in to multiple accounts in Whalebird but I cannot find any option to log out of an account short of deleting all of the app's settings/cache to reset it completely.

**Comment by h3poteto** [comment]
You can log out to remove association in preferences. If the wording is difficult to understand, please tell me.
![screenshot from 2019-03-02 12-18-58](https://user-images.githubusercontent.com/4631959/53676415-61f2f300-3ce5-11e9-92e0-61350ed716c0.png)
