### ISSUE TITLE
No Flatpak support

### ISSUE THREAD

**Issue by yerbestpal** [h3poteto/whalebird-desktop#858]
It would be very useful to have Flatpak as an option for installing Whalebird on Linux. I think supporting Snaps and Flatpaks would cover Linux in general, removing the need to build DEB and RPM packages. It would also ensure users would have automatically updated applications.

**Comment by h3poteto** [comment]
We are using electron-builder to build this package, but now electron-builder does not support Flatpak.
https://github.com/electron-userland/electron-builder/issues/512

I'm waiting for Flatpak to be supported in electron-builder.

**Comment by h3poteto** [comment]
I've tried to use `electron-builder` + `electron-installer-flatpak` .
https://github.com/endlessm/electron-installer-flatpak

But it can't build, flatpak-builder says error:

```
$ npm run package:flatpak

> Whalebird@3.0.0 package:flatpak /home/h3poteto/src/github.com/h3poteto/whalebird-desktop
> electron-installer-flatpak --src packages/Whalebird-linux-x64/ --dest build/ --arch x64

Creating package (this may take a while)
Error: flatpak failed with status code 1
    at ChildProcess.<anonymous> (/home/h3poteto/src/github.com/h3poteto/whalebird-desktop/node_modules/flatpak-bundler/index.js:74:16)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12) Error: flatpak failed with status code 1
    at ChildProcess.<anonymous> (/home/h3poteto/src/github.com/h3poteto/whalebird-desktop/node_modules/flatpak-bundler/index.js:74:16)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:430:11)
    at Socket.emit (events.js:210:5)
    at Pipe.<anonymous> (net.js:659:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Whalebird@3.0.0 package:flatpak: `electron-installer-flatpak --src packages/Whalebird-linux-x64/ --dest build/ --arch x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Whalebird@3.0.0 package:flatpak script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/h3poteto/.npm/_logs/2019-12-21T14_44_43_790Z-debug.log
```

**Comment by x80486** [comment]
I think it's possible to build the Flatpak. In the end, it would be something like [this](https://github.com/flathub/io.github.liberodark.OpenDrive) or [this](https://github.com/flathub/com.wire.WireDesktop).

I can give it a whirl, and if it works, you can take over the maintenance of the package, which should be nothing more (most of the times) than updating the Flatpak manifest with the new version(s) and hashes.

Let me know :sunglasses:

**Comment by iKarith** [comment]
> I think it's possible to build the Flatpak. In the end, it would be something like [this](https://github.com/flathub/io.github.liberodark.OpenDrive) or [this](https://github.com/flathub/com.wire.WireDesktop).
> 
> I can give it a whirl, and if it works, you can take over the maintenance of the package, which should be nothing more (most of the times) than updating the Flatpak manifest with the new version(s) and hashes.
> 
> Let me know

Did you ever attempt this, or did you have no luck? I was thinking I might have a look at it if it was just a matter of doing what others have already done for apps like Wire or so many other Electron-based apps I already have installed … but if there's some error happening I'd have to try and working it out while learning both Electron and Flatpak.

**Comment by Lunarequest** [comment]
I have created a flatpak could I submit it to flathub? https://github.com/Lunarequest/whalebird-flatpak

**Comment by Lunarequest** [comment]
@h3poteto I have opened a pr to submit the app to flathub https://github.com/flathub/flathub/pull/2641
