### ISSUE TITLE
Toot date as link to "View Toot Details"

### ISSUE THREAD

**Issue by andcarnivorous** [h3poteto/whalebird-desktop#862]
## Describe

It would be nice if it were possible to click on a toot's date to open up the detail column on the right, without having to click on the 3 dots and then "View Toot Detail". 
## Why

It could be quite handy and save a click to open up a toot, unless there is another way of quickly doing it which I have not noticed. Plus, some mobile clients use this feature and it comes in quite handy.

**Comment by neodc** [comment]
I'd like that ! A middle click on it could also open it in the browser directly.
