### ISSUE TITLE
Polls compatibility

### ISSUE THREAD

**Issue by neodc** [h3poteto/whalebird-desktop#874]
## Describe
With the last update of Mastodon it is now possible to create and respond to polls (cf. release note https://blog.joinmastodon.org/2019/04/mastodon-2.8/). It would be really cool to be able to at least respond and see result of pools if not the ability to create some.

## Why
For now it's impossible to respond easily as we can't do it in Whalebird or even by opening it in the browser.

**Comment by pabloweb10X** [comment]
Is there any updates?
