### ISSUE TITLE
Change default timeline

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/whalebird-desktop#894]
## Describe
When the app open, it read default timeline. Some users want to change the default timeline.

## Why
😮

**Comment by h3poteto** [comment]
Sometimes user want to use LTL as the default timeline.
https://mi.siotter.xyz/notes/8j0r92n1vw

**Comment by Enqueued** [comment]
I would like to add that I would also like to change my default timeline.

**Comment by h3poteto** [comment]
Please check 6.0.0.
https://github.com/h3poteto/whalebird-desktop/releases/tag/v6.0.0
