### ISSUE TITLE
Binary for raspberry pi

### ISSUE THREAD

**Issue by thearkadia** [h3poteto/whalebird-desktop#913]
Hi, could you also include a binary for arm based devices like the Raspberry Pi?

**Comment by h3poteto** [comment]
I don't know whether to run in RaspberryPi, but I can build it.
Do you really want to run Whalebird in RaspberryPi?

**Comment by thearkadia** [comment]
Great thanks and yes I do I want to try it on https://github.com/thearkadia/The_Ark/blob/master/README.md

**Comment by h3poteto** [comment]
Whalebird is not designed for narrow display, so I think that Whalebird is not useful in your device...
And it is not popular device as desktop environment, so if I prepare binary for RaspberryPi, I think it will be only used by you.

**Comment by thearkadia** [comment]
People with raspberry pis use it with normal monitors and the community of Mastodon is even using raspberry pis to run the server software to grow the fediverse. I think it would be useful to also have a client to browse Mastodon for pis. The pi is helping alot of kids and people in low income homes learn about tech and Mastodon is a good place for that

**Comment by h3poteto** [comment]
I agree that Raspberry Pi is good device to run Mastodon server, but do they really use client to browse in the pi?

**Comment by thearkadia** [comment]
Currently there is no client so web browser must be used.

**Comment by h3poteto** [comment]
OK, I will prepare binary for `arm64`. But I can't try it because I don't have device.
