### ISSUE TITLE
snap immediately exits under wayland

### ISSUE THREAD

**Issue by vasyugan** [h3poteto/whalebird-desktop#934]
## Description

Using the snap under Debian buster, under X11, everything is fine, under Wayland (GNOME), it immediately exits, without any console output.

With strace, the last line says "write(2, "need to run as root or suid", 27need to run as root or suid) = 27
write(2, "\n", 1"

## How To Reproduce
1. Install debian buster / GNOME
2. snap install whalebird
3. run whalebird

## Your Environment
 - OS: Debian buster / snap
 - Whalebird Version: 2.7.3

**Comment by h3poteto** [comment]
I don't check Whalebird under Wayland...

**Comment by h3poteto** [comment]
https://github.com/electron/electron/issues/10915
https://github.com/electron/electron/issues/9056

**Comment by anarcobuda** [comment]
Basically, we'd have to wait Electron implement it after Chromium develops for Wayland?

**Comment by h3poteto** [comment]
Yes, we have to wait.

**Comment by anarcobuda** [comment]
Oh boy!

**Comment by shellheim** [comment]
So any progress on wayland support now??

**Comment by ckorn** [comment]
I can run discord under wayland meanwhile. But no success with whalebird.
