### ISSUE TITLE
Do not put gratuitous limits on font size

### ISSUE THREAD

**Issue by adamemerson** [h3poteto/whalebird-desktop#943]
## Describe

The font size selector should not stop me from choosing a font size larger than 18.

## Why

I have a visual impairment and need font sizes around 22, sometimes larger depending on the font and the context.

**Comment by digitalcircuit** [comment]
## Suggested fix

Modify `Appearance.vue` and increase the maximum value to either `72`, [like Firefox does for font sizes in the Preferences UI](https://dxr.mozilla.org/mozilla-central/rev/5cff72743ebc9266a78e4c6a41d17d68ac651326/browser/components/preferences/in-content/main.xul#147-175 ), or allow specifying an actual number (`Custom` or such).

### Example

**Untested way to allow up to 72 pt font**

[`src/renderer/components/Preferences/Appearance.vue`](https://github.com/h3poteto/whalebird-desktop/blob/88e11af737bcce91606e740b685a5dd50ffac00e/src/renderer/components/Preferences/Appearance.vue#L26)

```diff
--- <src/renderer/components/Preferences/Appearance.vue>
+++ <src/renderer/components/Preferences/Appearance.vue>
@@ -1,3 +1,3 @@
       <el-form-item for="font-size" :label="$t('preferences.appearance.font_size')">
-        <el-input-number id="font-size" :value="fontSize" :min="9" :max="18" @change="updateFontSize"></el-input-number>
+        <el-input-number id="font-size" :value="fontSize" :min="9" :max="72" @change="updateFontSize"></el-input-number>
       </el-form-item>
```
