### ISSUE TITLE
Whalebird fails to authorize on shitposter.club

### ISSUE THREAD

**Issue by Flat** [h3poteto/whalebird-desktop#947]
## Description
Whalebird gives the error "Failed to authorize" when trying to add an account to the Pleroma instance shitposter.club
`[error] Error: Request failed with status code 400`

## How To Reproduce
1. Enter the instance name.
2. Click 'Login' button.
3. Paste in authorization code.
4. Receive above error.

## Your Environment
 - OS: Linux
 - Whalebird Version: 2.7.5-r13-g8077606 (git master)
 - Instance: shitposter.club

**Comment by h3poteto** [comment]
OK, I will check.

**Comment by h3poteto** [comment]
I can login to `shitposter.club` in Whalebird. So I can't reproduce it.
Does your authorization code is correct?

**Comment by Flat** [comment]
I am fairly certain it is correct. I will try again later when I have access to my desktop and report back.

**Comment by Flat** [comment]
Just tried again with the same steps and it worked fine. I wonder if it was using my cached login and providing an invalid token. Either way resolved now. Thank you for looking into it!
