### ISSUE TITLE
Feature Request: proxy support

### ISSUE THREAD

**Issue by fabrei** [h3poteto/whalebird-desktop#982]
## Describe
is there any idea to implement a proxy support?

## Why
it would be nice to use whalebird via tor :)

**Comment by h3poteto** [comment]
Does that mean you want to use http proxy between your computer and some mastodon server?

I can't image that. Is there a sample application which can use proxy?

**Comment by fabrei** [comment]
i want to connect the application with the tor network. kind of the following screenshot from mozilla firefox:

![image](https://user-images.githubusercontent.com/39765984/61822471-dfb4c800-ae59-11e9-993f-61e220c22799.png)

i dont know how much work it is, but it is only a question :)

**Comment by h3poteto** [comment]
It works fine on web browser, so I think that it can.

**Comment by h3poteto** [comment]
`axios` has proxy configuration, so I can implement it, may be.

**Comment by Lyoko-Jeremie** [comment]
Request a proxy, same.

otherwise, will not work on some country like this :

![图片](https://user-images.githubusercontent.com/6566869/66371318-6bf47700-e9d5-11e9-99be-ab9569052fa4.png)

**Comment by h3poteto** [comment]
Does anyone use socks proxy? Now I am implementing this feature on: https://github.com/h3poteto/megalodon/issues/69 .
And I have implemented a new option to use http proxy, but it is not support socks proxy.

**Comment by fabrei** [comment]
+1 for socks proxy

**Comment by h3poteto** [comment]
I finished implementation of this issue, and it is contained next version. Please wait next release...

**Comment by h3poteto** [comment]
Hi there.
I released v3.0.0: https://github.com/h3poteto/whalebird-desktop/releases/tag/3.0.0
It contains proxy support, I'm sorry to be late.
