### ISSUE TITLE
download fails Whalebird-2.8.1-linux-x64.deb

### ISSUE THREAD

**Issue by galenthurber** [h3poteto/whalebird-desktop#988]
## Description

download fails to complete on all browsers tried

## How To Reproduce
1. attempt to download via firefox 68.0.1 or seamonkey 2.49.4  etc
2. download fails at 41.0MB mark

## Your Environment
 - OS: [e.g. MacOS]
Linux MX 18.3 Xubuntu 16.04  ...
 - Whalebird Version: [e.g. 1.0.0]
 - Instance: [e.g. mastodon.social]

**Comment by h3poteto** [comment]
Can you download version 2.8.2?

**Comment by galenthurber** [comment]
yes

**Comment by galenthurber** [comment]
won't connect to mastadon.social but it will connect to counter.social

**Comment by galenthurber** [comment]
mastodon not mastadon, it works, my mistake
