### ISSUE TITLE
Limit precision of numbers in poll result display

### ISSUE THREAD

**Issue by marians** [h3poteto/whalebird-desktop#989]
## Description

The precision of poll results should be displayed to 1 or 2 digits behind the decimal separator, at most.

In one example I saw 14 digits:

![image](https://user-images.githubusercontent.com/273727/62122902-0abe7200-b2c7-11e9-8eb4-cc7eb2a867da.png)

Toot with poll: https://fosstodon.org/@alexbuzzbee/102527838847574085

## How To Reproduce
1. Create a poll with two answer options
2. Get an uneven number of responses for each
3. Show the poll toot in a whalebird timeline

## Environment
 - OS: MacOS
 - Whalebird Version: 2.8.1
 - Instance: gruene.social

**Comment by h3poteto** [comment]
This is already closed: https://github.com/h3poteto/whalebird-desktop/issues/976
Please use version 2.8.2.

**Comment by marians** [comment]
Thanks!
