### ISSUE TITLE
Failed to fetch timeline in Direct Messages

### ISSUE THREAD

**Issue by mason1900** [h3poteto/whalebird-desktop#999]
## Description
The Direct Messages is unusable for mastodon.social. 

## How To Reproduce
1. Login to any account on mastodon.social (which is the flagship of mastodon instances)
2. click Direct Messages
3. An error message will show: "Failed to fetch timeline" and no Direct Messages will show up

## Your Environment
 - OS: Windows 10 1903
 - Whalebird Version: 2.8.2
 - Instance: mastodon.social

**Comment by h3poteto** [comment]
OK, I have confirmed it.
